import { GameInfo } from '@/types/game';

export const GAMES: GameInfo[] = [
  {
    id: 'quiz',
    titleRu: 'Квиз',
    titleEn: 'Quiz',
    descriptionRu: 'Отвечайте на вопросы быстрее всех! Кто наберёт больше очков — тот победитель.',
    descriptionEn: 'Answer questions faster than everyone! The one with the most points wins.',
    minPlayers: 2,
    maxPlayers: 20,
    icon: '🧠',
  },
  {
    id: 'hundred-to-one',
    titleRu: '100 к 1',
    titleEn: '100 to 1',
    descriptionRu: 'Угадайте самые популярные ответы на вопросы опросов.',
    descriptionEn: 'Guess the most popular survey answers.',
    minPlayers: 2,
    maxPlayers: 20,
    icon: '💯',
  },
  {
    id: 'crocodile',
    titleRu: 'Крокодил',
    titleEn: 'Crocodile',
    descriptionRu: 'Объясняйте слова жестами или словами, не называя само слово!',
    descriptionEn: 'Explain words using gestures or descriptions without saying the word!',
    minPlayers: 4,
    maxPlayers: 16,
    icon: '🐊',
  },
  {
    id: 'truth-or-dare',
    titleRu: 'Правда или Действие',
    titleEn: 'Truth or Dare',
    descriptionRu: 'Выбирайте: честно ответить на вопрос или выполнить задание.',
    descriptionEn: 'Choose: honestly answer a question or complete a dare.',
    minPlayers: 3,
    maxPlayers: 20,
    icon: '🎭',
  },
  {
    id: 'mafia',
    titleRu: 'Мафия',
    titleEn: 'Mafia',
    descriptionRu: 'Классическая игра. Мафия убивает ночью, горожане ищут мафию днём.',
    descriptionEn: 'Classic game. Mafia kills at night, citizens search for mafia during the day.',
    minPlayers: 6,
    maxPlayers: 16,
    icon: '🕵️',
  },
  {
    id: 'who-am-i',
    titleRu: 'Кто я?',
    titleEn: 'Who Am I?',
    descriptionRu: 'Угадайте персонажа, задавая вопросы с ответом "Да" или "Нет".',
    descriptionEn: 'Guess the character by asking Yes or No questions.',
    minPlayers: 3,
    maxPlayers: 12,
    icon: '🤔',
  },
];
