import { QuizQuestion, HundredToOneQuestion } from '@/types/game';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая планета Солнечной системы самая большая?',
    questionEn: 'What is the largest planet in our Solar System?',
    options: [
      { ru: 'Сатурн', en: 'Saturn' },
      { ru: 'Юпитер', en: 'Jupiter' },
      { ru: 'Нептун', en: 'Neptune' },
      { ru: 'Уран', en: 'Uranus' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'q2',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году пала Берлинская стена?',
    questionEn: 'In what year did the Berlin Wall fall?',
    options: [
      { ru: '1987', en: '1987' },
      { ru: '1989', en: '1989' },
      { ru: '1991', en: '1991' },
      { ru: '1985', en: '1985' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'q3',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой химический элемент обозначается символом «Au»?',
    questionEn: 'Which chemical element has the symbol "Au"?',
    options: [
      { ru: 'Серебро', en: 'Silver' },
      { ru: 'Алюминий', en: 'Aluminum' },
      { ru: 'Золото', en: 'Gold' },
      { ru: 'Медь', en: 'Copper' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'q4',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто написал роман «Мастер и Маргарита»?',
    questionEn: 'Who wrote the novel "The Master and Margarita"?',
    options: [
      { ru: 'Лев Толстой', en: 'Leo Tolstoy' },
      { ru: 'Михаил Булгаков', en: 'Mikhail Bulgakov' },
      { ru: 'Фёдор Достоевский', en: 'Fyodor Dostoevsky' },
      { ru: 'Антон Чехов', en: 'Anton Chekhov' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'q5',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько костей в теле взрослого человека?',
    questionEn: 'How many bones are in an adult human body?',
    options: [
      { ru: '186', en: '186' },
      { ru: '206', en: '206' },
      { ru: '226', en: '226' },
      { ru: '256', en: '256' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'q6',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какая столица Австралии?',
    questionEn: 'What is the capital of Australia?',
    options: [
      { ru: 'Сидней', en: 'Sydney' },
      { ru: 'Мельбурн', en: 'Melbourne' },
      { ru: 'Канберра', en: 'Canberra' },
      { ru: 'Брисбен', en: 'Brisbane' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'q7',
    topic: 'pop-culture',
    difficulty: 'easy',
    questionRu: 'Кто сыграл главную роль в фильме «Титаник» (1997)?',
    questionEn: 'Who played the lead role in the movie "Titanic" (1997)?',
    options: [
      { ru: 'Брэд Питт', en: 'Brad Pitt' },
      { ru: 'Том Хэнкс', en: 'Tom Hanks' },
      { ru: 'Леонардо Ди Каприо', en: 'Leonardo DiCaprio' },
      { ru: 'Джонни Депп', en: 'Johnny Depp' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'q8',
    topic: 'pop-culture',
    difficulty: 'easy',
    questionRu: 'Какой вид спорта называют «королевой спорта»?',
    questionEn: 'Which sport is called "the queen of sports"?',
    options: [
      { ru: 'Хоккей', en: 'Hockey' },
      { ru: 'Баскетбол', en: 'Basketball' },
      { ru: 'Лёгкая атлетика', en: 'Track and Field' },
      { ru: 'Футбол', en: 'Football (Soccer)' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'q9',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется самое глубокое озеро в мире?',
    questionEn: 'What is the deepest lake in the world?',
    options: [
      { ru: 'Каспийское море', en: 'Caspian Sea' },
      { ru: 'Байкал', en: 'Lake Baikal' },
      { ru: 'Танганьика', en: 'Lake Tanganyika' },
      { ru: 'Озеро Верхнее', en: 'Lake Superior' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'q10',
    topic: 'pop-culture',
    difficulty: 'easy',
    questionRu: 'Сколько струн у стандартной гитары?',
    questionEn: 'How many strings does a standard guitar have?',
    options: [
      { ru: '4', en: '4' },
      { ru: '5', en: '5' },
      { ru: '6', en: '6' },
      { ru: '8', en: '8' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
];

export const HUNDRED_TO_ONE_QUESTIONS: HundredToOneQuestion[] = [
  {
    id: 'h1',
    questionRu: 'Что люди берут с собой на пляж?',
    questionEn: 'What do people take to the beach?',
    answers: [
      { textRu: 'Полотенце', textEn: 'Towel', points: 38 },
      { textRu: 'Крем от загара', textEn: 'Sunscreen', points: 24 },
      { textRu: 'Купальник', textEn: 'Swimsuit', points: 16 },
      { textRu: 'Очки от солнца', textEn: 'Sunglasses', points: 11 },
      { textRu: 'Еда и напитки', textEn: 'Food and drinks', points: 7 },
      { textRu: 'Мяч', textEn: 'Ball', points: 4 },
    ],
  },
  {
    id: 'h2',
    questionRu: 'Что чаще всего забывают дома, уходя на работу?',
    questionEn: 'What do people most often forget at home when leaving for work?',
    answers: [
      { textRu: 'Телефон', textEn: 'Phone', points: 40 },
      { textRu: 'Ключи', textEn: 'Keys', points: 25 },
      { textRu: 'Кошелёк', textEn: 'Wallet', points: 14 },
      { textRu: 'Зонт', textEn: 'Umbrella', points: 10 },
      { textRu: 'Обед', textEn: 'Lunch', points: 7 },
      { textRu: 'Документы', textEn: 'Documents', points: 4 },
    ],
  },
  {
    id: 'h3',
    questionRu: 'Назовите причину опоздания на работу.',
    questionEn: 'Name a reason for being late to work.',
    answers: [
      { textRu: 'Пробки', textEn: 'Traffic', points: 42 },
      { textRu: 'Проспал', textEn: 'Overslept', points: 26 },
      { textRu: 'Сломался транспорт', textEn: 'Transport broke down', points: 13 },
      { textRu: 'Ребёнок', textEn: 'Child-related issue', points: 9 },
      { textRu: 'Плохая погода', textEn: 'Bad weather', points: 6 },
      { textRu: 'Забыл что-то дома', textEn: 'Forgot something at home', points: 4 },
    ],
  },
  {
    id: 'h4',
    questionRu: 'Что делают люди в очереди?',
    questionEn: 'What do people do while waiting in line?',
    answers: [
      { textRu: 'Смотрят в телефон', textEn: 'Look at their phone', points: 45 },
      { textRu: 'Разговаривают', textEn: 'Talk to each other', points: 20 },
      { textRu: 'Скучают / ждут', textEn: 'Get bored / wait', points: 14 },
      { textRu: 'Читают', textEn: 'Read', points: 10 },
      { textRu: 'Ругаются', textEn: 'Complain', points: 7 },
      { textRu: 'Слушают музыку', textEn: 'Listen to music', points: 4 },
    ],
  },
  {
    id: 'h5',
    questionRu: 'Назовите популярный новогодний подарок.',
    questionEn: 'Name a popular New Year / Christmas gift.',
    answers: [
      { textRu: 'Парфюм', textEn: 'Perfume', points: 35 },
      { textRu: 'Деньги', textEn: 'Money', points: 25 },
      { textRu: 'Сладости', textEn: 'Sweets / Chocolate', points: 16 },
      { textRu: 'Игрушка', textEn: 'Toy', points: 11 },
      { textRu: 'Одежда', textEn: 'Clothing', points: 8 },
      { textRu: 'Книга', textEn: 'Book', points: 5 },
    ],
  },
];

export const CROCODILE_WORDS: { ru: string; en: string }[] = [
  { ru: 'Космонавт', en: 'Astronaut' },
  { ru: 'Пылесос', en: 'Vacuum cleaner' },
  { ru: 'Светофор', en: 'Traffic light' },
  { ru: 'Подушка', en: 'Pillow' },
  { ru: 'Зеркало', en: 'Mirror' },
  { ru: 'Холодильник', en: 'Refrigerator' },
  { ru: 'Бабочка', en: 'Butterfly' },
  { ru: 'Велосипед', en: 'Bicycle' },
  { ru: 'Фотоаппарат', en: 'Camera' },
  { ru: 'Зонтик', en: 'Umbrella' },
  { ru: 'Пианино', en: 'Piano' },
  { ru: 'Крокодил', en: 'Crocodile' },
  { ru: 'Самолёт', en: 'Airplane' },
  { ru: 'Телевизор', en: 'Television' },
  { ru: 'Микроволновка', en: 'Microwave' },
  { ru: 'Жираф', en: 'Giraffe' },
  { ru: 'Футболист', en: 'Football player' },
  { ru: 'Снеговик', en: 'Snowman' },
  { ru: 'Клоун', en: 'Clown' },
  { ru: 'Ракета', en: 'Rocket' },
  { ru: 'Балерина', en: 'Ballerina' },
  { ru: 'Будильник', en: 'Alarm clock' },
  { ru: 'Попугай', en: 'Parrot' },
  { ru: 'Стиральная машина', en: 'Washing machine' },
  { ru: 'Паук', en: 'Spider' },
  { ru: 'Лифт', en: 'Elevator' },
  { ru: 'Дельфин', en: 'Dolphin' },
  { ru: 'Пожарный', en: 'Firefighter' },
  { ru: 'Кактус', en: 'Cactus' },
  { ru: 'Скрипка', en: 'Violin' },
  { ru: 'Акула', en: 'Shark' },
  { ru: 'Пингвин', en: 'Penguin' },
  { ru: 'Робот', en: 'Robot' },
  { ru: 'Водопад', en: 'Waterfall' },
  { ru: 'Барабан', en: 'Drum' },
  { ru: 'Хамелеон', en: 'Chameleon' },
  { ru: 'Фокусник', en: 'Magician' },
  { ru: 'Компас', en: 'Compass' },
  { ru: 'Вулкан', en: 'Volcano' },
  { ru: 'Сёрфинг', en: 'Surfing' },
  { ru: 'Граффити', en: 'Graffiti' },
  { ru: 'Пират', en: 'Pirate' },
  { ru: 'Маяк', en: 'Lighthouse' },
  { ru: 'Каток', en: 'Ice rink' },
  { ru: 'Шахматы', en: 'Chess' },
  { ru: 'Аквариум', en: 'Aquarium' },
  { ru: 'Вертолёт', en: 'Helicopter' },
  { ru: 'Носорог', en: 'Rhinoceros' },
  { ru: 'Батут', en: 'Trampoline' },
  { ru: 'Айсберг', en: 'Iceberg' },
];

export type Difficulty = 'easy' | 'medium' | 'hard';

export const TRUTHS: { ru: string; en: string; difficulty: Difficulty }[] = [
  // Easy
  { ru: 'Какой твой самый неловкий момент в школе?', en: 'What is your most embarrassing moment at school?', difficulty: 'easy' },
  { ru: 'Какой фильм заставил тебя плакать?', en: 'What movie made you cry?', difficulty: 'easy' },
  { ru: 'Какой у тебя самый странный страх?', en: 'What is your strangest fear?', difficulty: 'easy' },
  { ru: 'Какую песню ты тайно любишь?', en: 'What song do you secretly love?', difficulty: 'easy' },
  { ru: 'Какое твоё виноватое удовольствие?', en: 'What is your guilty pleasure?', difficulty: 'easy' },
  // Medium
  { ru: 'Ты когда-нибудь врал лучшему другу?', en: 'Have you ever lied to your best friend?', difficulty: 'medium' },
  { ru: 'Какой самый глупый поступок ты совершил?', en: 'What is the dumbest thing you have ever done?', difficulty: 'medium' },
  { ru: 'О чём ты больше всего жалеешь?', en: 'What do you regret the most?', difficulty: 'medium' },
  { ru: 'Ты когда-нибудь подслушивал чужой разговор?', en: 'Have you ever eavesdropped on someone?', difficulty: 'medium' },
  { ru: 'Какой секрет ты скрываешь от родителей?', en: 'What secret are you hiding from your parents?', difficulty: 'medium' },
  // Hard
  { ru: 'Покажи последнюю фотографию в галерее телефона.', en: 'Show the last photo in your phone gallery.', difficulty: 'hard' },
  { ru: 'Прочитай вслух последнее сообщение в мессенджере.', en: 'Read your last messenger message out loud.', difficulty: 'hard' },
  { ru: 'Расскажи о самом постыдном моменте в твоей жизни.', en: 'Tell us about the most shameful moment of your life.', difficulty: 'hard' },
  { ru: 'Кого из присутствующих ты бы пригласил на свидание?', en: 'Who here would you ask out on a date?', difficulty: 'hard' },
  { ru: 'Какой самый безумный поступок ты совершил ради кого-то?', en: 'What is the craziest thing you have done for someone?', difficulty: 'hard' },
];

export const DARES: { ru: string; en: string; difficulty: Difficulty }[] = [
  // Easy
  { ru: 'Изобрази любое животное в течение 30 секунд.', en: 'Imitate any animal for 30 seconds.', difficulty: 'easy' },
  { ru: 'Спой куплет любой песни.', en: 'Sing a verse of any song.', difficulty: 'easy' },
  { ru: 'Сделай 10 приседаний прямо сейчас.', en: 'Do 10 squats right now.', difficulty: 'easy' },
  { ru: 'Расскажи скороговорку 3 раза подряд.', en: 'Say a tongue twister 3 times in a row.', difficulty: 'easy' },
  { ru: 'Нарисуй автопортрет за 30 секунд.', en: 'Draw a self-portrait in 30 seconds.', difficulty: 'easy' },
  // Medium
  { ru: 'Позвони случайному контакту и скажи "Я тебя люблю".', en: 'Call a random contact and say "I love you".', difficulty: 'medium' },
  { ru: 'Танцуй без музыки 1 минуту.', en: 'Dance without music for 1 minute.', difficulty: 'medium' },
  { ru: 'Говори с акцентом следующие 3 раунда.', en: 'Speak with an accent for the next 3 rounds.', difficulty: 'medium' },
  { ru: 'Сделай комплимент каждому игроку.', en: 'Give a compliment to every player.', difficulty: 'medium' },
  { ru: 'Изобрази знаменитость, пока другие не угадают.', en: 'Impersonate a celebrity until others guess who.', difficulty: 'medium' },
  // Hard
  { ru: 'Опубликуй смешное селфи в соцсетях прямо сейчас.', en: 'Post a funny selfie on social media right now.', difficulty: 'hard' },
  { ru: 'Съешь ложку горчицы или кетчупа.', en: 'Eat a spoonful of mustard or ketchup.', difficulty: 'hard' },
  { ru: 'Не пользуйся телефоном до конца игры.', en: 'Do not use your phone until the end of the game.', difficulty: 'hard' },
  { ru: 'Позволь любому игроку написать пост от твоего имени.', en: 'Let any player write a post on your behalf.', difficulty: 'hard' },
  { ru: 'Выйди на улицу и громко крикни "Я суперзвезда!".', en: 'Go outside and shout "I am a superstar!" loudly.', difficulty: 'hard' },
];

export const WHO_AM_I_CHARACTERS: { ru: string; en: string }[] = [
  { ru: 'Альберт Эйнштейн', en: 'Albert Einstein' },
  { ru: 'Клеопатра', en: 'Cleopatra' },
  { ru: 'Гарри Поттер', en: 'Harry Potter' },
  { ru: 'Мадонна', en: 'Madonna' },
  { ru: 'Наполеон Бонапарт', en: 'Napoleon Bonaparte' },
  { ru: 'Шрек', en: 'Shrek' },
  { ru: 'Илон Маск', en: 'Elon Musk' },
  { ru: 'Микки Маус', en: 'Mickey Mouse' },
  { ru: 'Моцарт', en: 'Mozart' },
  { ru: 'Дарт Вейдер', en: 'Darth Vader' },
  { ru: 'Мэрилин Монро', en: 'Marilyn Monroe' },
  { ru: 'Гомер Симпсон', en: 'Homer Simpson' },
  { ru: 'Леонардо да Винчи', en: 'Leonardo da Vinci' },
  { ru: 'Джеймс Бонд', en: 'James Bond' },
  { ru: 'Фрида Кало', en: 'Frida Kahlo' },
  { ru: 'Супер Марио', en: 'Super Mario' },
  { ru: 'Юрий Гагарин', en: 'Yuri Gagarin' },
  { ru: 'Бэтмен', en: 'Batman' },
  { ru: 'Чарли Чаплин', en: 'Charlie Chaplin' },
  { ru: 'Эльза (Холодное сердце)', en: 'Elsa (Frozen)' },
  { ru: 'Фредди Меркьюри', en: 'Freddie Mercury' },
  { ru: 'Пикачу', en: 'Pikachu' },
  { ru: 'Чингисхан', en: 'Genghis Khan' },
  { ru: 'Тони Старк', en: 'Tony Stark' },
  { ru: 'Винни-Пух', en: 'Winnie the Pooh' },
  { ru: 'Майкл Джексон', en: 'Michael Jackson' },
  { ru: 'Шерлок Холмс', en: 'Sherlock Holmes' },
  { ru: 'Золушка', en: 'Cinderella' },
  { ru: 'Боб Марли', en: 'Bob Marley' },
  { ru: 'Чебурашка', en: 'Cheburashka' },
];

// Spy game words — simple nouns easy to explain/draw
export const SPY_WORDS: string[] = [
  'Кошка', 'Собака', 'Дом', 'Машина', 'Солнце',
  'Дерево', 'Рыба', 'Птица', 'Цветок', 'Книга',
  'Стул', 'Стол', 'Телефон', 'Зонт', 'Шляпа',
  'Мяч', 'Гитара', 'Самолёт', 'Корабль', 'Поезд',
  'Замок', 'Ракета', 'Пицца', 'Торт', 'Мороженое',
  'Очки', 'Часы', 'Луна', 'Звезда', 'Облако',
  'Снеговик', 'Робот', 'Динозавр', 'Бабочка', 'Паук',
  'Ключ', 'Лампа', 'Камера', 'Велосипед', 'Барабан',
  'Ножницы', 'Свеча', 'Арбуз', 'Банан', 'Яблоко',
  'Медведь', 'Лев', 'Слон', 'Жираф', 'Пингвин',
  'Компьютер', 'Телевизор', 'Холодильник', 'Кактус', 'Грибок',
  'Корона', 'Меч', 'Щит', 'Флаг', 'Палатка',
];

export interface SpyLocation {
  category: string;
  categoryIcon: string;
  word: string;
}

export const SPY_LOCATIONS: SpyLocation[] = [
  // Места
  { category: 'Места', categoryIcon: '📍', word: 'Аэропорт' },
  { category: 'Места', categoryIcon: '📍', word: 'Вокзал' },
  { category: 'Места', categoryIcon: '📍', word: 'Школа' },
  { category: 'Места', categoryIcon: '📍', word: 'Больница' },
  { category: 'Места', categoryIcon: '📍', word: 'Пляж' },
  { category: 'Места', categoryIcon: '📍', word: 'Театр' },
  { category: 'Места', categoryIcon: '📍', word: 'Ресторан' },
  { category: 'Места', categoryIcon: '📍', word: 'Тюрьма' },
  { category: 'Места', categoryIcon: '📍', word: 'Казино' },
  { category: 'Места', categoryIcon: '📍', word: 'Библиотека' },
  // Природа
  { category: 'Природа', categoryIcon: '🌿', word: 'Лес' },
  { category: 'Природа', categoryIcon: '🌿', word: 'Горы' },
  { category: 'Природа', categoryIcon: '🌿', word: 'Пустыня' },
  { category: 'Природа', categoryIcon: '🌿', word: 'Джунгли' },
  { category: 'Природа', categoryIcon: '🌿', word: 'Пещера' },
  { category: 'Природа', categoryIcon: '🌿', word: 'Остров' },
  // Работа
  { category: 'Работа', categoryIcon: '🏢', word: 'Офис' },
  { category: 'Работа', categoryIcon: '🏢', word: 'Фабрика' },
  { category: 'Работа', categoryIcon: '🏢', word: 'Стройка' },
  { category: 'Работа', categoryIcon: '🏢', word: 'Лаборатория' },
  { category: 'Работа', categoryIcon: '🏢', word: 'Ферма' },
  { category: 'Работа', categoryIcon: '🏢', word: 'Шахта' },
  // Развлечения
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Цирк' },
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Стадион' },
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Кинотеатр' },
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Музей' },
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Аквапарк' },
  { category: 'Развлечения', categoryIcon: '🎭', word: 'Зоопарк' },
  // Транспорт
  { category: 'Транспорт', categoryIcon: '🚗', word: 'Самолёт' },
  { category: 'Транспорт', categoryIcon: '🚗', word: 'Подводная лодка' },
  { category: 'Транспорт', categoryIcon: '🚗', word: 'Поезд' },
  { category: 'Транспорт', categoryIcon: '🚗', word: 'Корабль' },
  { category: 'Транспорт', categoryIcon: '🚗', word: 'Ракета' },
];

export const ALIAS_WORDS: { ru: string; en: string }[] = [
  { ru: 'Авторитет', en: 'Authority' },
  { ru: 'Вдохновение', en: 'Inspiration' },
  { ru: 'Перемирие', en: 'Ceasefire' },
  { ru: 'Справедливость', en: 'Justice' },
  { ru: 'Наслаждение', en: 'Delight' },
  { ru: 'Путешествие', en: 'Journey' },
  { ru: 'Библиотека', en: 'Library' },
  { ru: 'Землетрясение', en: 'Earthquake' },
  { ru: 'Фотография', en: 'Photography' },
  { ru: 'Каникулы', en: 'Vacation' },
  { ru: 'Приключение', en: 'Adventure' },
  { ru: 'Клавиатура', en: 'Keyboard' },
  { ru: 'Одиночество', en: 'Loneliness' },
  { ru: 'Фейерверк', en: 'Fireworks' },
  { ru: 'Воображение', en: 'Imagination' },
  { ru: 'Бутерброд', en: 'Sandwich' },
  { ru: 'Перекрёсток', en: 'Crossroads' },
  { ru: 'Аплодисменты', en: 'Applause' },
  { ru: 'Термометр', en: 'Thermometer' },
  { ru: 'Карусель', en: 'Carousel' },
  { ru: 'Предательство', en: 'Betrayal' },
  { ru: 'Водопад', en: 'Waterfall' },
  { ru: 'Ностальгия', en: 'Nostalgia' },
  { ru: 'Будильник', en: 'Alarm clock' },
  { ru: 'Лабиринт', en: 'Labyrinth' },
  { ru: 'Маскарад', en: 'Masquerade' },
  { ru: 'Горизонт', en: 'Horizon' },
  { ru: 'Чемодан', en: 'Suitcase' },
  { ru: 'Страховка', en: 'Insurance' },
  { ru: 'Бессонница', en: 'Insomnia' },
  { ru: 'Телескоп', en: 'Telescope' },
  { ru: 'Сувенир', en: 'Souvenir' },
  { ru: 'Конкуренция', en: 'Competition' },
  { ru: 'Парашют', en: 'Parachute' },
  { ru: 'Электричество', en: 'Electricity' },
  { ru: 'Головоломка', en: 'Puzzle' },
  { ru: 'Традиция', en: 'Tradition' },
  { ru: 'Невесомость', en: 'Weightlessness' },
  { ru: 'Светлячок', en: 'Firefly' },
  { ru: 'Репутация', en: 'Reputation' },
  { ru: 'Калейдоскоп', en: 'Kaleidoscope' },
  { ru: 'Наводнение', en: 'Flood' },
  { ru: 'Дирижёр', en: 'Conductor' },
  { ru: 'Переговоры', en: 'Negotiations' },
  { ru: 'Подсолнух', en: 'Sunflower' },
  { ru: 'Суеверие', en: 'Superstition' },
  { ru: 'Рецепт', en: 'Recipe' },
  { ru: 'Силуэт', en: 'Silhouette' },
  { ru: 'Антракт', en: 'Intermission' },
  { ru: 'Генератор', en: 'Generator' },
  { ru: 'Напёрсток', en: 'Thimble' },
  { ru: 'Пропаганда', en: 'Propaganda' },
  { ru: 'Айсберг', en: 'Iceberg' },
  { ru: 'Детектив', en: 'Detective' },
  { ru: 'Серенада', en: 'Serenade' },
  { ru: 'Балкон', en: 'Balcony' },
  { ru: 'Гипотеза', en: 'Hypothesis' },
  { ru: 'Талисман', en: 'Talisman' },
  { ru: 'Вулкан', en: 'Volcano' },
  { ru: 'Экзамен', en: 'Exam' },
  { ru: 'Миграция', en: 'Migration' },
  { ru: 'Пантомима', en: 'Pantomime' },
  { ru: 'Рефлекс', en: 'Reflex' },
  { ru: 'Лотерея', en: 'Lottery' },
  { ru: 'Компромисс', en: 'Compromise' },
  { ru: 'Эволюция', en: 'Evolution' },
  { ru: 'Катастрофа', en: 'Catastrophe' },
  { ru: 'Галактика', en: 'Galaxy' },
  { ru: 'Прогноз', en: 'Forecast' },
  { ru: 'Дипломатия', en: 'Diplomacy' },
  { ru: 'Урожай', en: 'Harvest' },
  { ru: 'Мелодия', en: 'Melody' },
  { ru: 'Скульптура', en: 'Sculpture' },
  { ru: 'Пароль', en: 'Password' },
  { ru: 'Стратегия', en: 'Strategy' },
  { ru: 'Аквариум', en: 'Aquarium' },
  { ru: 'Оптимизм', en: 'Optimism' },
  { ru: 'Маяк', en: 'Lighthouse' },
  { ru: 'Гравитация', en: 'Gravity' },
  { ru: 'Обещание', en: 'Promise' },
];
