import { GameInfo } from '@/types/game';

export const GAMES: GameInfo[] = [
  {
    id: 'quiz',
    titleRu: 'Квиз',
    titleEn: 'Quiz',
    descriptionRu: 'Отвечайте на вопросы быстрее всех! Кто наберёт больше очков — тот победитель.',
    descriptionEn: 'Answer questions faster than everyone! The one with the most points wins.',
    minPlayers: 2,
    maxPlayers: 20,
    icon: '🧠',
  },
  {
    id: 'hundred-to-one',
    titleRu: '100 к 1',
    titleEn: '100 to 1',
    descriptionRu: 'Угадайте самые популярные ответы на вопросы опросов.',
    descriptionEn: 'Guess the most popular survey answers.',
    minPlayers: 2,
    maxPlayers: 20,
    icon: '💯',
  },
  {
    id: 'crocodile',
    titleRu: 'Крокодил',
    titleEn: 'Crocodile',
    descriptionRu: 'Объясняйте слова жестами или словами, не называя само слово!',
    descriptionEn: 'Explain words using gestures or descriptions without saying the word!',
    minPlayers: 4,
    maxPlayers: 16,
    icon: '🐊',
  },
  {
    id: 'spy',
    titleRu: 'Шпион',
    titleEn: 'Spy',
    descriptionRu: 'Один из вас — шпион! Угадайте слово или найдите шпиона.',
    descriptionEn: 'One of you is a spy! Guess the word or find the spy.',
    minPlayers: 3,
    maxPlayers: 20,
    icon: '🕵️‍♂️',
  },
  {
    id: 'alias',
    titleRu: 'Угадай слово',
    titleEn: 'Guess the Word',
    descriptionRu: 'Объясняйте слова за ограниченное время! Чем больше угадаете — тем больше очков.',
    descriptionEn: 'Explain words before time runs out! The more you guess, the more points you earn.',
    minPlayers: 4,
    maxPlayers: 20,
    icon: '💬',
  },
  {
    id: 'mafia',
    titleRu: 'Мафия',
    titleEn: 'Mafia',
    descriptionRu: 'Классическая игра. Мафия убивает ночью, горожане ищут мафию днём.',
    descriptionEn: 'Classic game. Mafia kills at night, citizens search for mafia during the day.',
    minPlayers: 6,
    maxPlayers: 16,
    icon: '🕵️',
  },
  {
    id: 'who-am-i',
    titleRu: 'Кто я?',
    titleEn: 'Who Am I?',
    descriptionRu: 'Угадайте персонажа, задавая вопросы с ответом "Да" или "Нет".',
    descriptionEn: 'Guess the character by asking Yes or No questions.',
    minPlayers: 3,
    maxPlayers: 12,
    icon: '🤔',
  },
];
