import { QuizQuestion } from '@/types/game';

export const HARRY_POTTER_1_QUESTIONS: QuizQuestion[] = [
  {
    id: 'hp1-1',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Какое животное является анимагусом Сириуса Блэка?',
    questionEn: 'What animal is Sirius Black\'s Animagus form?',
    options: [
      { ru: 'Кот', en: 'Cat' },
      { ru: 'Большая чёрная собака', en: 'Large black dog' },
      { ru: 'Олень', en: 'Stag' },
      { ru: 'Крыса', en: 'Rat' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hp1-2',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Какого цвета глаза у Люциуса Малфоя?',
    questionEn: 'What color are Lucius Malfoy\'s eyes?',
    options: [
      { ru: 'Чёрные', en: 'Black' },
      { ru: 'Голубые ледяные', en: 'Icy blue' },
      { ru: 'Серые холодные', en: 'Cold grey' },
      { ru: 'Зелёные', en: 'Green' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hp1-3',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Сколько лет провёл Сириус Блэк в Азкабане?',
    questionEn: 'How many years did Sirius Black spend in Azkaban?',
    options: [
      { ru: '10', en: '10' },
      { ru: '12', en: '12' },
      { ru: '14', en: '14' },
      { ru: '15', en: '15' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hp1-4',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Какой клуб основал Гарри в пятом курсе?',
    questionEn: 'What club did Harry found in his fifth year?',
    options: [
      { ru: 'Клуб дуэльной магии', en: 'Duelling Club' },
      { ru: 'Отряд Дамблдора', en: 'Dumbledore\'s Army' },
      { ru: 'Клуб защиты от тёмных искусств', en: 'Defence Against the Dark Arts Club' },
      { ru: 'Клуб любителей полётов на метле', en: 'Broomstick Flying Club' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hp1-5',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Кто охранял вход в башню Гриффиндора на протяжении всей учёбы Гарри?',
    questionEn: 'Who guarded the entrance to Gryffindor Tower throughout Harry\'s time at Hogwarts?',
    options: [
      { ru: 'Портрет Кровавого Барона', en: 'Portrait of the Bloody Baron' },
      { ru: 'Портрет Толстой Леди', en: 'Portrait of the Fat Lady' },
      { ru: 'Портрет пирата Барбоссы', en: 'Portrait of Pirate Barbossa' },
      { ru: 'Портрет сэра Кадогана', en: 'Portrait of Sir Cadogan' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hp1-6',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Сколько братьев и сестёр у Рона Уизли?',
    questionEn: 'How many siblings does Ron Weasley have?',
    options: [
      { ru: '4', en: '4' },
      { ru: '5', en: '5' },
      { ru: '6', en: '6' },
      { ru: '7', en: '7' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hp1-7',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Сколько крестражей намеренно создал Волдеморт (не считая Гарри)?',
    questionEn: 'How many Horcruxes did Voldemort intentionally create (not counting Harry)?',
    options: [
      { ru: '5', en: '5' },
      { ru: '6', en: '6' },
      { ru: '7', en: '7' },
      { ru: '8', en: '8' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hp1-8',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Кто в последний момент стал Хранителем тайны семьи Поттеров?',
    questionEn: 'Who became the Secret Keeper for the Potter family at the last moment?',
    options: [
      { ru: 'Сириус Блэк', en: 'Sirius Black' },
      { ru: 'Альбус Дамблдор', en: 'Albus Dumbledore' },
      { ru: 'Питер Петтигрю', en: 'Peter Pettigrew' },
      { ru: 'Ремус Люпин', en: 'Remus Lupin' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hp1-9',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как зовут домового эльфа семьи Малфой?',
    questionEn: 'What is the name of the Malfoy family\'s house-elf?',
    options: [
      { ru: 'Добби', en: 'Dobby' },
      { ru: 'Кикимер', en: 'Kreacher' },
      { ru: 'Хоки', en: 'Hokey' },
      { ru: 'Винки', en: 'Winky' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'hp1-10',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Кто рассказал молодому Тому Реддлу о крестражах?',
    questionEn: 'Who told the young Tom Riddle about Horcruxes?',
    options: [
      { ru: 'Дамблдор', en: 'Dumbledore' },
      { ru: 'Профессор Слагхорн', en: 'Professor Slughorn' },
      { ru: 'Беллатриса Лестрейндж', en: 'Bellatrix Lestrange' },
      { ru: 'Профессор Квиррелл', en: 'Professor Quirrell' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
];
