import { QuizQuestion } from '@/types/game';

export const MARVEL_1_QUESTIONS: QuizQuestion[] = [
  {
    id: 'mv1-1',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как настоящее имя Капитана Америка?',
    questionEn: 'What is Captain America\'s real name?',
    options: [
      { ru: 'Джеймс Роудс', en: 'James Rhodes' },
      { ru: 'Стив Роджерс', en: 'Steve Rogers' },
      { ru: 'Сэм Уилсон', en: 'Sam Wilson' },
      { ru: 'Баки Барнс', en: 'Bucky Barnes' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'mv1-2',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Какой камень Бесконечности был вставлен в лоб Вижна?',
    questionEn: 'Which Infinity Stone was embedded in Vision\'s forehead?',
    options: [
      { ru: 'Камень Души', en: 'Soul Stone' },
      { ru: 'Камень Реальности', en: 'Reality Stone' },
      { ru: 'Камень Разума', en: 'Mind Stone' },
      { ru: 'Камень Силы', en: 'Power Stone' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'mv1-3',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'На какой планете находится Камень Души в «Войне бесконечности»?',
    questionEn: 'On which planet is the Soul Stone located in Avengers: Infinity War?',
    options: [
      { ru: 'Нор', en: 'Knowhere' },
      { ru: 'Вормир', en: 'Vormir' },
      { ru: 'Ксандар', en: 'Xandar' },
      { ru: 'Асгард', en: 'Asgard' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'mv1-4',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как называется молот Тора?',
    questionEn: 'What is the name of Thor\'s hammer?',
    options: [
      { ru: 'Громобой', en: 'Stormbreaker' },
      { ru: 'Гунгнир', en: 'Gungnir' },
      { ru: 'Мьёльнир', en: 'Mjolnir' },
      { ru: 'Ярнбьёрн', en: 'Jarnbjorn' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'mv1-5',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Кто пожертвовал собой ради Камня Души в «Мстители: Финал»?',
    questionEn: 'Who sacrificed themselves for the Soul Stone in Avengers: Endgame?',
    options: [
      { ru: 'Железный Человек', en: 'Iron Man' },
      { ru: 'Чёрная Вдова', en: 'Black Widow' },
      { ru: 'Капитан Америка', en: 'Captain America' },
      { ru: 'Соколиный Глаз', en: 'Hawkeye' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'mv1-6',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как называется родина Чёрной Пантеры?',
    questionEn: 'What is the name of Black Panther\'s homeland?',
    options: [
      { ru: 'Мадрипур', en: 'Madripoor' },
      { ru: 'Соковия', en: 'Sokovia' },
      { ru: 'Ваканда', en: 'Wakanda' },
      { ru: 'Генош', en: 'Genosha' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'mv1-7',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как настоящее имя Человека-паука в MCU?',
    questionEn: 'What is Spider-Man\'s real name in the MCU?',
    options: [
      { ru: 'Майлз Моралес', en: 'Miles Morales' },
      { ru: 'Питер Паркер', en: 'Peter Parker' },
      { ru: 'Бен Рейли', en: 'Ben Reilly' },
      { ru: 'Мигель О\'Хара', en: 'Miguel O\'Hara' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'mv1-8',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Кто создал Альтрона?',
    questionEn: 'Who created Ultron?',
    options: [
      { ru: 'Тони Старк и Брюс Бэннер', en: 'Tony Stark and Bruce Banner' },
      { ru: 'Только Тони Старк', en: 'Tony Stark alone' },
      { ru: 'Ник Фьюри', en: 'Nick Fury' },
      { ru: 'ГИДРА', en: 'HYDRA' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'mv1-9',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Какую организацию возглавляет Ник Фьюри?',
    questionEn: 'Which organization does Nick Fury lead?',
    options: [
      { ru: 'ГИДРА', en: 'HYDRA' },
      { ru: 'АИМ', en: 'AIM' },
      { ru: 'Щ.И.Т.', en: 'S.H.I.E.L.D.' },
      { ru: 'СВОРД', en: 'SWORD' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'mv1-10',
    topic: 'pop-culture',
    difficulty: 'medium',
    questionRu: 'Как зовут ИИ-помощника Тони Старка в ранних фильмах MCU?',
    questionEn: 'What is the name of Tony Stark\'s AI assistant in the early MCU films?',
    options: [
      { ru: 'ПЯТНИЦА', en: 'FRIDAY' },
      { ru: 'ВИЖН', en: 'VISION' },
      { ru: 'ДЖАРВИС', en: 'JARVIS' },
      { ru: 'ЭДИТ', en: 'EDITH' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
];
