import { QuizQuestion } from '@/types/game';

export const HISTORY_QUESTIONS: QuizQuestion[] = [
  // === EASY (1-17) ===
  {
    id: 'hist-1',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был первым президентом США?',
    questionEn: 'Who was the first president of the United States?',
    options: [
      { ru: 'Джордж Вашингтон', en: 'George Washington' },
      { ru: 'Томас Джефферсон', en: 'Thomas Jefferson' },
      { ru: 'Бенджамин Франклин', en: 'Benjamin Franklin' },
      { ru: 'Джон Адамс', en: 'John Adams' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'hist-2',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году закончилась Вторая мировая война?',
    questionEn: 'In what year did World War II end?',
    options: [
      { ru: '1943', en: '1943' },
      { ru: '1944', en: '1944' },
      { ru: '1945', en: '1945' },
      { ru: '1946', en: '1946' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-3',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какая древняя цивилизация построила пирамиды в Гизе?',
    questionEn: 'Which ancient civilization built the pyramids of Giza?',
    options: [
      { ru: 'Римляне', en: 'Romans' },
      { ru: 'Греки', en: 'Greeks' },
      { ru: 'Египтяне', en: 'Egyptians' },
      { ru: 'Персы', en: 'Persians' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-4',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто открыл Америку в 1492 году?',
    questionEn: 'Who discovered America in 1492?',
    options: [
      { ru: 'Фернан Магеллан', en: 'Ferdinand Magellan' },
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Васко да Гама', en: 'Vasco da Gama' },
      { ru: 'Америго Веспуччи', en: 'Amerigo Vespucci' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-5',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой город был столицей Римской империи?',
    questionEn: 'What city was the capital of the Roman Empire?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Рим', en: 'Rome' },
      { ru: 'Карфаген', en: 'Carthage' },
      { ru: 'Александрия', en: 'Alexandria' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-6',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был первым человеком, полетевшим в космос?',
    questionEn: 'Who was the first person to fly into space?',
    options: [
      { ru: 'Нил Армстронг', en: 'Neil Armstrong' },
      { ru: 'Юрий Гагарин', en: 'Yuri Gagarin' },
      { ru: 'Алан Шепард', en: 'Alan Shepard' },
      { ru: 'Валентина Терешкова', en: 'Valentina Tereshkova' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-7',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В какой стране произошла Октябрьская революция 1917 года?',
    questionEn: 'In which country did the October Revolution of 1917 take place?',
    options: [
      { ru: 'Германия', en: 'Germany' },
      { ru: 'Франция', en: 'France' },
      { ru: 'Россия', en: 'Russia' },
      { ru: 'Китай', en: 'China' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-8',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какое сооружение является символом Китая и видно из космоса по легенде?',
    questionEn: 'Which structure is a symbol of China and is legendarily said to be visible from space?',
    options: [
      { ru: 'Великая Китайская стена', en: 'Great Wall of China' },
      { ru: 'Терракотовая армия', en: 'Terracotta Army' },
      { ru: 'Запретный город', en: 'Forbidden City' },
      { ru: 'Храм Неба', en: 'Temple of Heaven' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'hist-9',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто написал «Мона Лизу»?',
    questionEn: 'Who painted the Mona Lisa?',
    options: [
      { ru: 'Микеланджело', en: 'Michelangelo' },
      { ru: 'Рафаэль', en: 'Raphael' },
      { ru: 'Леонардо да Винчи', en: 'Leonardo da Vinci' },
      { ru: 'Сандро Боттичелли', en: 'Sandro Botticelli' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-10',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой корабль затонул в 1912 году во время своего первого рейса?',
    questionEn: 'Which ship sank in 1912 during its maiden voyage?',
    options: [
      { ru: '«Лузитания»', en: 'Lusitania' },
      { ru: '«Титаник»', en: 'Titanic' },
      { ru: '«Бисмарк»', en: 'Bismarck' },
      { ru: '«Олимпик»', en: 'Olympic' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-11',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой континент был последним открытым людьми?',
    questionEn: 'Which continent was the last to be discovered by humans?',
    options: [
      { ru: 'Австралия', en: 'Australia' },
      { ru: 'Антарктида', en: 'Antarctica' },
      { ru: 'Южная Америка', en: 'South America' },
      { ru: 'Африка', en: 'Africa' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-12',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году пала Берлинская стена?',
    questionEn: 'In what year did the Berlin Wall fall?',
    options: [
      { ru: '1987', en: '1987' },
      { ru: '1989', en: '1989' },
      { ru: '1991', en: '1991' },
      { ru: '1993', en: '1993' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-13',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был лидером Советского Союза во время Второй мировой войны?',
    questionEn: 'Who was the leader of the Soviet Union during World War II?',
    options: [
      { ru: 'Владимир Ленин', en: 'Vladimir Lenin' },
      { ru: 'Иосиф Сталин', en: 'Joseph Stalin' },
      { ru: 'Никита Хрущёв', en: 'Nikita Khrushchev' },
      { ru: 'Леонид Брежнев', en: 'Leonid Brezhnev' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-14',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой изобретатель создал первую практичную электрическую лампочку?',
    questionEn: 'Which inventor created the first practical electric light bulb?',
    options: [
      { ru: 'Никола Тесла', en: 'Nikola Tesla' },
      { ru: 'Томас Эдисон', en: 'Thomas Edison' },
      { ru: 'Александр Белл', en: 'Alexander Bell' },
      { ru: 'Майкл Фарадей', en: 'Michael Faraday' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-15',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Как назывался период культурного расцвета в Европе XIV–XVI веков?',
    questionEn: 'What was the period of cultural flourishing in Europe during the 14th–16th centuries called?',
    options: [
      { ru: 'Просвещение', en: 'Enlightenment' },
      { ru: 'Возрождение (Ренессанс)', en: 'Renaissance' },
      { ru: 'Реформация', en: 'Reformation' },
      { ru: 'Романтизм', en: 'Romanticism' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-16',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'На каких островах жили самураи?',
    questionEn: 'On which islands did samurai live?',
    options: [
      { ru: 'Филиппины', en: 'Philippines' },
      { ru: 'Японские острова', en: 'Japanese islands' },
      { ru: 'Гавайские острова', en: 'Hawaiian islands' },
      { ru: 'Британские острова', en: 'British Isles' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-17',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой царь основал Санкт-Петербург?',
    questionEn: 'Which tsar founded Saint Petersburg?',
    options: [
      { ru: 'Иван Грозный', en: 'Ivan the Terrible' },
      { ru: 'Пётр I', en: 'Peter the Great' },
      { ru: 'Екатерина II', en: 'Catherine the Great' },
      { ru: 'Александр I', en: 'Alexander I' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },

  // === MEDIUM (18-34) ===
  {
    id: 'hist-18',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году началась Французская революция?',
    questionEn: 'In what year did the French Revolution begin?',
    options: [
      { ru: '1776', en: '1776' },
      { ru: '1789', en: '1789' },
      { ru: '1804', en: '1804' },
      { ru: '1815', en: '1815' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-19',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая битва считается переломным моментом Второй мировой войны на Восточном фронте?',
    questionEn: 'Which battle is considered the turning point of WWII on the Eastern Front?',
    options: [
      { ru: 'Битва за Москву', en: 'Battle of Moscow' },
      { ru: 'Сталинградская битва', en: 'Battle of Stalingrad' },
      { ru: 'Курская битва', en: 'Battle of Kursk' },
      { ru: 'Битва за Берлин', en: 'Battle of Berlin' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-20',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто был последним царём Российской империи?',
    questionEn: 'Who was the last tsar of the Russian Empire?',
    options: [
      { ru: 'Александр III', en: 'Alexander III' },
      { ru: 'Николай II', en: 'Nicholas II' },
      { ru: 'Николай I', en: 'Nicholas I' },
      { ru: 'Александр II', en: 'Alexander II' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-21',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году Константинополь был захвачен османами?',
    questionEn: 'In what year was Constantinople conquered by the Ottomans?',
    options: [
      { ru: '1389', en: '1389' },
      { ru: '1453', en: '1453' },
      { ru: '1492', en: '1492' },
      { ru: '1517', en: '1517' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-22',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая страна первой провела промышленную революцию?',
    questionEn: 'Which country was the first to undergo the Industrial Revolution?',
    options: [
      { ru: 'Франция', en: 'France' },
      { ru: 'Германия', en: 'Germany' },
      { ru: 'Великобритания', en: 'Great Britain' },
      { ru: 'США', en: 'United States' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-23',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто возглавлял поход монголов на Русь в XIII веке?',
    questionEn: 'Who led the Mongol invasion of Rus in the 13th century?',
    options: [
      { ru: 'Чингисхан', en: 'Genghis Khan' },
      { ru: 'Батый', en: 'Batu Khan' },
      { ru: 'Тамерлан', en: 'Tamerlane' },
      { ru: 'Хубилай', en: 'Kublai Khan' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-24',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какое событие послужило поводом для начала Первой мировой войны?',
    questionEn: 'What event triggered the start of World War I?',
    options: [
      { ru: 'Потопление «Лузитании»', en: 'Sinking of the Lusitania' },
      { ru: 'Убийство эрцгерцога Франца Фердинанда', en: 'Assassination of Archduke Franz Ferdinand' },
      { ru: 'Вторжение Германии в Бельгию', en: 'German invasion of Belgium' },
      { ru: 'Русская мобилизация', en: 'Russian mobilization' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-25',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой древнегреческий город-государство славился своей военной мощью?',
    questionEn: 'Which ancient Greek city-state was famous for its military power?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Коринф', en: 'Corinth' },
      { ru: 'Спарта', en: 'Sparta' },
      { ru: 'Фивы', en: 'Thebes' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-26',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году произошла Куликовская битва?',
    questionEn: 'In what year did the Battle of Kulikovo take place?',
    options: [
      { ru: '1240', en: '1240' },
      { ru: '1380', en: '1380' },
      { ru: '1480', en: '1480' },
      { ru: '1552', en: '1552' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-27',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто изобрёл книгопечатание в Европе?',
    questionEn: 'Who invented the printing press in Europe?',
    options: [
      { ru: 'Иоганн Гутенберг', en: 'Johannes Gutenberg' },
      { ru: 'Уильям Кэкстон', en: 'William Caxton' },
      { ru: 'Альд Мануций', en: 'Aldus Manutius' },
      { ru: 'Иван Фёдоров', en: 'Ivan Fyodorov' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'hist-28',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая империя контролировала большую часть Южной Америки до прихода испанцев?',
    questionEn: 'Which empire controlled most of South America before the arrival of the Spanish?',
    options: [
      { ru: 'Империя ацтеков', en: 'Aztec Empire' },
      { ru: 'Империя майя', en: 'Maya Empire' },
      { ru: 'Империя инков', en: 'Inca Empire' },
      { ru: 'Империя ольмеков', en: 'Olmec Empire' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-29',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой документ был подписан в 1215 году и ограничил власть английского короля?',
    questionEn: 'Which document was signed in 1215 and limited the power of the English king?',
    options: [
      { ru: 'Билль о правах', en: 'Bill of Rights' },
      { ru: 'Великая хартия вольностей', en: 'Magna Carta' },
      { ru: 'Хабеас корпус', en: 'Habeas Corpus' },
      { ru: 'Декларация независимости', en: 'Declaration of Independence' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-30',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой полководец перешёл через Альпы со слонами для нападения на Рим?',
    questionEn: 'Which commander crossed the Alps with elephants to attack Rome?',
    options: [
      { ru: 'Александр Македонский', en: 'Alexander the Great' },
      { ru: 'Юлий Цезарь', en: 'Julius Caesar' },
      { ru: 'Ганнибал Барка', en: 'Hannibal Barca' },
      { ru: 'Сципион Африканский', en: 'Scipio Africanus' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-31',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году Наполеон вторгся в Россию?',
    questionEn: 'In what year did Napoleon invade Russia?',
    options: [
      { ru: '1805', en: '1805' },
      { ru: '1809', en: '1809' },
      { ru: '1812', en: '1812' },
      { ru: '1815', en: '1815' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-32',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой правитель объединил Египет и стал первым фараоном?',
    questionEn: 'Which ruler united Egypt and became the first pharaoh?',
    options: [
      { ru: 'Рамзес II', en: 'Ramesses II' },
      { ru: 'Тутанхамон', en: 'Tutankhamun' },
      { ru: 'Нармер (Менес)', en: 'Narmer (Menes)' },
      { ru: 'Хеопс', en: 'Khufu' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-33',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая война шла в США с 1861 по 1865 год?',
    questionEn: 'What war was fought in the United States from 1861 to 1865?',
    options: [
      { ru: 'Война за независимость', en: 'War of Independence' },
      { ru: 'Гражданская война', en: 'Civil War' },
      { ru: 'Испано-американская война', en: 'Spanish-American War' },
      { ru: 'Мексикано-американская война', en: 'Mexican-American War' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-34',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто совершил первое кругосветное плавание?',
    questionEn: 'Who completed the first circumnavigation of the Earth?',
    options: [
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Джеймс Кук', en: 'James Cook' },
      { ru: 'Экспедиция Магеллана — Элькано', en: 'Magellan–Elcano expedition' },
      { ru: 'Фрэнсис Дрейк', en: 'Francis Drake' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },

  // === HARD (35-50) ===
  {
    id: 'hist-35',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой договор завершил Тридцатилетнюю войну?',
    questionEn: 'What treaty ended the Thirty Years\' War?',
    options: [
      { ru: 'Вестфальский мир', en: 'Peace of Westphalia' },
      { ru: 'Утрехтский мир', en: 'Treaty of Utrecht' },
      { ru: 'Парижский мир', en: 'Treaty of Paris' },
      { ru: 'Аугсбургский мир', en: 'Peace of Augsburg' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-36',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой византийский император издал Кодекс, ставший основой европейского права?',
    questionEn: 'Which Byzantine emperor issued the Code that became the foundation of European law?',
    options: [
      { ru: 'Константин I', en: 'Constantine I' },
      { ru: 'Феодосий I', en: 'Theodosius I' },
      { ru: 'Юстиниан I', en: 'Justinian I' },
      { ru: 'Василий II', en: 'Basil II' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-37',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая династия правила Китаем во время строительства основной части Великой стены?',
    questionEn: 'Which dynasty ruled China during the construction of the main part of the Great Wall?',
    options: [
      { ru: 'Династия Хань', en: 'Han Dynasty' },
      { ru: 'Династия Тан', en: 'Tang Dynasty' },
      { ru: 'Династия Мин', en: 'Ming Dynasty' },
      { ru: 'Династия Цинь', en: 'Qin Dynasty' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-38',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'В каком году была подписана Брестская мирная конвенция между Советской Россией и Центральными державами?',
    questionEn: 'In what year was the Treaty of Brest-Litovsk signed between Soviet Russia and the Central Powers?',
    options: [
      { ru: '1917', en: '1917' },
      { ru: '1918', en: '1918' },
      { ru: '1919', en: '1919' },
      { ru: '1920', en: '1920' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-39',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой город был столицей государства инков?',
    questionEn: 'What city was the capital of the Inca Empire?',
    options: [
      { ru: 'Мачу-Пикчу', en: 'Machu Picchu' },
      { ru: 'Куско', en: 'Cusco' },
      { ru: 'Теночтитлан', en: 'Tenochtitlan' },
      { ru: 'Лима', en: 'Lima' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-40',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой русский полководец командовал русской армией в Бородинской битве?',
    questionEn: 'Which Russian commander led the Russian army at the Battle of Borodino?',
    options: [
      { ru: 'Александр Суворов', en: 'Alexander Suvorov' },
      { ru: 'Михаил Кутузов', en: 'Mikhail Kutuzov' },
      { ru: 'Пётр Багратион', en: 'Pyotr Bagration' },
      { ru: 'Михаил Барклай-де-Толли', en: 'Mikhail Barclay de Tolly' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-41',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая битва 480 г. до н.э. стала знаменитым последним боем 300 спартанцев?',
    questionEn: 'Which battle of 480 BC became the famous last stand of the 300 Spartans?',
    options: [
      { ru: 'Битва при Марафоне', en: 'Battle of Marathon' },
      { ru: 'Битва при Саламине', en: 'Battle of Salamis' },
      { ru: 'Битва при Фермопилах', en: 'Battle of Thermopylae' },
      { ru: 'Битва при Платеях', en: 'Battle of Plataea' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-42',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой мирный договор завершил Русско-японскую войну 1904–1905 годов?',
    questionEn: 'Which peace treaty ended the Russo-Japanese War of 1904–1905?',
    options: [
      { ru: 'Портсмутский мир', en: 'Treaty of Portsmouth' },
      { ru: 'Симоносекский договор', en: 'Treaty of Shimonoseki' },
      { ru: 'Сан-Стефанский мир', en: 'Treaty of San Stefano' },
      { ru: 'Тильзитский мир', en: 'Treaty of Tilsit' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-43',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой учёный расшифровал египетские иероглифы с помощью Розеттского камня?',
    questionEn: 'Which scholar deciphered Egyptian hieroglyphs using the Rosetta Stone?',
    options: [
      { ru: 'Говард Картер', en: 'Howard Carter' },
      { ru: 'Жан-Франсуа Шампольон', en: 'Jean-François Champollion' },
      { ru: 'Генрих Шлиман', en: 'Heinrich Schliemann' },
      { ru: 'Томас Юнг', en: 'Thomas Young' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-44',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая битва 1709 года стала решающей в Северной войне?',
    questionEn: 'Which battle of 1709 was decisive in the Great Northern War?',
    options: [
      { ru: 'Битва при Нарве', en: 'Battle of Narva' },
      { ru: 'Полтавская битва', en: 'Battle of Poltava' },
      { ru: 'Гангутское сражение', en: 'Battle of Gangut' },
      { ru: 'Битва при Лесной', en: 'Battle of Lesnaya' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-45',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Как называлась политика Отто фон Бисмарка по объединению Германии?',
    questionEn: 'What was Otto von Bismarck\'s policy for unifying Germany called?',
    options: [
      { ru: '«Железом и кровью»', en: 'Blood and Iron' },
      { ru: '«Реальная политика»', en: 'Realpolitik' },
      { ru: '«Культуркампф»', en: 'Kulturkampf' },
      { ru: '«Мировая политика»', en: 'Weltpolitik' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-46',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой город был столицей Золотой Орды?',
    questionEn: 'What city was the capital of the Golden Horde?',
    options: [
      { ru: 'Каракорум', en: 'Karakorum' },
      { ru: 'Сарай-Бату', en: 'Sarai Batu' },
      { ru: 'Самарканд', en: 'Samarkand' },
      { ru: 'Булгар', en: 'Bolgar' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-47',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая цивилизация создала клинописное письмо?',
    questionEn: 'Which civilization created cuneiform writing?',
    options: [
      { ru: 'Египтяне', en: 'Egyptians' },
      { ru: 'Шумеры', en: 'Sumerians' },
      { ru: 'Финикийцы', en: 'Phoenicians' },
      { ru: 'Хетты', en: 'Hittites' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-48',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой конгресс определил новый порядок в Европе после наполеоновских войн?',
    questionEn: 'Which congress established the new order in Europe after the Napoleonic Wars?',
    options: [
      { ru: 'Берлинский конгресс', en: 'Congress of Berlin' },
      { ru: 'Венский конгресс', en: 'Congress of Vienna' },
      { ru: 'Парижский конгресс', en: 'Congress of Paris' },
      { ru: 'Аахенский конгресс', en: 'Congress of Aix-la-Chapelle' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-49',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой английский король был казнён во время Английской гражданской войны?',
    questionEn: 'Which English king was executed during the English Civil War?',
    options: [
      { ru: 'Яков I', en: 'James I' },
      { ru: 'Карл I', en: 'Charles I' },
      { ru: 'Карл II', en: 'Charles II' },
      { ru: 'Генрих VIII', en: 'Henry VIII' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-50',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой древний торговый путь связывал Китай с Римской империей?',
    questionEn: 'Which ancient trade route connected China with the Roman Empire?',
    options: [
      { ru: 'Янтарный путь', en: 'Amber Road' },
      { ru: 'Путь благовоний', en: 'Incense Route' },
      { ru: 'Великий шёлковый путь', en: 'Silk Road' },
      { ru: 'Путь специй', en: 'Spice Route' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },

  // ============================================================
  // === BATCH 2 — EASY (51-67) ===
  // ============================================================
  {
    id: 'hist-51',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой город был столицей Римской империи?',
    questionEn: 'What city was the capital of the Roman Empire?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Рим', en: 'Rome' },
      { ru: 'Карфаген', en: 'Carthage' },
      { ru: 'Константинополь', en: 'Constantinople' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-52',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто открыл Америку в 1492 году?',
    questionEn: 'Who discovered America in 1492?',
    options: [
      { ru: 'Фернан Магеллан', en: 'Ferdinand Magellan' },
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Васко да Гама', en: 'Vasco da Gama' },
      { ru: 'Америго Веспуччи', en: 'Amerigo Vespucci' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-53',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году началась Первая мировая война?',
    questionEn: 'In what year did World War I begin?',
    options: [
      { ru: '1912', en: '1912' },
      { ru: '1914', en: '1914' },
      { ru: '1916', en: '1916' },
      { ru: '1918', en: '1918' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-54',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой фараон построил Великую пирамиду в Гизе?',
    questionEn: 'Which pharaoh built the Great Pyramid of Giza?',
    options: [
      { ru: 'Тутанхамон', en: 'Tutankhamun' },
      { ru: 'Рамзес II', en: 'Ramesses II' },
      { ru: 'Хеопс', en: 'Khufu' },
      { ru: 'Клеопатра', en: 'Cleopatra' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-55',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какая страна подарила Статую Свободы Америке?',
    questionEn: 'Which country gifted the Statue of Liberty to America?',
    options: [
      { ru: 'Великобритания', en: 'Great Britain' },
      { ru: 'Франция', en: 'France' },
      { ru: 'Испания', en: 'Spain' },
      { ru: 'Италия', en: 'Italy' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-56',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был первым человеком в космосе?',
    questionEn: 'Who was the first human in space?',
    options: [
      { ru: 'Нил Армстронг', en: 'Neil Armstrong' },
      { ru: 'Юрий Гагарин', en: 'Yuri Gagarin' },
      { ru: 'Алан Шепард', en: 'Alan Shepard' },
      { ru: 'Валентина Терешкова', en: 'Valentina Tereshkova' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-57',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году пала Берлинская стена?',
    questionEn: 'In what year did the Berlin Wall fall?',
    options: [
      { ru: '1987', en: '1987' },
      { ru: '1989', en: '1989' },
      { ru: '1991', en: '1991' },
      { ru: '1993', en: '1993' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-58',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какое событие произошло в России в 1917 году?',
    questionEn: 'What major event occurred in Russia in 1917?',
    options: [
      { ru: 'Крымская война', en: 'Crimean War' },
      { ru: 'Революция', en: 'Revolution' },
      { ru: 'Отмена крепостного права', en: 'Abolition of serfdom' },
      { ru: 'Основание Петербурга', en: 'Founding of St. Petersburg' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-59',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой океан пересёк Колумб, направляясь в Новый Свет?',
    questionEn: 'Which ocean did Columbus cross to reach the New World?',
    options: [
      { ru: 'Тихий', en: 'Pacific' },
      { ru: 'Индийский', en: 'Indian' },
      { ru: 'Атлантический', en: 'Atlantic' },
      { ru: 'Северный Ледовитый', en: 'Arctic' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-60',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Как назывался корабль, на котором пилигримы прибыли в Америку?',
    questionEn: 'What was the name of the ship that brought the Pilgrims to America?',
    options: [
      { ru: 'Санта-Мария', en: 'Santa Maria' },
      { ru: 'Мэйфлауэр', en: 'Mayflower' },
      { ru: 'Титаник', en: 'Titanic' },
      { ru: 'Виктория', en: 'Victoria' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-61',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой древний город был уничтожен извержением Везувия?',
    questionEn: 'Which ancient city was destroyed by the eruption of Vesuvius?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Помпеи', en: 'Pompeii' },
      { ru: 'Спарта', en: 'Sparta' },
      { ru: 'Троя', en: 'Troy' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-62',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто написал «Мона Лизу»?',
    questionEn: 'Who painted the "Mona Lisa"?',
    options: [
      { ru: 'Микеланджело', en: 'Michelangelo' },
      { ru: 'Рафаэль', en: 'Raphael' },
      { ru: 'Леонардо да Винчи', en: 'Leonardo da Vinci' },
      { ru: 'Сандро Боттичелли', en: 'Sandro Botticelli' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-63',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какая война шла в США в 1861–1865 годах?',
    questionEn: 'What war was fought in the US from 1861 to 1865?',
    options: [
      { ru: 'Война за независимость', en: 'War of Independence' },
      { ru: 'Гражданская война', en: 'Civil War' },
      { ru: 'Первая мировая', en: 'World War I' },
      { ru: 'Испано-американская', en: 'Spanish-American War' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-64',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был лидером СССР во время Второй мировой войны?',
    questionEn: 'Who was the leader of the USSR during World War II?',
    options: [
      { ru: 'Ленин', en: 'Lenin' },
      { ru: 'Сталин', en: 'Stalin' },
      { ru: 'Хрущёв', en: 'Khrushchev' },
      { ru: 'Брежнев', en: 'Brezhnev' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-65',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой материк был открыт последним?',
    questionEn: 'Which continent was discovered last?',
    options: [
      { ru: 'Австралия', en: 'Australia' },
      { ru: 'Антарктида', en: 'Antarctica' },
      { ru: 'Южная Америка', en: 'South America' },
      { ru: 'Африка', en: 'Africa' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-66',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году человек впервые ступил на Луну?',
    questionEn: 'In what year did a human first walk on the Moon?',
    options: [
      { ru: '1965', en: '1965' },
      { ru: '1969', en: '1969' },
      { ru: '1971', en: '1971' },
      { ru: '1975', en: '1975' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-67',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой титул носил правитель Древнего Египта?',
    questionEn: 'What title did the ruler of Ancient Egypt hold?',
    options: [
      { ru: 'Император', en: 'Emperor' },
      { ru: 'Царь', en: 'King' },
      { ru: 'Фараон', en: 'Pharaoh' },
      { ru: 'Султан', en: 'Sultan' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },

  // ============================================================
  // === BATCH 2 — MEDIUM (68-84) ===
  // ============================================================
  {
    id: 'hist-68',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какое сражение считается переломным моментом Второй мировой войны на Восточном фронте?',
    questionEn: 'Which battle is considered the turning point of WWII on the Eastern Front?',
    options: [
      { ru: 'Битва за Москву', en: 'Battle of Moscow' },
      { ru: 'Сталинградская битва', en: 'Battle of Stalingrad' },
      { ru: 'Курская битва', en: 'Battle of Kursk' },
      { ru: 'Блокада Ленинграда', en: 'Siege of Leningrad' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-69',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто был первым императором Франции?',
    questionEn: 'Who was the first Emperor of France?',
    options: [
      { ru: 'Людовик XIV', en: 'Louis XIV' },
      { ru: 'Наполеон Бонапарт', en: 'Napoleon Bonaparte' },
      { ru: 'Карл Великий', en: 'Charlemagne' },
      { ru: 'Людовик XVI', en: 'Louis XVI' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-70',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году был основан Санкт-Петербург?',
    questionEn: 'In what year was Saint Petersburg founded?',
    options: [
      { ru: '1700', en: '1700' },
      { ru: '1703', en: '1703' },
      { ru: '1712', en: '1712' },
      { ru: '1725', en: '1725' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-71',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая цивилизация изобрела письменность клинописью?',
    questionEn: 'Which civilization invented cuneiform writing?',
    options: [
      { ru: 'Египетская', en: 'Egyptian' },
      { ru: 'Шумерская', en: 'Sumerian' },
      { ru: 'Китайская', en: 'Chinese' },
      { ru: 'Греческая', en: 'Greek' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-72',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой договор завершил Первую мировую войну?',
    questionEn: 'Which treaty ended World War I?',
    options: [
      { ru: 'Вестфальский мир', en: 'Peace of Westphalia' },
      { ru: 'Версальский договор', en: 'Treaty of Versailles' },
      { ru: 'Парижский мир', en: 'Treaty of Paris' },
      { ru: 'Брест-Литовский мир', en: 'Treaty of Brest-Litovsk' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-73',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто объединил Германию в 1871 году?',
    questionEn: 'Who unified Germany in 1871?',
    options: [
      { ru: 'Фридрих Великий', en: 'Frederick the Great' },
      { ru: 'Отто фон Бисмарк', en: 'Otto von Bismarck' },
      { ru: 'Вильгельм I', en: 'Wilhelm I' },
      { ru: 'Карл Маркс', en: 'Karl Marx' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-74',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая империя правила большей частью Южной Америки до XIX века?',
    questionEn: 'Which empire ruled most of South America until the 19th century?',
    options: [
      { ru: 'Британская', en: 'British' },
      { ru: 'Португальская', en: 'Portuguese' },
      { ru: 'Испанская', en: 'Spanish' },
      { ru: 'Французская', en: 'French' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-75',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какое государство называли «Империя, над которой не заходит солнце»?',
    questionEn: 'Which state was called "The empire on which the sun never sets"?',
    options: [
      { ru: 'Римская империя', en: 'Roman Empire' },
      { ru: 'Испанская империя', en: 'Spanish Empire' },
      { ru: 'Британская империя', en: 'British Empire' },
      { ru: 'Монгольская империя', en: 'Mongol Empire' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-76',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году произошла Великая французская революция?',
    questionEn: 'In what year did the French Revolution begin?',
    options: [
      { ru: '1776', en: '1776' },
      { ru: '1789', en: '1789' },
      { ru: '1799', en: '1799' },
      { ru: '1804', en: '1804' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-77',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой полководец перешёл через Альпы с боевыми слонами?',
    questionEn: 'Which general crossed the Alps with war elephants?',
    options: [
      { ru: 'Юлий Цезарь', en: 'Julius Caesar' },
      { ru: 'Александр Македонский', en: 'Alexander the Great' },
      { ru: 'Ганнибал Барка', en: 'Hannibal Barca' },
      { ru: 'Спартак', en: 'Spartacus' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-78',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой город был столицей Византийской империи?',
    questionEn: 'What city was the capital of the Byzantine Empire?',
    options: [
      { ru: 'Рим', en: 'Rome' },
      { ru: 'Александрия', en: 'Alexandria' },
      { ru: 'Константинополь', en: 'Constantinople' },
      { ru: 'Антиохия', en: 'Antioch' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-79',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто написал «Капитал» — основной труд по политической экономии?',
    questionEn: 'Who wrote "Das Kapital"?',
    options: [
      { ru: 'Фридрих Энгельс', en: 'Friedrich Engels' },
      { ru: 'Адам Смит', en: 'Adam Smith' },
      { ru: 'Карл Маркс', en: 'Karl Marx' },
      { ru: 'Владимир Ленин', en: 'Vladimir Lenin' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-80',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая страна первой провела промышленную революцию?',
    questionEn: 'Which country was the first to undergo the Industrial Revolution?',
    options: [
      { ru: 'Франция', en: 'France' },
      { ru: 'Германия', en: 'Germany' },
      { ru: 'США', en: 'USA' },
      { ru: 'Великобритания', en: 'Great Britain' },
    ],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'hist-81',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Как называлась организация, предшественница ООН?',
    questionEn: 'What was the predecessor organization of the United Nations?',
    options: [
      { ru: 'НАТО', en: 'NATO' },
      { ru: 'Лига Наций', en: 'League of Nations' },
      { ru: 'Коминтерн', en: 'Comintern' },
      { ru: 'Священный союз', en: 'Holy Alliance' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-82',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году было отменено крепостное право в России?',
    questionEn: 'In what year was serfdom abolished in Russia?',
    options: [
      { ru: '1825', en: '1825' },
      { ru: '1861', en: '1861' },
      { ru: '1881', en: '1881' },
      { ru: '1905', en: '1905' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-83',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой мореплаватель первым совершил кругосветное путешествие?',
    questionEn: 'Which explorer led the first circumnavigation of the globe?',
    options: [
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Фернан Магеллан', en: 'Ferdinand Magellan' },
      { ru: 'Васко да Гама', en: 'Vasco da Gama' },
      { ru: 'Джеймс Кук', en: 'James Cook' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-84',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой город был столицей империи инков?',
    questionEn: 'What city was the capital of the Inca Empire?',
    options: [
      { ru: 'Мачу-Пикчу', en: 'Machu Picchu' },
      { ru: 'Куско', en: 'Cusco' },
      { ru: 'Теночтитлан', en: 'Tenochtitlan' },
      { ru: 'Лима', en: 'Lima' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },

  // ============================================================
  // === BATCH 2 — HARD (85-100) ===
  // ============================================================
  {
    id: 'hist-85',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой мирный договор завершил Тридцатилетнюю войну?',
    questionEn: 'Which peace treaty ended the Thirty Years\' War?',
    options: [
      { ru: 'Утрехтский мир', en: 'Treaty of Utrecht' },
      { ru: 'Вестфальский мир', en: 'Peace of Westphalia' },
      { ru: 'Аугсбургский мир', en: 'Peace of Augsburg' },
      { ru: 'Нимвегенский мир', en: 'Treaty of Nijmegen' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-86',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'В каком году пал Константинополь под натиском Османской империи?',
    questionEn: 'In what year did Constantinople fall to the Ottoman Empire?',
    options: [
      { ru: '1389', en: '1389' },
      { ru: '1453', en: '1453' },
      { ru: '1492', en: '1492' },
      { ru: '1517', en: '1517' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-87',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой император издал Миланский эдикт о веротерпимости в 313 году?',
    questionEn: 'Which emperor issued the Edict of Milan on religious tolerance in 313 AD?',
    options: [
      { ru: 'Нерон', en: 'Nero' },
      { ru: 'Константин Великий', en: 'Constantine the Great' },
      { ru: 'Август', en: 'Augustus' },
      { ru: 'Юстиниан', en: 'Justinian' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-88',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая битва 1805 года считается величайшей морской победой Нельсона?',
    questionEn: 'Which 1805 battle is considered Nelson\'s greatest naval victory?',
    options: [
      { ru: 'Битва при Ниле', en: 'Battle of the Nile' },
      { ru: 'Трафальгарское сражение', en: 'Battle of Trafalgar' },
      { ru: 'Ютландское сражение', en: 'Battle of Jutland' },
      { ru: 'Битва при Лепанто', en: 'Battle of Lepanto' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-89',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой древнегреческий историк считается «отцом истории»?',
    questionEn: 'Which ancient Greek historian is called the "Father of History"?',
    options: [
      { ru: 'Фукидид', en: 'Thucydides' },
      { ru: 'Геродот', en: 'Herodotus' },
      { ru: 'Плутарх', en: 'Plutarch' },
      { ru: 'Ксенофонт', en: 'Xenophon' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-90',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая династия правила Россией с 1613 по 1917 год?',
    questionEn: 'Which dynasty ruled Russia from 1613 to 1917?',
    options: [
      { ru: 'Рюриковичи', en: 'Rurikids' },
      { ru: 'Романовы', en: 'Romanovs' },
      { ru: 'Годуновы', en: 'Godunovs' },
      { ru: 'Шуйские', en: 'Shuiskys' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-91',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой кодекс законов был создан в Вавилоне около 1750 года до н.э.?',
    questionEn: 'Which code of laws was created in Babylon around 1750 BC?',
    options: [
      { ru: 'Законы XII таблиц', en: 'Twelve Tables' },
      { ru: 'Кодекс Хаммурапи', en: 'Code of Hammurabi' },
      { ru: 'Кодекс Юстиниана', en: 'Code of Justinian' },
      { ru: 'Законы Ману', en: 'Laws of Manu' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-92',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какое государство существовало на территории Мексики до прихода испанцев?',
    questionEn: 'Which empire existed in Mexico before the Spanish arrival?',
    options: [
      { ru: 'Империя инков', en: 'Inca Empire' },
      { ru: 'Империя ацтеков', en: 'Aztec Empire' },
      { ru: 'Империя майя', en: 'Maya Empire' },
      { ru: 'Тольтекская империя', en: 'Toltec Empire' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-93',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой конгресс перекроил карту Европы после наполеоновских войн?',
    questionEn: 'Which congress redrew the map of Europe after the Napoleonic Wars?',
    options: [
      { ru: 'Парижский конгресс', en: 'Congress of Paris' },
      { ru: 'Берлинский конгресс', en: 'Congress of Berlin' },
      { ru: 'Венский конгресс', en: 'Congress of Vienna' },
      { ru: 'Аахенский конгресс', en: 'Congress of Aix-la-Chapelle' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-94',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Кто возглавил движение за независимость Индии ненасильственным путём?',
    questionEn: 'Who led the Indian independence movement through nonviolent resistance?',
    options: [
      { ru: 'Джавахарлал Неру', en: 'Jawaharlal Nehru' },
      { ru: 'Махатма Ганди', en: 'Mahatma Gandhi' },
      { ru: 'Субхас Чандра Бос', en: 'Subhas Chandra Bose' },
      { ru: 'Бхагат Сингх', en: 'Bhagat Singh' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-95',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'В каком году произошла Битва при Гастингсе?',
    questionEn: 'In what year did the Battle of Hastings take place?',
    options: [
      { ru: '1016', en: '1016' },
      { ru: '1066', en: '1066' },
      { ru: '1086', en: '1086' },
      { ru: '1100', en: '1100' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-96',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая война между Афинами и Спартой длилась почти 30 лет?',
    questionEn: 'Which war between Athens and Sparta lasted almost 30 years?',
    options: [
      { ru: 'Греко-персидские войны', en: 'Greco-Persian Wars' },
      { ru: 'Пелопоннесская война', en: 'Peloponnesian War' },
      { ru: 'Коринфская война', en: 'Corinthian War' },
      { ru: 'Ламийская война', en: 'Lamian War' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-97',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой философ был учителем Александра Македонского?',
    questionEn: 'Which philosopher was the tutor of Alexander the Great?',
    options: [
      { ru: 'Сократ', en: 'Socrates' },
      { ru: 'Платон', en: 'Plato' },
      { ru: 'Аристотель', en: 'Aristotle' },
      { ru: 'Диоген', en: 'Diogenes' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-98',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какое событие считается началом эпохи Возрождения?',
    questionEn: 'What event is considered the start of the Renaissance?',
    options: [
      { ru: 'Изобретение книгопечатания', en: 'Invention of printing' },
      { ru: 'Падение Константинополя', en: 'Fall of Constantinople' },
      { ru: 'Открытие Америки', en: 'Discovery of America' },
      { ru: 'Расцвет Флоренции в XIV веке', en: 'Flourishing of Florence in the 14th century' },
    ],
    correctIndex: 3,
    timeLimit: 25,
  },
  {
    id: 'hist-99',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой план восстановления Европы после Второй мировой войны был предложен США?',
    questionEn: 'What US plan helped rebuild Europe after World War II?',
    options: [
      { ru: 'Доктрина Трумэна', en: 'Truman Doctrine' },
      { ru: 'План Маршалла', en: 'Marshall Plan' },
      { ru: 'Ленд-лиз', en: 'Lend-Lease' },
      { ru: 'План Моргентау', en: 'Morgenthau Plan' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-100',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой император разделил Римскую империю на Западную и Восточную?',
    questionEn: 'Which emperor divided the Roman Empire into Western and Eastern parts?',
    options: [
      { ru: 'Константин', en: 'Constantine' },
      { ru: 'Диоклетиан', en: 'Diocletian' },
      { ru: 'Феодосий', en: 'Theodosius' },
      { ru: 'Юлиан', en: 'Julian' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
];
