import { QuizQuestion } from '@/types/game';

export const HISTORY_QUESTIONS: QuizQuestion[] = [
  // === EASY (1-17) ===
  {
    id: 'hist-1',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был первым президентом США?',
    questionEn: 'Who was the first president of the United States?',
    options: [
      { ru: 'Джордж Вашингтон', en: 'George Washington' },
      { ru: 'Томас Джефферсон', en: 'Thomas Jefferson' },
      { ru: 'Бенджамин Франклин', en: 'Benjamin Franklin' },
      { ru: 'Джон Адамс', en: 'John Adams' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'hist-2',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году закончилась Вторая мировая война?',
    questionEn: 'In what year did World War II end?',
    options: [
      { ru: '1943', en: '1943' },
      { ru: '1944', en: '1944' },
      { ru: '1945', en: '1945' },
      { ru: '1946', en: '1946' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-3',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какая древняя цивилизация построила пирамиды в Гизе?',
    questionEn: 'Which ancient civilization built the pyramids of Giza?',
    options: [
      { ru: 'Римляне', en: 'Romans' },
      { ru: 'Греки', en: 'Greeks' },
      { ru: 'Египтяне', en: 'Egyptians' },
      { ru: 'Персы', en: 'Persians' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-4',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто открыл Америку в 1492 году?',
    questionEn: 'Who discovered America in 1492?',
    options: [
      { ru: 'Фернан Магеллан', en: 'Ferdinand Magellan' },
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Васко да Гама', en: 'Vasco da Gama' },
      { ru: 'Америго Веспуччи', en: 'Amerigo Vespucci' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-5',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой город был столицей Римской империи?',
    questionEn: 'What city was the capital of the Roman Empire?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Рим', en: 'Rome' },
      { ru: 'Карфаген', en: 'Carthage' },
      { ru: 'Александрия', en: 'Alexandria' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-6',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был первым человеком, полетевшим в космос?',
    questionEn: 'Who was the first person to fly into space?',
    options: [
      { ru: 'Нил Армстронг', en: 'Neil Armstrong' },
      { ru: 'Юрий Гагарин', en: 'Yuri Gagarin' },
      { ru: 'Алан Шепард', en: 'Alan Shepard' },
      { ru: 'Валентина Терешкова', en: 'Valentina Tereshkova' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-7',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В какой стране произошла Октябрьская революция 1917 года?',
    questionEn: 'In which country did the October Revolution of 1917 take place?',
    options: [
      { ru: 'Германия', en: 'Germany' },
      { ru: 'Франция', en: 'France' },
      { ru: 'Россия', en: 'Russia' },
      { ru: 'Китай', en: 'China' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-8',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какое сооружение является символом Китая и видно из космоса по легенде?',
    questionEn: 'Which structure is a symbol of China and is legendarily said to be visible from space?',
    options: [
      { ru: 'Великая Китайская стена', en: 'Great Wall of China' },
      { ru: 'Терракотовая армия', en: 'Terracotta Army' },
      { ru: 'Запретный город', en: 'Forbidden City' },
      { ru: 'Храм Неба', en: 'Temple of Heaven' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'hist-9',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто написал «Мона Лизу»?',
    questionEn: 'Who painted the Mona Lisa?',
    options: [
      { ru: 'Микеланджело', en: 'Michelangelo' },
      { ru: 'Рафаэль', en: 'Raphael' },
      { ru: 'Леонардо да Винчи', en: 'Leonardo da Vinci' },
      { ru: 'Сандро Боттичелли', en: 'Sandro Botticelli' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'hist-10',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой корабль затонул в 1912 году во время своего первого рейса?',
    questionEn: 'Which ship sank in 1912 during its maiden voyage?',
    options: [
      { ru: '«Лузитания»', en: 'Lusitania' },
      { ru: '«Титаник»', en: 'Titanic' },
      { ru: '«Бисмарк»', en: 'Bismarck' },
      { ru: '«Олимпик»', en: 'Olympic' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-11',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой континент был последним открытым людьми?',
    questionEn: 'Which continent was the last to be discovered by humans?',
    options: [
      { ru: 'Австралия', en: 'Australia' },
      { ru: 'Антарктида', en: 'Antarctica' },
      { ru: 'Южная Америка', en: 'South America' },
      { ru: 'Африка', en: 'Africa' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-12',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'В каком году пала Берлинская стена?',
    questionEn: 'In what year did the Berlin Wall fall?',
    options: [
      { ru: '1987', en: '1987' },
      { ru: '1989', en: '1989' },
      { ru: '1991', en: '1991' },
      { ru: '1993', en: '1993' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-13',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Кто был лидером Советского Союза во время Второй мировой войны?',
    questionEn: 'Who was the leader of the Soviet Union during World War II?',
    options: [
      { ru: 'Владимир Ленин', en: 'Vladimir Lenin' },
      { ru: 'Иосиф Сталин', en: 'Joseph Stalin' },
      { ru: 'Никита Хрущёв', en: 'Nikita Khrushchev' },
      { ru: 'Леонид Брежнев', en: 'Leonid Brezhnev' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-14',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой изобретатель создал первую практичную электрическую лампочку?',
    questionEn: 'Which inventor created the first practical electric light bulb?',
    options: [
      { ru: 'Никола Тесла', en: 'Nikola Tesla' },
      { ru: 'Томас Эдисон', en: 'Thomas Edison' },
      { ru: 'Александр Белл', en: 'Alexander Bell' },
      { ru: 'Майкл Фарадей', en: 'Michael Faraday' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-15',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Как назывался период культурного расцвета в Европе XIV–XVI веков?',
    questionEn: 'What was the period of cultural flourishing in Europe during the 14th–16th centuries called?',
    options: [
      { ru: 'Просвещение', en: 'Enlightenment' },
      { ru: 'Возрождение (Ренессанс)', en: 'Renaissance' },
      { ru: 'Реформация', en: 'Reformation' },
      { ru: 'Романтизм', en: 'Romanticism' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-16',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'На каких островах жили самураи?',
    questionEn: 'On which islands did samurai live?',
    options: [
      { ru: 'Филиппины', en: 'Philippines' },
      { ru: 'Японские острова', en: 'Japanese islands' },
      { ru: 'Гавайские острова', en: 'Hawaiian islands' },
      { ru: 'Британские острова', en: 'British Isles' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'hist-17',
    topic: 'history',
    difficulty: 'easy',
    questionRu: 'Какой царь основал Санкт-Петербург?',
    questionEn: 'Which tsar founded Saint Petersburg?',
    options: [
      { ru: 'Иван Грозный', en: 'Ivan the Terrible' },
      { ru: 'Пётр I', en: 'Peter the Great' },
      { ru: 'Екатерина II', en: 'Catherine the Great' },
      { ru: 'Александр I', en: 'Alexander I' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },

  // === MEDIUM (18-34) ===
  {
    id: 'hist-18',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году началась Французская революция?',
    questionEn: 'In what year did the French Revolution begin?',
    options: [
      { ru: '1776', en: '1776' },
      { ru: '1789', en: '1789' },
      { ru: '1804', en: '1804' },
      { ru: '1815', en: '1815' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-19',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая битва считается переломным моментом Второй мировой войны на Восточном фронте?',
    questionEn: 'Which battle is considered the turning point of WWII on the Eastern Front?',
    options: [
      { ru: 'Битва за Москву', en: 'Battle of Moscow' },
      { ru: 'Сталинградская битва', en: 'Battle of Stalingrad' },
      { ru: 'Курская битва', en: 'Battle of Kursk' },
      { ru: 'Битва за Берлин', en: 'Battle of Berlin' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-20',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто был последним царём Российской империи?',
    questionEn: 'Who was the last tsar of the Russian Empire?',
    options: [
      { ru: 'Александр III', en: 'Alexander III' },
      { ru: 'Николай II', en: 'Nicholas II' },
      { ru: 'Николай I', en: 'Nicholas I' },
      { ru: 'Александр II', en: 'Alexander II' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-21',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году Константинополь был захвачен османами?',
    questionEn: 'In what year was Constantinople conquered by the Ottomans?',
    options: [
      { ru: '1389', en: '1389' },
      { ru: '1453', en: '1453' },
      { ru: '1492', en: '1492' },
      { ru: '1517', en: '1517' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-22',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая страна первой провела промышленную революцию?',
    questionEn: 'Which country was the first to undergo the Industrial Revolution?',
    options: [
      { ru: 'Франция', en: 'France' },
      { ru: 'Германия', en: 'Germany' },
      { ru: 'Великобритания', en: 'Great Britain' },
      { ru: 'США', en: 'United States' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-23',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто возглавлял поход монголов на Русь в XIII веке?',
    questionEn: 'Who led the Mongol invasion of Rus in the 13th century?',
    options: [
      { ru: 'Чингисхан', en: 'Genghis Khan' },
      { ru: 'Батый', en: 'Batu Khan' },
      { ru: 'Тамерлан', en: 'Tamerlane' },
      { ru: 'Хубилай', en: 'Kublai Khan' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-24',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какое событие послужило поводом для начала Первой мировой войны?',
    questionEn: 'What event triggered the start of World War I?',
    options: [
      { ru: 'Потопление «Лузитании»', en: 'Sinking of the Lusitania' },
      { ru: 'Убийство эрцгерцога Франца Фердинанда', en: 'Assassination of Archduke Franz Ferdinand' },
      { ru: 'Вторжение Германии в Бельгию', en: 'German invasion of Belgium' },
      { ru: 'Русская мобилизация', en: 'Russian mobilization' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-25',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой древнегреческий город-государство славился своей военной мощью?',
    questionEn: 'Which ancient Greek city-state was famous for its military power?',
    options: [
      { ru: 'Афины', en: 'Athens' },
      { ru: 'Коринф', en: 'Corinth' },
      { ru: 'Спарта', en: 'Sparta' },
      { ru: 'Фивы', en: 'Thebes' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-26',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году произошла Куликовская битва?',
    questionEn: 'In what year did the Battle of Kulikovo take place?',
    options: [
      { ru: '1240', en: '1240' },
      { ru: '1380', en: '1380' },
      { ru: '1480', en: '1480' },
      { ru: '1552', en: '1552' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-27',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто изобрёл книгопечатание в Европе?',
    questionEn: 'Who invented the printing press in Europe?',
    options: [
      { ru: 'Иоганн Гутенберг', en: 'Johannes Gutenberg' },
      { ru: 'Уильям Кэкстон', en: 'William Caxton' },
      { ru: 'Альд Мануций', en: 'Aldus Manutius' },
      { ru: 'Иван Фёдоров', en: 'Ivan Fyodorov' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'hist-28',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая империя контролировала большую часть Южной Америки до прихода испанцев?',
    questionEn: 'Which empire controlled most of South America before the arrival of the Spanish?',
    options: [
      { ru: 'Империя ацтеков', en: 'Aztec Empire' },
      { ru: 'Империя майя', en: 'Maya Empire' },
      { ru: 'Империя инков', en: 'Inca Empire' },
      { ru: 'Империя ольмеков', en: 'Olmec Empire' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-29',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой документ был подписан в 1215 году и ограничил власть английского короля?',
    questionEn: 'Which document was signed in 1215 and limited the power of the English king?',
    options: [
      { ru: 'Билль о правах', en: 'Bill of Rights' },
      { ru: 'Великая хартия вольностей', en: 'Magna Carta' },
      { ru: 'Хабеас корпус', en: 'Habeas Corpus' },
      { ru: 'Декларация независимости', en: 'Declaration of Independence' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-30',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой полководец перешёл через Альпы со слонами для нападения на Рим?',
    questionEn: 'Which commander crossed the Alps with elephants to attack Rome?',
    options: [
      { ru: 'Александр Македонский', en: 'Alexander the Great' },
      { ru: 'Юлий Цезарь', en: 'Julius Caesar' },
      { ru: 'Ганнибал Барка', en: 'Hannibal Barca' },
      { ru: 'Сципион Африканский', en: 'Scipio Africanus' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-31',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'В каком году Наполеон вторгся в Россию?',
    questionEn: 'In what year did Napoleon invade Russia?',
    options: [
      { ru: '1805', en: '1805' },
      { ru: '1809', en: '1809' },
      { ru: '1812', en: '1812' },
      { ru: '1815', en: '1815' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-32',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какой правитель объединил Египет и стал первым фараоном?',
    questionEn: 'Which ruler united Egypt and became the first pharaoh?',
    options: [
      { ru: 'Рамзес II', en: 'Ramesses II' },
      { ru: 'Тутанхамон', en: 'Tutankhamun' },
      { ru: 'Нармер (Менес)', en: 'Narmer (Menes)' },
      { ru: 'Хеопс', en: 'Khufu' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'hist-33',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Какая война шла в США с 1861 по 1865 год?',
    questionEn: 'What war was fought in the United States from 1861 to 1865?',
    options: [
      { ru: 'Война за независимость', en: 'War of Independence' },
      { ru: 'Гражданская война', en: 'Civil War' },
      { ru: 'Испано-американская война', en: 'Spanish-American War' },
      { ru: 'Мексикано-американская война', en: 'Mexican-American War' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'hist-34',
    topic: 'history',
    difficulty: 'medium',
    questionRu: 'Кто совершил первое кругосветное плавание?',
    questionEn: 'Who completed the first circumnavigation of the Earth?',
    options: [
      { ru: 'Христофор Колумб', en: 'Christopher Columbus' },
      { ru: 'Джеймс Кук', en: 'James Cook' },
      { ru: 'Экспедиция Магеллана — Элькано', en: 'Magellan–Elcano expedition' },
      { ru: 'Фрэнсис Дрейк', en: 'Francis Drake' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },

  // === HARD (35-50) ===
  {
    id: 'hist-35',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой договор завершил Тридцатилетнюю войну?',
    questionEn: 'What treaty ended the Thirty Years\' War?',
    options: [
      { ru: 'Вестфальский мир', en: 'Peace of Westphalia' },
      { ru: 'Утрехтский мир', en: 'Treaty of Utrecht' },
      { ru: 'Парижский мир', en: 'Treaty of Paris' },
      { ru: 'Аугсбургский мир', en: 'Peace of Augsburg' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-36',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой византийский император издал Кодекс, ставший основой европейского права?',
    questionEn: 'Which Byzantine emperor issued the Code that became the foundation of European law?',
    options: [
      { ru: 'Константин I', en: 'Constantine I' },
      { ru: 'Феодосий I', en: 'Theodosius I' },
      { ru: 'Юстиниан I', en: 'Justinian I' },
      { ru: 'Василий II', en: 'Basil II' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-37',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая династия правила Китаем во время строительства основной части Великой стены?',
    questionEn: 'Which dynasty ruled China during the construction of the main part of the Great Wall?',
    options: [
      { ru: 'Династия Хань', en: 'Han Dynasty' },
      { ru: 'Династия Тан', en: 'Tang Dynasty' },
      { ru: 'Династия Мин', en: 'Ming Dynasty' },
      { ru: 'Династия Цинь', en: 'Qin Dynasty' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-38',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'В каком году была подписана Брестская мирная конвенция между Советской Россией и Центральными державами?',
    questionEn: 'In what year was the Treaty of Brest-Litovsk signed between Soviet Russia and the Central Powers?',
    options: [
      { ru: '1917', en: '1917' },
      { ru: '1918', en: '1918' },
      { ru: '1919', en: '1919' },
      { ru: '1920', en: '1920' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-39',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой город был столицей государства инков?',
    questionEn: 'What city was the capital of the Inca Empire?',
    options: [
      { ru: 'Мачу-Пикчу', en: 'Machu Picchu' },
      { ru: 'Куско', en: 'Cusco' },
      { ru: 'Теночтитлан', en: 'Tenochtitlan' },
      { ru: 'Лима', en: 'Lima' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-40',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой русский полководец командовал русской армией в Бородинской битве?',
    questionEn: 'Which Russian commander led the Russian army at the Battle of Borodino?',
    options: [
      { ru: 'Александр Суворов', en: 'Alexander Suvorov' },
      { ru: 'Михаил Кутузов', en: 'Mikhail Kutuzov' },
      { ru: 'Пётр Багратион', en: 'Pyotr Bagration' },
      { ru: 'Михаил Барклай-де-Толли', en: 'Mikhail Barclay de Tolly' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-41',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая битва 480 г. до н.э. стала знаменитым последним боем 300 спартанцев?',
    questionEn: 'Which battle of 480 BC became the famous last stand of the 300 Spartans?',
    options: [
      { ru: 'Битва при Марафоне', en: 'Battle of Marathon' },
      { ru: 'Битва при Саламине', en: 'Battle of Salamis' },
      { ru: 'Битва при Фермопилах', en: 'Battle of Thermopylae' },
      { ru: 'Битва при Платеях', en: 'Battle of Plataea' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'hist-42',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой мирный договор завершил Русско-японскую войну 1904–1905 годов?',
    questionEn: 'Which peace treaty ended the Russo-Japanese War of 1904–1905?',
    options: [
      { ru: 'Портсмутский мир', en: 'Treaty of Portsmouth' },
      { ru: 'Симоносекский договор', en: 'Treaty of Shimonoseki' },
      { ru: 'Сан-Стефанский мир', en: 'Treaty of San Stefano' },
      { ru: 'Тильзитский мир', en: 'Treaty of Tilsit' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-43',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой учёный расшифровал египетские иероглифы с помощью Розеттского камня?',
    questionEn: 'Which scholar deciphered Egyptian hieroglyphs using the Rosetta Stone?',
    options: [
      { ru: 'Говард Картер', en: 'Howard Carter' },
      { ru: 'Жан-Франсуа Шампольон', en: 'Jean-François Champollion' },
      { ru: 'Генрих Шлиман', en: 'Heinrich Schliemann' },
      { ru: 'Томас Юнг', en: 'Thomas Young' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-44',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая битва 1709 года стала решающей в Северной войне?',
    questionEn: 'Which battle of 1709 was decisive in the Great Northern War?',
    options: [
      { ru: 'Битва при Нарве', en: 'Battle of Narva' },
      { ru: 'Полтавская битва', en: 'Battle of Poltava' },
      { ru: 'Гангутское сражение', en: 'Battle of Gangut' },
      { ru: 'Битва при Лесной', en: 'Battle of Lesnaya' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-45',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Как называлась политика Отто фон Бисмарка по объединению Германии?',
    questionEn: 'What was Otto von Bismarck\'s policy for unifying Germany called?',
    options: [
      { ru: '«Железом и кровью»', en: 'Blood and Iron' },
      { ru: '«Реальная политика»', en: 'Realpolitik' },
      { ru: '«Культуркампф»', en: 'Kulturkampf' },
      { ru: '«Мировая политика»', en: 'Weltpolitik' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'hist-46',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой город был столицей Золотой Орды?',
    questionEn: 'What city was the capital of the Golden Horde?',
    options: [
      { ru: 'Каракорум', en: 'Karakorum' },
      { ru: 'Сарай-Бату', en: 'Sarai Batu' },
      { ru: 'Самарканд', en: 'Samarkand' },
      { ru: 'Булгар', en: 'Bolgar' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-47',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какая цивилизация создала клинописное письмо?',
    questionEn: 'Which civilization created cuneiform writing?',
    options: [
      { ru: 'Египтяне', en: 'Egyptians' },
      { ru: 'Шумеры', en: 'Sumerians' },
      { ru: 'Финикийцы', en: 'Phoenicians' },
      { ru: 'Хетты', en: 'Hittites' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-48',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой конгресс определил новый порядок в Европе после наполеоновских войн?',
    questionEn: 'Which congress established the new order in Europe after the Napoleonic Wars?',
    options: [
      { ru: 'Берлинский конгресс', en: 'Congress of Berlin' },
      { ru: 'Венский конгресс', en: 'Congress of Vienna' },
      { ru: 'Парижский конгресс', en: 'Congress of Paris' },
      { ru: 'Аахенский конгресс', en: 'Congress of Aix-la-Chapelle' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-49',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой английский король был казнён во время Английской гражданской войны?',
    questionEn: 'Which English king was executed during the English Civil War?',
    options: [
      { ru: 'Яков I', en: 'James I' },
      { ru: 'Карл I', en: 'Charles I' },
      { ru: 'Карл II', en: 'Charles II' },
      { ru: 'Генрих VIII', en: 'Henry VIII' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'hist-50',
    topic: 'history',
    difficulty: 'hard',
    questionRu: 'Какой древний торговый путь связывал Китай с Римской империей?',
    questionEn: 'Which ancient trade route connected China with the Roman Empire?',
    options: [
      { ru: 'Янтарный путь', en: 'Amber Road' },
      { ru: 'Путь благовоний', en: 'Incense Route' },
      { ru: 'Великий шёлковый путь', en: 'Silk Road' },
      { ru: 'Путь специй', en: 'Spice Route' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
];
