import { QuizQuestion } from '@/types/game';

export const POP_CULTURE_QUESTIONS: QuizQuestion[] = [
  // ==================== EASY (17) ====================
  {
    id: 'pop-1', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто сыграл Железного человека в киновселенной Marvel?',
    questionEn: 'Who played Iron Man in the Marvel Cinematic Universe?',
    options: [
      { ru: 'Крис Эванс', en: 'Chris Evans' },
      { ru: 'Роберт Дауни-мл.', en: 'Robert Downey Jr.' },
      { ru: 'Крис Хемсворт', en: 'Chris Hemsworth' },
      { ru: 'Марк Руффало', en: 'Mark Ruffalo' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-2', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая социальная сеть использует логотип с птицей?',
    questionEn: 'Which social network originally used a bird logo?',
    options: [
      { ru: 'Facebook', en: 'Facebook' },
      { ru: 'Instagram', en: 'Instagram' },
      { ru: 'Twitter', en: 'Twitter' },
      { ru: 'TikTok', en: 'TikTok' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-3', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как зовут главного героя серии фильмов о Гарри Поттере?',
    questionEn: 'What is the name of the main character in the Harry Potter series?',
    options: [
      { ru: 'Рон Уизли', en: 'Ron Weasley' },
      { ru: 'Гарри Поттер', en: 'Harry Potter' },
      { ru: 'Драко Малфой', en: 'Draco Malfoy' },
      { ru: 'Невилл Долгопупс', en: 'Neville Longbottom' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-4', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая игра стала самой продаваемой в мире?',
    questionEn: 'What is the best-selling video game of all time?',
    options: [
      { ru: 'Tetris', en: 'Tetris' },
      { ru: 'GTA V', en: 'GTA V' },
      { ru: 'Minecraft', en: 'Minecraft' },
      { ru: 'Fortnite', en: 'Fortnite' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-5', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто исполняет песню «Shape of You»?',
    questionEn: 'Who performs the song "Shape of You"?',
    options: [
      { ru: 'Джастин Бибер', en: 'Justin Bieber' },
      { ru: 'Эд Ширан', en: 'Ed Sheeran' },
      { ru: 'Бруно Марс', en: 'Bruno Mars' },
      { ru: 'Дрейк', en: 'Drake' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-6', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'В каком фильме Леонардо Ди Каприо наконец получил «Оскар»?',
    questionEn: 'For which movie did Leonardo DiCaprio finally win an Oscar?',
    options: [
      { ru: 'Титаник', en: 'Titanic' },
      { ru: 'Начало', en: 'Inception' },
      { ru: 'Выживший', en: 'The Revenant' },
      { ru: 'Волк с Уолл-стрит', en: 'The Wolf of Wall Street' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-7', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как называется аниме про парня с соломенной шляпой, который хочет стать Королём пиратов?',
    questionEn: 'What anime features a straw hat boy who wants to become King of the Pirates?',
    options: [
      { ru: 'Наруто', en: 'Naruto' },
      { ru: 'Ван Пис', en: 'One Piece' },
      { ru: 'Блич', en: 'Bleach' },
      { ru: 'Атака титанов', en: 'Attack on Titan' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-8', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой фильм первым в истории собрал более 2 миллиардов долларов?',
    questionEn: 'What was the first movie to gross over $2 billion?',
    options: [
      { ru: 'Мстители: Финал', en: 'Avengers: Endgame' },
      { ru: 'Аватар', en: 'Avatar' },
      { ru: 'Титаник', en: 'Titanic' },
      { ru: 'Звёздные войны', en: 'Star Wars' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-9', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая группа исполняет песню «Bohemian Rhapsody»?',
    questionEn: 'Which band performs "Bohemian Rhapsody"?',
    options: [
      { ru: 'The Beatles', en: 'The Beatles' },
      { ru: 'Queen', en: 'Queen' },
      { ru: 'Led Zeppelin', en: 'Led Zeppelin' },
      { ru: 'Pink Floyd', en: 'Pink Floyd' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-10', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как зовут жёлтую семью из знаменитого мультсериала?',
    questionEn: 'What is the name of the famous yellow cartoon family?',
    options: [
      { ru: 'Гриффины', en: 'The Griffins' },
      { ru: 'Симпсоны', en: 'The Simpsons' },
      { ru: 'Флинтстоуны', en: 'The Flintstones' },
      { ru: 'Джетсоны', en: 'The Jetsons' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-11', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой стриминговый сервис выпустил сериал «Очень странные дела»?',
    questionEn: 'Which streaming service released "Stranger Things"?',
    options: [
      { ru: 'Amazon Prime', en: 'Amazon Prime' },
      { ru: 'HBO Max', en: 'HBO Max' },
      { ru: 'Netflix', en: 'Netflix' },
      { ru: 'Disney+', en: 'Disney+' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-12', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто является создателем Facebook?',
    questionEn: 'Who is the founder of Facebook?',
    options: [
      { ru: 'Илон Маск', en: 'Elon Musk' },
      { ru: 'Билл Гейтс', en: 'Bill Gates' },
      { ru: 'Марк Цукерберг', en: 'Mark Zuckerberg' },
      { ru: 'Джефф Безос', en: 'Jeff Bezos' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-13', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой персонаж Nintendo является водопроводчиком?',
    questionEn: 'Which Nintendo character is a plumber?',
    options: [
      { ru: 'Линк', en: 'Link' },
      { ru: 'Марио', en: 'Mario' },
      { ru: 'Кирби', en: 'Kirby' },
      { ru: 'Донки Конг', en: 'Donkey Kong' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-14', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая певица известна как «Королева поп-музыки»?',
    questionEn: 'Which singer is known as the "Queen of Pop"?',
    options: [
      { ru: 'Бейонсе', en: 'Beyoncé' },
      { ru: 'Мадонна', en: 'Madonna' },
      { ru: 'Леди Гага', en: 'Lady Gaga' },
      { ru: 'Рианна', en: 'Rihanna' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-15', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как называется южнокорейский сериал о смертельных играх, ставший хитом Netflix?',
    questionEn: 'What is the Korean Netflix hit about deadly games?',
    options: [
      { ru: 'Алиса в пограничье', en: 'Alice in Borderland' },
      { ru: 'Игра в кальмара', en: 'Squid Game' },
      { ru: 'Сладкий дом', en: 'Sweet Home' },
      { ru: 'Паразиты', en: 'Parasite' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-16', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто озвучивает Шрека в оригинальной версии мультфильма?',
    questionEn: 'Who voices Shrek in the original movie?',
    options: [
      { ru: 'Эдди Мёрфи', en: 'Eddie Murphy' },
      { ru: 'Майк Майерс', en: 'Mike Myers' },
      { ru: 'Джек Блэк', en: 'Jack Black' },
      { ru: 'Уилл Смит', en: 'Will Smith' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-17', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой вид спорта является самым популярным в мире?',
    questionEn: 'What is the most popular sport in the world?',
    options: [
      { ru: 'Баскетбол', en: 'Basketball' },
      { ru: 'Крикет', en: 'Cricket' },
      { ru: 'Футбол', en: 'Football (Soccer)' },
      { ru: 'Теннис', en: 'Tennis' },
    ],
    correctIndex: 2,
  },

  // ==================== MEDIUM (17) ====================
  {
    id: 'pop-18', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'В каком году вышел первый iPhone?',
    questionEn: 'In what year was the first iPhone released?',
    options: [
      { ru: '2005', en: '2005' },
      { ru: '2006', en: '2006' },
      { ru: '2007', en: '2007' },
      { ru: '2008', en: '2008' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-19', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой фильм получил первый «Оскар» за лучший фильм?',
    questionEn: 'What film won the first Academy Award for Best Picture?',
    options: [
      { ru: 'Крылья', en: 'Wings' },
      { ru: 'Певец джаза', en: 'The Jazz Singer' },
      { ru: 'Санрайз', en: 'Sunrise' },
      { ru: 'Метрополис', en: 'Metropolis' },
    ],
    correctIndex: 0,
  },
  {
    id: 'pop-20', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Как настоящее имя рэпера Эминема?',
    questionEn: 'What is Eminem\'s real name?',
    options: [
      { ru: 'Кёртис Джексон', en: 'Curtis Jackson' },
      { ru: 'Маршалл Мэтерс', en: 'Marshall Mathers' },
      { ru: 'Шон Картер', en: 'Shawn Carter' },
      { ru: 'Андре Янг', en: 'Andre Young' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-21', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'В какой стране была создана манга «Наруто»?',
    questionEn: 'In which country was the manga "Naruto" created?',
    options: [
      { ru: 'Китай', en: 'China' },
      { ru: 'Южная Корея', en: 'South Korea' },
      { ru: 'Япония', en: 'Japan' },
      { ru: 'Тайвань', en: 'Taiwan' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-22', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая видеоигра впервые представила персонажа Марио?',
    questionEn: 'Which video game first featured the character Mario?',
    options: [
      { ru: 'Super Mario Bros.', en: 'Super Mario Bros.' },
      { ru: 'Donkey Kong', en: 'Donkey Kong' },
      { ru: 'Mario Bros.', en: 'Mario Bros.' },
      { ru: 'Super Mario World', en: 'Super Mario World' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-23', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Кто написал серию книг «Песнь льда и пламени», по которой снят «Игра престолов»?',
    questionEn: 'Who wrote the "A Song of Ice and Fire" series that "Game of Thrones" is based on?',
    options: [
      { ru: 'Дж. Р. Р. Толкин', en: 'J.R.R. Tolkien' },
      { ru: 'Джордж Р. Р. Мартин', en: 'George R.R. Martin' },
      { ru: 'Патрик Ротфусс', en: 'Patrick Rothfuss' },
      { ru: 'Брэндон Сандерсон', en: 'Brandon Sanderson' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-24', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая K-pop группа выпустила хит «Dynamite»?',
    questionEn: 'Which K-pop group released the hit "Dynamite"?',
    options: [
      { ru: 'BLACKPINK', en: 'BLACKPINK' },
      { ru: 'BTS', en: 'BTS' },
      { ru: 'EXO', en: 'EXO' },
      { ru: 'TWICE', en: 'TWICE' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-25', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Сколько фильмов входит в основную сагу «Звёздных войн»?',
    questionEn: 'How many films are in the main Star Wars saga?',
    options: [
      { ru: '6', en: '6' },
      { ru: '8', en: '8' },
      { ru: '9', en: '9' },
      { ru: '11', en: '11' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-26', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Как называлась первая песня, набравшая 1 миллиард просмотров на YouTube?',
    questionEn: 'What was the first song to reach 1 billion views on YouTube?',
    options: [
      { ru: 'Baby — Justin Bieber', en: 'Baby — Justin Bieber' },
      { ru: 'Gangnam Style — PSY', en: 'Gangnam Style — PSY' },
      { ru: 'See You Again — Wiz Khalifa', en: 'See You Again — Wiz Khalifa' },
      { ru: 'Despacito — Luis Fonsi', en: 'Despacito — Luis Fonsi' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-27', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой актёр сыграл Джокера в фильме «Тёмный рыцарь» (2008)?',
    questionEn: 'Who played the Joker in "The Dark Knight" (2008)?',
    options: [
      { ru: 'Джаред Лето', en: 'Jared Leto' },
      { ru: 'Хоакин Феникс', en: 'Joaquin Phoenix' },
      { ru: 'Хит Леджер', en: 'Heath Ledger' },
      { ru: 'Джек Николсон', en: 'Jack Nicholson' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-28', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая игра от Epic Games стала культурным феноменом в 2017–2018 годах?',
    questionEn: 'Which Epic Games title became a cultural phenomenon in 2017–2018?',
    options: [
      { ru: 'PUBG', en: 'PUBG' },
      { ru: 'Apex Legends', en: 'Apex Legends' },
      { ru: 'Fortnite', en: 'Fortnite' },
      { ru: 'Overwatch', en: 'Overwatch' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-29', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Кто является автором серии книг о Гарри Поттере?',
    questionEn: 'Who is the author of the Harry Potter book series?',
    options: [
      { ru: 'К. С. Льюис', en: 'C.S. Lewis' },
      { ru: 'Дж. К. Роулинг', en: 'J.K. Rowling' },
      { ru: 'Рик Риордан', en: 'Rick Riordan' },
      { ru: 'Сьюзен Коллинз', en: 'Suzanne Collins' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-30', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой сериал HBO рассказывает о семье Таргариенов?',
    questionEn: 'Which HBO series tells the story of House Targaryen?',
    options: [
      { ru: 'Игра престолов', en: 'Game of Thrones' },
      { ru: 'Дом Дракона', en: 'House of the Dragon' },
      { ru: 'Кольца власти', en: 'Rings of Power' },
      { ru: 'Ведьмак', en: 'The Witcher' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-31', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой футболист забил больше всего голов в истории?',
    questionEn: 'Which football player has scored the most goals in history?',
    options: [
      { ru: 'Лионель Месси', en: 'Lionel Messi' },
      { ru: 'Пеле', en: 'Pelé' },
      { ru: 'Криштиану Роналду', en: 'Cristiano Ronaldo' },
      { ru: 'Роберт Левандовски', en: 'Robert Lewandowski' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-32', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Как называется вымышленный металл из Ваканды в фильмах Marvel?',
    questionEn: 'What is the fictional metal from Wakanda in Marvel films?',
    options: [
      { ru: 'Адамантий', en: 'Adamantium' },
      { ru: 'Мифрил', en: 'Mithril' },
      { ru: 'Вибраниум', en: 'Vibranium' },
      { ru: 'Карбонадиум', en: 'Carbonadium' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-33', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая компания разработала игру The Witcher 3?',
    questionEn: 'Which company developed The Witcher 3?',
    options: [
      { ru: 'Bethesda', en: 'Bethesda' },
      { ru: 'CD Projekt Red', en: 'CD Projekt Red' },
      { ru: 'BioWare', en: 'BioWare' },
      { ru: 'Ubisoft', en: 'Ubisoft' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-34', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой мем стал символом 2020 года с котом и женщиной за столом?',
    questionEn: 'What meme features a woman yelling and a confused cat at a dinner table?',
    options: [
      { ru: 'Smudge the Cat', en: 'Smudge the Cat' },
      { ru: 'Grumpy Cat', en: 'Grumpy Cat' },
      { ru: 'Keyboard Cat', en: 'Keyboard Cat' },
      { ru: 'Nyan Cat', en: 'Nyan Cat' },
    ],
    correctIndex: 0,
  },

  // ==================== HARD (16) ====================
  {
    id: 'pop-35', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой альбом Майкла Джексона стал самым продаваемым в истории?',
    questionEn: 'What is Michael Jackson\'s best-selling album of all time?',
    options: [
      { ru: 'Bad', en: 'Bad' },
      { ru: 'Dangerous', en: 'Dangerous' },
      { ru: 'Thriller', en: 'Thriller' },
      { ru: 'Off the Wall', en: 'Off the Wall' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-36', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой фильм Квентина Тарантино получил «Золотую пальмовую ветвь» в Каннах?',
    questionEn: 'Which Quentin Tarantino film won the Palme d\'Or at Cannes?',
    options: [
      { ru: 'Убить Билла', en: 'Kill Bill' },
      { ru: 'Криминальное чтиво', en: 'Pulp Fiction' },
      { ru: 'Бесславные ублюдки', en: 'Inglourious Basterds' },
      { ru: 'Джанго освобождённый', en: 'Django Unchained' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-37', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Как называлась первая консоль Nintendo, выпущенная в Японии?',
    questionEn: 'What was Nintendo\'s first home console released in Japan?',
    options: [
      { ru: 'Nintendo 64', en: 'Nintendo 64' },
      { ru: 'Super Nintendo', en: 'Super Nintendo' },
      { ru: 'Family Computer (Famicom)', en: 'Family Computer (Famicom)' },
      { ru: 'Game Boy', en: 'Game Boy' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-38', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой режиссёр снял фильмы «Мементо», «Начало» и «Интерстеллар»?',
    questionEn: 'Which director made "Memento", "Inception", and "Interstellar"?',
    options: [
      { ru: 'Дэвид Финчер', en: 'David Fincher' },
      { ru: 'Кристофер Нолан', en: 'Christopher Nolan' },
      { ru: 'Дени Вильнёв', en: 'Denis Villeneuve' },
      { ru: 'Ридли Скотт', en: 'Ridley Scott' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-39', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какая рок-группа выпустила альбом «The Dark Side of the Moon» в 1973 году?',
    questionEn: 'Which rock band released "The Dark Side of the Moon" in 1973?',
    options: [
      { ru: 'Led Zeppelin', en: 'Led Zeppelin' },
      { ru: 'The Rolling Stones', en: 'The Rolling Stones' },
      { ru: 'Pink Floyd', en: 'Pink Floyd' },
      { ru: 'Deep Purple', en: 'Deep Purple' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-40', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Кто создал мангу «Берсерк»?',
    questionEn: 'Who created the manga "Berserk"?',
    options: [
      { ru: 'Эйитиро Ода', en: 'Eiichiro Oda' },
      { ru: 'Кэнтаро Миура', en: 'Kentaro Miura' },
      { ru: 'Хадзимэ Исаяма', en: 'Hajime Isayama' },
      { ru: 'Акира Торияма', en: 'Akira Toriyama' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-41', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какая игра студии FromSoftware получила награду «Игра года» на The Game Awards 2022?',
    questionEn: 'Which FromSoftware game won Game of the Year at The Game Awards 2022?',
    options: [
      { ru: 'Dark Souls III', en: 'Dark Souls III' },
      { ru: 'Sekiro', en: 'Sekiro' },
      { ru: 'Elden Ring', en: 'Elden Ring' },
      { ru: 'Bloodborne', en: 'Bloodborne' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-42', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой актёр сыграл главную роль в фильме «Олдбой» (2003)?',
    questionEn: 'Who starred in the 2003 Korean film "Oldboy"?',
    options: [
      { ru: 'Сон Кан-хо', en: 'Song Kang-ho' },
      { ru: 'Чхве Мин-сик', en: 'Choi Min-sik' },
      { ru: 'Ли Бён-хон', en: 'Lee Byung-hun' },
      { ru: 'Пак Чхан-ук', en: 'Park Chan-wook' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-43', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой альбом Radiohead часто называют одним из лучших альбомов 2000-х?',
    questionEn: 'Which Radiohead album is often considered one of the best albums of the 2000s?',
    options: [
      { ru: 'The Bends', en: 'The Bends' },
      { ru: 'OK Computer', en: 'OK Computer' },
      { ru: 'Kid A', en: 'Kid A' },
      { ru: 'In Rainbows', en: 'In Rainbows' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-44', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какая настольная игра является самой продаваемой в мире?',
    questionEn: 'What is the best-selling board game of all time?',
    options: [
      { ru: 'Монополия', en: 'Monopoly' },
      { ru: 'Шахматы', en: 'Chess' },
      { ru: 'Скрэббл', en: 'Scrabble' },
      { ru: 'Клуэдо', en: 'Cluedo' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-45', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Кто режиссёр аниме-фильма «Унесённые призраками»?',
    questionEn: 'Who directed the anime film "Spirited Away"?',
    options: [
      { ru: 'Макото Синкай', en: 'Makoto Shinkai' },
      { ru: 'Хаяо Миядзаки', en: 'Hayao Miyazaki' },
      { ru: 'Сатоси Кон', en: 'Satoshi Kon' },
      { ru: 'Мамору Хосода', en: 'Mamoru Hosoda' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-46', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой YouTube-канал первым набрал 100 миллионов подписчиков?',
    questionEn: 'Which YouTube channel was the first to reach 100 million subscribers?',
    options: [
      { ru: 'PewDiePie', en: 'PewDiePie' },
      { ru: 'T-Series', en: 'T-Series' },
      { ru: 'MrBeast', en: 'MrBeast' },
      { ru: 'Cocomelon', en: 'Cocomelon' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-47', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой фильм студии Pixar вышел первым?',
    questionEn: 'What was Pixar\'s first feature film?',
    options: [
      { ru: 'В поисках Немо', en: 'Finding Nemo' },
      { ru: 'Корпорация монстров', en: 'Monsters, Inc.' },
      { ru: 'История игрушек', en: 'Toy Story' },
      { ru: 'Жизнь жуков', en: 'A Bug\'s Life' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-48', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой музыкант выпустил альбом «Abbey Road» в 1969 году?',
    questionEn: 'Which band released the album "Abbey Road" in 1969?',
    options: [
      { ru: 'The Rolling Stones', en: 'The Rolling Stones' },
      { ru: 'The Beatles', en: 'The Beatles' },
      { ru: 'The Who', en: 'The Who' },
      { ru: 'The Doors', en: 'The Doors' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-49', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой сериал считается самым дорогим в истории телевидения (на 2022 год)?',
    questionEn: 'What is considered the most expensive TV series ever made (as of 2022)?',
    options: [
      { ru: 'Игра престолов', en: 'Game of Thrones' },
      { ru: 'Кольца власти', en: 'The Rings of Power' },
      { ru: 'Мандалорец', en: 'The Mandalorian' },
      { ru: 'Очень странные дела', en: 'Stranger Things' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-50', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой композитор написал музыку к фильмам «Начало», «Интерстеллар» и «Дюна»?',
    questionEn: 'Which composer scored "Inception", "Interstellar", and "Dune"?',
    options: [
      { ru: 'Джон Уильямс', en: 'John Williams' },
      { ru: 'Ханс Циммер', en: 'Hans Zimmer' },
      { ru: 'Говард Шор', en: 'Howard Shore' },
      { ru: 'Людвиг Йоранссон', en: 'Ludwig Göransson' },
    ],
    correctIndex: 1,
  },

  // ============================================================
  // === BATCH 2 — EASY (51-67) ===
  // ============================================================
  {
    id: 'pop-51', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой персонаж живёт в ананасе на дне океана?',
    questionEn: 'Which character lives in a pineapple under the sea?',
    options: [
      { ru: 'Патрик', en: 'Patrick' },
      { ru: 'Губка Боб', en: 'SpongeBob' },
      { ru: 'Сквидвард', en: 'Squidward' },
      { ru: 'Мистер Крабс', en: 'Mr. Krabs' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-52', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая певица известна как «Королева поп-музыки»?',
    questionEn: 'Which singer is known as the "Queen of Pop"?',
    options: [
      { ru: 'Бейонсе', en: 'Beyoncé' },
      { ru: 'Мадонна', en: 'Madonna' },
      { ru: 'Леди Гага', en: 'Lady Gaga' },
      { ru: 'Рианна', en: 'Rihanna' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-53', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'В какой видеоигре нужно собирать покемонов?',
    questionEn: 'In which video game do you catch Pokémon?',
    options: [
      { ru: 'Марио', en: 'Mario' },
      { ru: 'Зельда', en: 'Zelda' },
      { ru: 'Покемон', en: 'Pokémon' },
      { ru: 'Соник', en: 'Sonic' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-54', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой фильм рассказывает о тонущем корабле и любви Джека и Роуз?',
    questionEn: 'Which movie tells the story of a sinking ship and the love of Jack and Rose?',
    options: [
      { ru: 'Титаник', en: 'Titanic' },
      { ru: 'Посейдон', en: 'Poseidon' },
      { ru: 'Водный мир', en: 'Waterworld' },
      { ru: 'Перл-Харбор', en: 'Pearl Harbor' },
    ],
    correctIndex: 0,
  },
  {
    id: 'pop-55', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как зовут мальчика-волшебника из книг Дж. К. Роулинг?',
    questionEn: 'What is the name of the boy wizard from J.K. Rowling\'s books?',
    options: [
      { ru: 'Рон Уизли', en: 'Ron Weasley' },
      { ru: 'Гарри Поттер', en: 'Harry Potter' },
      { ru: 'Драко Малфой', en: 'Draco Malfoy' },
      { ru: 'Невилл Долгопупс', en: 'Neville Longbottom' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-56', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая платформа для коротких видео принадлежит компании ByteDance?',
    questionEn: 'Which short video platform is owned by ByteDance?',
    options: [
      { ru: 'YouTube Shorts', en: 'YouTube Shorts' },
      { ru: 'Instagram Reels', en: 'Instagram Reels' },
      { ru: 'TikTok', en: 'TikTok' },
      { ru: 'Snapchat', en: 'Snapchat' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-57', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто озвучивает осла в мультфильме «Шрек»?',
    questionEn: 'Who voices Donkey in the movie "Shrek"?',
    options: [
      { ru: 'Джим Керри', en: 'Jim Carrey' },
      { ru: 'Эдди Мёрфи', en: 'Eddie Murphy' },
      { ru: 'Уилл Смит', en: 'Will Smith' },
      { ru: 'Крис Рок', en: 'Chris Rock' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-58', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой цвет у светового меча ситхов в «Звёздных войнах»?',
    questionEn: 'What color is a Sith lightsaber in "Star Wars"?',
    options: [
      { ru: 'Синий', en: 'Blue' },
      { ru: 'Зелёный', en: 'Green' },
      { ru: 'Красный', en: 'Red' },
      { ru: 'Фиолетовый', en: 'Purple' },
    ],
    correctIndex: 2,
  },
  {
    id: 'pop-59', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая игровая консоль от Nintendo вышла в 2017 году?',
    questionEn: 'Which Nintendo console was released in 2017?',
    options: [
      { ru: 'Wii U', en: 'Wii U' },
      { ru: 'Nintendo Switch', en: 'Nintendo Switch' },
      { ru: 'Nintendo 3DS', en: 'Nintendo 3DS' },
      { ru: 'Game Boy', en: 'Game Boy' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-60', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Кто исполняет роль Джека Воробья в «Пиратах Карибского моря»?',
    questionEn: 'Who plays Jack Sparrow in "Pirates of the Caribbean"?',
    options: [
      { ru: 'Брэд Питт', en: 'Brad Pitt' },
      { ru: 'Джонни Депп', en: 'Johnny Depp' },
      { ru: 'Орландо Блум', en: 'Orlando Bloom' },
      { ru: 'Киану Ривз', en: 'Keanu Reeves' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-61', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой мультфильм Disney рассказывает о ледяной королеве Эльзе?',
    questionEn: 'Which Disney movie features the ice queen Elsa?',
    options: [
      { ru: 'Рапунцель', en: 'Tangled' },
      { ru: 'Холодное сердце', en: 'Frozen' },
      { ru: 'Моана', en: 'Moana' },
      { ru: 'Храбрая сердцем', en: 'Brave' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-62', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какая группа исполнила песню «Bohemian Rhapsody»?',
    questionEn: 'Which band performed "Bohemian Rhapsody"?',
    options: [
      { ru: 'The Beatles', en: 'The Beatles' },
      { ru: 'Queen', en: 'Queen' },
      { ru: 'Led Zeppelin', en: 'Led Zeppelin' },
      { ru: 'Pink Floyd', en: 'Pink Floyd' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-63', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'В каком аниме главный герой мечтает стать королём пиратов?',
    questionEn: 'In which anime does the main character dream of becoming King of the Pirates?',
    options: [
      { ru: 'Наруто', en: 'Naruto' },
      { ru: 'Ван Пис', en: 'One Piece' },
      { ru: 'Блич', en: 'Bleach' },
      { ru: 'Атака титанов', en: 'Attack on Titan' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-64', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой стриминговый сервис создал Netflix?',
    questionEn: 'What type of service is Netflix?',
    options: [
      { ru: 'Музыкальный', en: 'Music' },
      { ru: 'Видеостриминг', en: 'Video streaming' },
      { ru: 'Игровой', en: 'Gaming' },
      { ru: 'Подкасты', en: 'Podcasts' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-65', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Как зовут главного героя серии игр The Legend of Zelda?',
    questionEn: 'What is the name of the main character in The Legend of Zelda?',
    options: [
      { ru: 'Зельда', en: 'Zelda' },
      { ru: 'Линк', en: 'Link' },
      { ru: 'Ганон', en: 'Ganon' },
      { ru: 'Эпона', en: 'Epona' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-66', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой рэпер известен под псевдонимом Эминем?',
    questionEn: 'What is Eminem\'s real name?',
    options: [
      { ru: 'Маршалл Мэзерс', en: 'Marshall Mathers' },
      { ru: 'Кертис Джексон', en: 'Curtis Jackson' },
      { ru: 'Шон Картер', en: 'Shawn Carter' },
      { ru: 'Обри Грэм', en: 'Aubrey Graham' },
    ],
    correctIndex: 0,
  },
  {
    id: 'pop-67', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15,
    questionRu: 'Какой фильм 2009 года стал самым кассовым на тот момент?',
    questionEn: 'Which 2009 film became the highest-grossing at the time?',
    options: [
      { ru: 'Мстители', en: 'The Avengers' },
      { ru: 'Аватар', en: 'Avatar' },
      { ru: 'Начало', en: 'Inception' },
      { ru: 'Тёмный рыцарь', en: 'The Dark Knight' },
    ],
    correctIndex: 1,
  },

  // ============================================================
  // === BATCH 2 — MEDIUM (68-84) ===
  // ============================================================
  {
    id: 'pop-68', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой актёр сыграл Джокера в фильме «Тёмный рыцарь» (2008)?',
    questionEn: 'Which actor played the Joker in "The Dark Knight" (2008)?',
    options: [
      { ru: 'Джек Николсон', en: 'Jack Nicholson' },
      { ru: 'Хит Леджер', en: 'Heath Ledger' },
      { ru: 'Хоакин Феникс', en: 'Joaquin Phoenix' },
      { ru: 'Джаред Лето', en: 'Jared Leto' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-69', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая игра от Mojang стала одной из самых продаваемых в мире?',
    questionEn: 'Which Mojang game became one of the best-selling games ever?',
    options: [
      { ru: 'Terraria', en: 'Terraria' },
      { ru: 'Minecraft', en: 'Minecraft' },
      { ru: 'Roblox', en: 'Roblox' },
      { ru: 'Fortnite', en: 'Fortnite' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-70', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой сериал HBO основан на серии книг «Песнь льда и пламени»?',
    questionEn: 'Which HBO series is based on "A Song of Ice and Fire"?',
    options: [
      { ru: 'Викинги', en: 'Vikings' },
      { ru: 'Игра престолов', en: 'Game of Thrones' },
      { ru: 'Ведьмак', en: 'The Witcher' },
      { ru: 'Властелин колец', en: 'Lord of the Rings' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-71', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой южнокорейский фильм получил «Оскар» за лучший фильм в 2020 году?',
    questionEn: 'Which South Korean film won the Best Picture Oscar in 2020?',
    options: [
      { ru: 'Олдбой', en: 'Oldboy' },
      { ru: 'Паразиты', en: 'Parasite' },
      { ru: 'Поезд в Пусан', en: 'Train to Busan' },
      { ru: 'Минари', en: 'Minari' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-72', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая K-pop группа стала мировым феноменом с песней «Dynamite»?',
    questionEn: 'Which K-pop group became a global phenomenon with "Dynamite"?',
    options: [
      { ru: 'BLACKPINK', en: 'BLACKPINK' },
      { ru: 'BTS', en: 'BTS' },
      { ru: 'EXO', en: 'EXO' },
      { ru: 'TWICE', en: 'TWICE' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-73', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой режиссёр снял трилогию «Властелин колец»?',
    questionEn: 'Which director made "The Lord of the Rings" trilogy?',
    options: [
      { ru: 'Стивен Спилберг', en: 'Steven Spielberg' },
      { ru: 'Питер Джексон', en: 'Peter Jackson' },
      { ru: 'Кристофер Нолан', en: 'Christopher Nolan' },
      { ru: 'Джеймс Кэмерон', en: 'James Cameron' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-74', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'В каком году вышел первый iPhone?',
    questionEn: 'In what year was the first iPhone released?',
    options: [
      { ru: '2005', en: '2005' },
      { ru: '2007', en: '2007' },
      { ru: '2009', en: '2009' },
      { ru: '2010', en: '2010' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-75', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой персонаж Marvel собрал все Камни Бесконечности?',
    questionEn: 'Which Marvel character collected all the Infinity Stones?',
    options: [
      { ru: 'Локи', en: 'Loki' },
      { ru: 'Танос', en: 'Thanos' },
      { ru: 'Альтрон', en: 'Ultron' },
      { ru: 'Дормамму', en: 'Dormammu' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-76', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая настольная игра была создана Чарльзом Дэрроу в 1935 году?',
    questionEn: 'Which board game was created by Charles Darrow in 1935?',
    options: [
      { ru: 'Скрэббл', en: 'Scrabble' },
      { ru: 'Монополия', en: 'Monopoly' },
      { ru: 'Клуэдо', en: 'Cluedo' },
      { ru: 'Риск', en: 'Risk' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-77', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой актёр играет Нео в фильме «Матрица»?',
    questionEn: 'Which actor plays Neo in "The Matrix"?',
    options: [
      { ru: 'Уилл Смит', en: 'Will Smith' },
      { ru: 'Киану Ривз', en: 'Keanu Reeves' },
      { ru: 'Том Круз', en: 'Tom Cruise' },
      { ru: 'Бен Аффлек', en: 'Ben Affleck' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-78', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой музыкальный стриминг-сервис имеет зелёный логотип?',
    questionEn: 'Which music streaming service has a green logo?',
    options: [
      { ru: 'Apple Music', en: 'Apple Music' },
      { ru: 'Spotify', en: 'Spotify' },
      { ru: 'Deezer', en: 'Deezer' },
      { ru: 'Tidal', en: 'Tidal' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-79', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'В каком аниме персонажи используют «Тетрадь смерти»?',
    questionEn: 'In which anime do characters use a "Death Note"?',
    options: [
      { ru: 'Наруто', en: 'Naruto' },
      { ru: 'Тетрадь смерти', en: 'Death Note' },
      { ru: 'Токийский гуль', en: 'Tokyo Ghoul' },
      { ru: 'Хантер × Хантер', en: 'Hunter × Hunter' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-80', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой фильм Квентина Тарантино рассказывает о криминальном мире Лос-Анджелеса?',
    questionEn: 'Which Quentin Tarantino film is about the criminal underworld of LA?',
    options: [
      { ru: 'Убить Билла', en: 'Kill Bill' },
      { ru: 'Криминальное чтиво', en: 'Pulp Fiction' },
      { ru: 'Бешеные псы', en: 'Reservoir Dogs' },
      { ru: 'Джанго освобождённый', en: 'Django Unchained' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-81', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая серия игр от Rockstar Games известна открытым миром и криминальным сюжетом?',
    questionEn: 'Which Rockstar Games series is known for its open world and crime storyline?',
    options: [
      { ru: 'Red Dead Redemption', en: 'Red Dead Redemption' },
      { ru: 'Grand Theft Auto', en: 'Grand Theft Auto' },
      { ru: 'Max Payne', en: 'Max Payne' },
      { ru: 'Bully', en: 'Bully' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-82', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой мюзикл рассказывает историю Александра Гамильтона в стиле хип-хоп?',
    questionEn: 'Which musical tells the story of Alexander Hamilton in hip-hop style?',
    options: [
      { ru: 'Чикаго', en: 'Chicago' },
      { ru: 'Гамильтон', en: 'Hamilton' },
      { ru: 'Отверженные', en: 'Les Misérables' },
      { ru: 'Вестсайдская история', en: 'West Side Story' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-83', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какая социальная сеть принадлежит компании Meta (бывш. Facebook)?',
    questionEn: 'Which social network is owned by Meta (formerly Facebook)?',
    options: [
      { ru: 'Twitter', en: 'Twitter' },
      { ru: 'Instagram', en: 'Instagram' },
      { ru: 'TikTok', en: 'TikTok' },
      { ru: 'Snapchat', en: 'Snapchat' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-84', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20,
    questionRu: 'Какой сериал Netflix про шахматистку стал хитом в 2020 году?',
    questionEn: 'Which Netflix series about a chess player was a hit in 2020?',
    options: [
      { ru: 'Корона', en: 'The Crown' },
      { ru: 'Ход королевы', en: 'The Queen\'s Gambit' },
      { ru: 'Озарк', en: 'Ozark' },
      { ru: 'Люпен', en: 'Lupin' },
    ],
    correctIndex: 1,
  },

  // ============================================================
  // === BATCH 2 — HARD (85-100) ===
  // ============================================================
  {
    id: 'pop-85', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой фильм Стэнли Кубрика снят по роману Стивена Кинга?',
    questionEn: 'Which Stanley Kubrick film is based on a Stephen King novel?',
    options: [
      { ru: 'Заводной апельсин', en: 'A Clockwork Orange' },
      { ru: 'Сияние', en: 'The Shining' },
      { ru: '2001: Космическая одиссея', en: '2001: A Space Odyssey' },
      { ru: 'Цельнометаллическая оболочка', en: 'Full Metal Jacket' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-86', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какая группа выпустила альбом «The Dark Side of the Moon»?',
    questionEn: 'Which band released "The Dark Side of the Moon"?',
    options: [
      { ru: 'Led Zeppelin', en: 'Led Zeppelin' },
      { ru: 'Pink Floyd', en: 'Pink Floyd' },
      { ru: 'The Rolling Stones', en: 'The Rolling Stones' },
      { ru: 'Deep Purple', en: 'Deep Purple' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-87', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой японский режиссёр создал «Унесённых призраками»?',
    questionEn: 'Which Japanese director created "Spirited Away"?',
    options: [
      { ru: 'Акира Куросава', en: 'Akira Kurosawa' },
      { ru: 'Хаяо Миядзаки', en: 'Hayao Miyazaki' },
      { ru: 'Макото Синкай', en: 'Makoto Shinkai' },
      { ru: 'Сатоси Кон', en: 'Satoshi Kon' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-88', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой рэпер выпустил альбом «The Marshall Mathers LP»?',
    questionEn: 'Which rapper released "The Marshall Mathers LP"?',
    options: [
      { ru: 'Jay-Z', en: 'Jay-Z' },
      { ru: 'Eminem', en: 'Eminem' },
      { ru: 'Kanye West', en: 'Kanye West' },
      { ru: '50 Cent', en: '50 Cent' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-89', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'В какой игре от FromSoftware нужно сражаться с боссами в мире «Междуземья»?',
    questionEn: 'In which FromSoftware game do you fight bosses in the "Lands Between"?',
    options: [
      { ru: 'Dark Souls III', en: 'Dark Souls III' },
      { ru: 'Elden Ring', en: 'Elden Ring' },
      { ru: 'Sekiro', en: 'Sekiro' },
      { ru: 'Bloodborne', en: 'Bloodborne' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-90', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой альбом Radiohead часто называют одним из лучших в истории рок-музыки?',
    questionEn: 'Which Radiohead album is often called one of the greatest rock albums ever?',
    options: [
      { ru: 'The Bends', en: 'The Bends' },
      { ru: 'OK Computer', en: 'OK Computer' },
      { ru: 'Kid A', en: 'Kid A' },
      { ru: 'In Rainbows', en: 'In Rainbows' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-91', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой фильм Дэвида Финчера основан на книге Чака Паланика?',
    questionEn: 'Which David Fincher film is based on a Chuck Palahniuk novel?',
    options: [
      { ru: 'Семь', en: 'Se7en' },
      { ru: 'Бойцовский клуб', en: 'Fight Club' },
      { ru: 'Зодиак', en: 'Zodiac' },
      { ru: 'Социальная сеть', en: 'The Social Network' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-92', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой композитор написал музыку к «Звёздным войнам»?',
    questionEn: 'Who composed the music for "Star Wars"?',
    options: [
      { ru: 'Ханс Циммер', en: 'Hans Zimmer' },
      { ru: 'Джон Уильямс', en: 'John Williams' },
      { ru: 'Говард Шор', en: 'Howard Shore' },
      { ru: 'Эннио Морриконе', en: 'Ennio Morricone' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-93', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой писатель-фантаст написал «Дюну»?',
    questionEn: 'Which science fiction author wrote "Dune"?',
    options: [
      { ru: 'Айзек Азимов', en: 'Isaac Asimov' },
      { ru: 'Фрэнк Герберт', en: 'Frank Herbert' },
      { ru: 'Артур Кларк', en: 'Arthur C. Clarke' },
      { ru: 'Рэй Брэдбери', en: 'Ray Bradbury' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-94', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой стриминговый сервис создал сериал «Мандалорец»?',
    questionEn: 'Which streaming service created "The Mandalorian"?',
    options: [
      { ru: 'Netflix', en: 'Netflix' },
      { ru: 'Disney+', en: 'Disney+' },
      { ru: 'HBO Max', en: 'HBO Max' },
      { ru: 'Amazon Prime', en: 'Amazon Prime' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-95', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой актёр снялся в фильмах «Побег из Шоушенка» и «Брюс Всемогущий»?',
    questionEn: 'Which actor starred in both "The Shawshank Redemption" and "Bruce Almighty"?',
    options: [
      { ru: 'Тим Роббинс', en: 'Tim Robbins' },
      { ru: 'Морган Фримен', en: 'Morgan Freeman' },
      { ru: 'Джим Керри', en: 'Jim Carrey' },
      { ru: 'Сэмюэл Л. Джексон', en: 'Samuel L. Jackson' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-96', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой художник известен работами с банками супа Campbell\'s?',
    questionEn: 'Which artist is famous for works featuring Campbell\'s soup cans?',
    options: [
      { ru: 'Рой Лихтенштейн', en: 'Roy Lichtenstein' },
      { ru: 'Энди Уорхол', en: 'Andy Warhol' },
      { ru: 'Бэнкси', en: 'Banksy' },
      { ru: 'Жан-Мишель Баския', en: 'Jean-Michel Basquiat' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-97', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой сериал Netflix про игру на выживание стал мировым хитом в 2021?',
    questionEn: 'Which Netflix series about a survival game became a global hit in 2021?',
    options: [
      { ru: 'Алиса в Пограничье', en: 'Alice in Borderland' },
      { ru: 'Игра в кальмара', en: 'Squid Game' },
      { ru: 'Тёмная', en: 'Dark' },
      { ru: '3%', en: '3%' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-98', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Кто является создателем серии игр Metal Gear?',
    questionEn: 'Who is the creator of the Metal Gear series?',
    options: [
      { ru: 'Сигэру Миямото', en: 'Shigeru Miyamoto' },
      { ru: 'Хидео Кодзима', en: 'Hideo Kojima' },
      { ru: 'Хидэаки Анно', en: 'Hideaki Anno' },
      { ru: 'Тоби Фокс', en: 'Toby Fox' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-99', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какой фильм Кристофера Нолана рассказывает о снах внутри снов?',
    questionEn: 'Which Christopher Nolan film is about dreams within dreams?',
    options: [
      { ru: 'Интерстеллар', en: 'Interstellar' },
      { ru: 'Начало', en: 'Inception' },
      { ru: 'Довод', en: 'Tenet' },
      { ru: 'Престиж', en: 'The Prestige' },
    ],
    correctIndex: 1,
  },
  {
    id: 'pop-100', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25,
    questionRu: 'Какая книга Джорджа Оруэлла описывает тоталитарное общество с «Большим Братом»?',
    questionEn: 'Which George Orwell book describes a totalitarian society with "Big Brother"?',
    options: [
      { ru: 'Скотный двор', en: 'Animal Farm' },
      { ru: '1984', en: '1984' },
      { ru: 'О дивный новый мир', en: 'Brave New World' },
      { ru: '451 градус по Фаренгейту', en: 'Fahrenheit 451' },
    ],
    correctIndex: 1,
  },
  // ============================================================
  // === BATCH 3 — EASY (101-117) ===
  // ============================================================
  { id: 'pop-101', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой супергерой носит костюм паука?', questionEn: 'Which superhero wears a spider suit?', options: [{ ru: 'Бэтмен', en: 'Batman' }, { ru: 'Человек-паук', en: 'Spider-Man' }, { ru: 'Супермен', en: 'Superman' }, { ru: 'Флэш', en: 'Flash' }], correctIndex: 1 },
  { id: 'pop-102', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой мультфильм Pixar рассказывает об игрушках, которые оживают?', questionEn: 'Which Pixar movie is about toys that come to life?', options: [{ ru: 'Корпорация монстров', en: 'Monsters, Inc.' }, { ru: 'История игрушек', en: 'Toy Story' }, { ru: 'В поисках Немо', en: 'Finding Nemo' }, { ru: 'Тачки', en: 'Cars' }], correctIndex: 1 },
  { id: 'pop-103', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая певица известна хитом «Bad Guy»?', questionEn: 'Which singer is known for "Bad Guy"?', options: [{ ru: 'Ариана Гранде', en: 'Ariana Grande' }, { ru: 'Билли Айлиш', en: 'Billie Eilish' }, { ru: 'Дуа Липа', en: 'Dua Lipa' }, { ru: 'Тейлор Свифт', en: 'Taylor Swift' }], correctIndex: 1 },
  { id: 'pop-104', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой персонаж говорит «Я есть Грут»?', questionEn: 'Which character says "I am Groot"?', options: [{ ru: 'Ракета', en: 'Rocket' }, { ru: 'Грут', en: 'Groot' }, { ru: 'Дракс', en: 'Drax' }, { ru: 'Гамора', en: 'Gamora' }], correctIndex: 1 },
  { id: 'pop-105', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'В какой игре нужно строить и выживать в мире из блоков?', questionEn: 'In which game do you build and survive in a block world?', options: [{ ru: 'Fortnite', en: 'Fortnite' }, { ru: 'Minecraft', en: 'Minecraft' }, { ru: 'Roblox', en: 'Roblox' }, { ru: 'Terraria', en: 'Terraria' }], correctIndex: 1 },
  { id: 'pop-106', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Кто поёт песню «Shape of You»?', questionEn: 'Who sings "Shape of You"?', options: [{ ru: 'Джастин Бибер', en: 'Justin Bieber' }, { ru: 'Эд Ширан', en: 'Ed Sheeran' }, { ru: 'Брюно Марс', en: 'Bruno Mars' }, { ru: 'Шон Мендес', en: 'Shawn Mendes' }], correctIndex: 1 },
  { id: 'pop-107', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Как зовут принцессу из мультфильма «Русалочка»?', questionEn: 'What is the princess\'s name in "The Little Mermaid"?', options: [{ ru: 'Белль', en: 'Belle' }, { ru: 'Ариэль', en: 'Ariel' }, { ru: 'Жасмин', en: 'Jasmine' }, { ru: 'Аврора', en: 'Aurora' }], correctIndex: 1 },
  { id: 'pop-108', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой фильм начинается с фразы «Давным-давно в далёкой галактике...»?', questionEn: 'Which movie begins with "A long time ago in a galaxy far, far away..."?', options: [{ ru: 'Стартрек', en: 'Star Trek' }, { ru: 'Звёздные войны', en: 'Star Wars' }, { ru: 'Чужой', en: 'Alien' }, { ru: 'Интерстеллар', en: 'Interstellar' }], correctIndex: 1 },
  { id: 'pop-109', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой видеохостинг принадлежит Google?', questionEn: 'Which video platform is owned by Google?', options: [{ ru: 'Vimeo', en: 'Vimeo' }, { ru: 'YouTube', en: 'YouTube' }, { ru: 'Dailymotion', en: 'Dailymotion' }, { ru: 'Twitch', en: 'Twitch' }], correctIndex: 1 },
  { id: 'pop-110', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Кто создал персонажа Микки Мауса?', questionEn: 'Who created Mickey Mouse?', options: [{ ru: 'Стив Джобс', en: 'Steve Jobs' }, { ru: 'Уолт Дисней', en: 'Walt Disney' }, { ru: 'Стэн Ли', en: 'Stan Lee' }, { ru: 'Хаяо Миядзаки', en: 'Hayao Miyazaki' }], correctIndex: 1 },
  { id: 'pop-111', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой вид спорта является главным в серии игр FIFA?', questionEn: 'What sport is the main focus of the FIFA game series?', options: [{ ru: 'Баскетбол', en: 'Basketball' }, { ru: 'Футбол', en: 'Football/Soccer' }, { ru: 'Хоккей', en: 'Hockey' }, { ru: 'Теннис', en: 'Tennis' }], correctIndex: 1 },
  { id: 'pop-112', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой актёр играет Джона Уика?', questionEn: 'Which actor plays John Wick?', options: [{ ru: 'Том Круз', en: 'Tom Cruise' }, { ru: 'Киану Ривз', en: 'Keanu Reeves' }, { ru: 'Джейсон Стэйтем', en: 'Jason Statham' }, { ru: 'Лиам Нисон', en: 'Liam Neeson' }], correctIndex: 1 },
  { id: 'pop-113', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая песня Луиса Фонси стала мировым хитом в 2017?', questionEn: 'Which Luis Fonsi song became a global hit in 2017?', options: [{ ru: 'Bailando', en: 'Bailando' }, { ru: 'Despacito', en: 'Despacito' }, { ru: 'Vivir Mi Vida', en: 'Vivir Mi Vida' }, { ru: 'Mi Gente', en: 'Mi Gente' }], correctIndex: 1 },
  { id: 'pop-114', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой мессенджер использует зелёную иконку с телефонной трубкой?', questionEn: 'Which messenger uses a green icon with a phone handset?', options: [{ ru: 'Telegram', en: 'Telegram' }, { ru: 'WhatsApp', en: 'WhatsApp' }, { ru: 'Viber', en: 'Viber' }, { ru: 'Signal', en: 'Signal' }], correctIndex: 1 },
  { id: 'pop-115', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой персонаж Nintendo — водопроводчик в красной кепке?', questionEn: 'Which Nintendo character is a plumber in a red cap?', options: [{ ru: 'Луиджи', en: 'Luigi' }, { ru: 'Марио', en: 'Mario' }, { ru: 'Тоад', en: 'Toad' }, { ru: 'Йоши', en: 'Yoshi' }], correctIndex: 1 },
  { id: 'pop-116', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой фильм 2019 года собрал больше всех денег в истории кино?', questionEn: 'Which 2019 film became the highest-grossing movie ever?', options: [{ ru: 'Аватар', en: 'Avatar' }, { ru: 'Мстители: Финал', en: 'Avengers: Endgame' }, { ru: 'Король Лев', en: 'The Lion King' }, { ru: 'Джокер', en: 'Joker' }], correctIndex: 1 },
  { id: 'pop-117', topic: 'pop-culture', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая серия книг написана Дж. Р. Р. Толкином?', questionEn: 'Which book series was written by J.R.R. Tolkien?', options: [{ ru: 'Хроники Нарнии', en: 'Chronicles of Narnia' }, { ru: 'Властелин колец', en: 'Lord of the Rings' }, { ru: 'Гарри Поттер', en: 'Harry Potter' }, { ru: 'Голодные игры', en: 'Hunger Games' }], correctIndex: 1 },
  // ============================================================
  // === BATCH 3 — MEDIUM (118-134) ===
  // ============================================================
  { id: 'pop-118', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой фильм Уэса Андерсона рассказывает о семье Тененбаумов?', questionEn: 'Which Wes Anderson film is about the Tenenbaum family?', options: [{ ru: 'Отель «Гранд Будапешт»', en: 'The Grand Budapest Hotel' }, { ru: 'Семейка Тененбаум', en: 'The Royal Tenenbaums' }, { ru: 'Остров собак', en: 'Isle of Dogs' }, { ru: 'Водная жизнь', en: 'The Life Aquatic' }], correctIndex: 1 },
  { id: 'pop-119', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая игра от CD Projekt RED вышла в 2020 году с множеством багов?', questionEn: 'Which CD Projekt RED game launched in 2020 with many bugs?', options: [{ ru: 'Ведьмак 3', en: 'The Witcher 3' }, { ru: 'Cyberpunk 2077', en: 'Cyberpunk 2077' }, { ru: 'Ведьмак 2', en: 'The Witcher 2' }, { ru: 'Gwent', en: 'Gwent' }], correctIndex: 1 },
  { id: 'pop-120', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой певец известен как «Король поп-музыки»?', questionEn: 'Which singer is known as the "King of Pop"?', options: [{ ru: 'Элвис Пресли', en: 'Elvis Presley' }, { ru: 'Майкл Джексон', en: 'Michael Jackson' }, { ru: 'Принс', en: 'Prince' }, { ru: 'Фредди Меркьюри', en: 'Freddie Mercury' }], correctIndex: 1 },
  { id: 'pop-121', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой сериал Apple TV+ о футбольном тренере из Америки в Англии?', questionEn: 'Which Apple TV+ series is about an American football coach in England?', options: [{ ru: 'Утреннее шоу', en: 'The Morning Show' }, { ru: 'Тед Лассо', en: 'Ted Lasso' }, { ru: 'Основание', en: 'Foundation' }, { ru: 'Разделение', en: 'Severance' }], correctIndex: 1 },
  { id: 'pop-122', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой диджей выпустил хит «Wake Me Up»?', questionEn: 'Which DJ released the hit "Wake Me Up"?', options: [{ ru: 'Calvin Harris', en: 'Calvin Harris' }, { ru: 'Avicii', en: 'Avicii' }, { ru: 'David Guetta', en: 'David Guetta' }, { ru: 'Martin Garrix', en: 'Martin Garrix' }], correctIndex: 1 },
  { id: 'pop-123', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Кто режиссёр фильма «Бесславные ублюдки»?', questionEn: 'Who directed "Inglourious Basterds"?', options: [{ ru: 'Мартин Скорсезе', en: 'Martin Scorsese' }, { ru: 'Квентин Тарантино', en: 'Quentin Tarantino' }, { ru: 'Ридли Скотт', en: 'Ridley Scott' }, { ru: 'Гай Ричи', en: 'Guy Ritchie' }], correctIndex: 1 },
  { id: 'pop-124', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая серия игр известна фразой «War never changes»?', questionEn: 'Which game series is known for "War never changes"?', options: [{ ru: 'Call of Duty', en: 'Call of Duty' }, { ru: 'Fallout', en: 'Fallout' }, { ru: 'Battlefield', en: 'Battlefield' }, { ru: 'Metal Gear', en: 'Metal Gear' }], correctIndex: 1 },
  { id: 'pop-125', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой фильм получил «Оскар» за лучший фильм в 2024 году?', questionEn: 'Which film won Best Picture at the 2024 Oscars?', options: [{ ru: 'Барби', en: 'Barbie' }, { ru: 'Оппенгеймер', en: 'Oppenheimer' }, { ru: 'Бедные-несчастные', en: 'Poor Things' }, { ru: 'Убийцы цветочной луны', en: 'Killers of the Flower Moon' }], correctIndex: 1 },
  { id: 'pop-126', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая группа выпустила альбом «Abbey Road»?', questionEn: 'Which band released the album "Abbey Road"?', options: [{ ru: 'The Rolling Stones', en: 'The Rolling Stones' }, { ru: 'The Beatles', en: 'The Beatles' }, { ru: 'The Who', en: 'The Who' }, { ru: 'The Doors', en: 'The Doors' }], correctIndex: 1 },
  { id: 'pop-127', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой персонаж DC Comics родом с планеты Криптон?', questionEn: 'Which DC Comics character is from the planet Krypton?', options: [{ ru: 'Бэтмен', en: 'Batman' }, { ru: 'Супермен', en: 'Superman' }, { ru: 'Аквамен', en: 'Aquaman' }, { ru: 'Флэш', en: 'Flash' }], correctIndex: 1 },
  { id: 'pop-128', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой стример стал самым популярным на Twitch?', questionEn: 'Which platform is primarily used for live game streaming?', options: [{ ru: 'YouTube', en: 'YouTube' }, { ru: 'Twitch', en: 'Twitch' }, { ru: 'TikTok', en: 'TikTok' }, { ru: 'Discord', en: 'Discord' }], correctIndex: 1 },
  { id: 'pop-129', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой сериал HBO рассказывает о постапокалиптическом мире с грибковой инфекцией?', questionEn: 'Which HBO series is set in a post-apocalyptic world with a fungal infection?', options: [{ ru: 'Ходячие мертвецы', en: 'The Walking Dead' }, { ru: 'Одни из нас', en: 'The Last of Us' }, { ru: 'Станция Одиннадцать', en: 'Station Eleven' }, { ru: 'Выжившие', en: 'The 100' }], correctIndex: 1 },
  { id: 'pop-130', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Кто написал серию книг «Песнь льда и пламени»?', questionEn: 'Who wrote the "A Song of Ice and Fire" series?', options: [{ ru: 'Дж. Р. Р. Толкин', en: 'J.R.R. Tolkien' }, { ru: 'Джордж Р. Р. Мартин', en: 'George R.R. Martin' }, { ru: 'Стивен Кинг', en: 'Stephen King' }, { ru: 'Патрик Ротфусс', en: 'Patrick Rothfuss' }], correctIndex: 1 },
  { id: 'pop-131', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой артист выпустил альбом «Thriller» — самый продаваемый в истории?', questionEn: 'Which artist released "Thriller" — the best-selling album ever?', options: [{ ru: 'Принс', en: 'Prince' }, { ru: 'Майкл Джексон', en: 'Michael Jackson' }, { ru: 'Уитни Хьюстон', en: 'Whitney Houston' }, { ru: 'Элтон Джон', en: 'Elton John' }], correctIndex: 1 },
  { id: 'pop-132', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая компания создала PlayStation?', questionEn: 'Which company created PlayStation?', options: [{ ru: 'Nintendo', en: 'Nintendo' }, { ru: 'Sony', en: 'Sony' }, { ru: 'Microsoft', en: 'Microsoft' }, { ru: 'Sega', en: 'Sega' }], correctIndex: 1 },
  { id: 'pop-133', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой фильм Дени Вильнёва 2021 года основан на научно-фантастическом романе?', questionEn: 'Which 2021 Denis Villeneuve film is based on a sci-fi novel?', options: [{ ru: 'Прибытие', en: 'Arrival' }, { ru: 'Дюна', en: 'Dune' }, { ru: 'Бегущий по лезвию 2049', en: 'Blade Runner 2049' }, { ru: 'Сикарио', en: 'Sicario' }], correctIndex: 1 },
  { id: 'pop-134', topic: 'pop-culture', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая певица известна хитами «Halo» и «Single Ladies»?', questionEn: 'Which singer is known for "Halo" and "Single Ladies"?', options: [{ ru: 'Рианна', en: 'Rihanna' }, { ru: 'Бейонсе', en: 'Beyoncé' }, { ru: 'Адель', en: 'Adele' }, { ru: 'Леди Гага', en: 'Lady Gaga' }], correctIndex: 1 },
  // ============================================================
  // === BATCH 3 — HARD (135-150) ===
  // ============================================================
  { id: 'pop-135', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой режиссёр снял «Малхолланд Драйв» и «Твин Пикс»?', questionEn: 'Which director made "Mulholland Drive" and "Twin Peaks"?', options: [{ ru: 'Дэвид Кроненберг', en: 'David Cronenberg' }, { ru: 'Дэвид Линч', en: 'David Lynch' }, { ru: 'Дэвид Финчер', en: 'David Fincher' }, { ru: 'Стэнли Кубрик', en: 'Stanley Kubrick' }], correctIndex: 1 },
  { id: 'pop-136', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая группа выпустила альбом «In Utero» в 1993 году?', questionEn: 'Which band released "In Utero" in 1993?', options: [{ ru: 'Pearl Jam', en: 'Pearl Jam' }, { ru: 'Nirvana', en: 'Nirvana' }, { ru: 'Soundgarden', en: 'Soundgarden' }, { ru: 'Alice in Chains', en: 'Alice in Chains' }], correctIndex: 1 },
  { id: 'pop-137', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Кто создал мангу «Берсерк»?', questionEn: 'Who created the manga "Berserk"?', options: [{ ru: 'Акира Торияма', en: 'Akira Toriyama' }, { ru: 'Кэнтаро Миура', en: 'Kentaro Miura' }, { ru: 'Эйитиро Ода', en: 'Eiichiro Oda' }, { ru: 'Хадзимэ Исаяма', en: 'Hajime Isayama' }], correctIndex: 1 },
  { id: 'pop-138', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой фильм братьев Коэнов получил 4 «Оскара» в 2008 году?', questionEn: 'Which Coen Brothers film won 4 Oscars in 2008?', options: [{ ru: 'Фарго', en: 'Fargo' }, { ru: 'Старикам тут не место', en: 'No Country for Old Men' }, { ru: 'Большой Лебовски', en: 'The Big Lebowski' }, { ru: 'Железная хватка', en: 'True Grit' }], correctIndex: 1 },
  { id: 'pop-139', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая инди-игра 2015 года создана Тоби Фоксом?', questionEn: 'Which 2015 indie game was created by Toby Fox?', options: [{ ru: 'Hollow Knight', en: 'Hollow Knight' }, { ru: 'Undertale', en: 'Undertale' }, { ru: 'Celeste', en: 'Celeste' }, { ru: 'Stardew Valley', en: 'Stardew Valley' }], correctIndex: 1 },
  { id: 'pop-140', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой рэпер выпустил альбом «My Beautiful Dark Twisted Fantasy»?', questionEn: 'Which rapper released "My Beautiful Dark Twisted Fantasy"?', options: [{ ru: 'Drake', en: 'Drake' }, { ru: 'Kanye West', en: 'Kanye West' }, { ru: 'Kendrick Lamar', en: 'Kendrick Lamar' }, { ru: 'J. Cole', en: 'J. Cole' }], correctIndex: 1 },
  { id: 'pop-141', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой фильм Андрея Тарковского считается шедевром научной фантастики?', questionEn: 'Which Andrei Tarkovsky film is considered a sci-fi masterpiece?', options: [{ ru: 'Зеркало', en: 'Mirror' }, { ru: 'Солярис', en: 'Solaris' }, { ru: 'Иваново детство', en: 'Ivan\'s Childhood' }, { ru: 'Ностальгия', en: 'Nostalgia' }], correctIndex: 1 },
  { id: 'pop-142', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая серия игр от Naughty Dog рассказывает об охотнике за сокровищами?', questionEn: 'Which Naughty Dog series is about a treasure hunter?', options: [{ ru: 'The Last of Us', en: 'The Last of Us' }, { ru: 'Uncharted', en: 'Uncharted' }, { ru: 'Crash Bandicoot', en: 'Crash Bandicoot' }, { ru: 'Jak and Daxter', en: 'Jak and Daxter' }], correctIndex: 1 },
  { id: 'pop-143', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой альбом Kendrick Lamar получил Пулитцеровскую премию?', questionEn: 'Which Kendrick Lamar album won a Pulitzer Prize?', options: [{ ru: 'good kid, m.A.A.d city', en: 'good kid, m.A.A.d city' }, { ru: 'DAMN.', en: 'DAMN.' }, { ru: 'To Pimp a Butterfly', en: 'To Pimp a Butterfly' }, { ru: 'Mr. Morale', en: 'Mr. Morale' }], correctIndex: 1 },
  { id: 'pop-144', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Кто написал роман «Бойня номер пять»?', questionEn: 'Who wrote "Slaughterhouse-Five"?', options: [{ ru: 'Рэй Брэдбери', en: 'Ray Bradbury' }, { ru: 'Курт Воннегут', en: 'Kurt Vonnegut' }, { ru: 'Филип Дик', en: 'Philip K. Dick' }, { ru: 'Харпер Ли', en: 'Harper Lee' }], correctIndex: 1 },
  { id: 'pop-145', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой фильм Вонга Кар-Вая считается вершиной гонконгского кино?', questionEn: 'Which Wong Kar-wai film is considered the pinnacle of Hong Kong cinema?', options: [{ ru: 'Чунгкингский экспресс', en: 'Chungking Express' }, { ru: 'Любовное настроение', en: 'In the Mood for Love' }, { ru: 'Счастливы вместе', en: 'Happy Together' }, { ru: '2046', en: '2046' }], correctIndex: 1 },
  { id: 'pop-146', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая студия создала серию игр Dark Souls?', questionEn: 'Which studio created the Dark Souls series?', options: [{ ru: 'Capcom', en: 'Capcom' }, { ru: 'FromSoftware', en: 'FromSoftware' }, { ru: 'Square Enix', en: 'Square Enix' }, { ru: 'Konami', en: 'Konami' }], correctIndex: 1 },
  { id: 'pop-147', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой документальный фильм Netflix рассказывает о Тигровом Короле?', questionEn: 'Which Netflix documentary is about the Tiger King?', options: [{ ru: 'Making a Murderer', en: 'Making a Murderer' }, { ru: 'Tiger King', en: 'Tiger King' }, { ru: 'The Social Dilemma', en: 'The Social Dilemma' }, { ru: 'Icarus', en: 'Icarus' }], correctIndex: 1 },
  { id: 'pop-148', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой певец известен хитом «Blinding Lights»?', questionEn: 'Which singer is known for "Blinding Lights"?', options: [{ ru: 'Post Malone', en: 'Post Malone' }, { ru: 'The Weeknd', en: 'The Weeknd' }, { ru: 'Dua Lipa', en: 'Dua Lipa' }, { ru: 'Harry Styles', en: 'Harry Styles' }], correctIndex: 1 },
  { id: 'pop-149', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой режиссёр снял фильмы «Олдбой» и «Сочувствие госпоже Месть»?', questionEn: 'Which director made "Oldboy" and "Lady Vengeance"?', options: [{ ru: 'Пон Джун-хо', en: 'Bong Joon-ho' }, { ru: 'Пак Чхан-ук', en: 'Park Chan-wook' }, { ru: 'Ким Ки-дук', en: 'Kim Ki-duk' }, { ru: 'Хон Сан-су', en: 'Hong Sang-soo' }], correctIndex: 1 },
  { id: 'pop-150', topic: 'pop-culture', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой писатель создал мир «Тёмной Башни»?', questionEn: 'Which author created the "Dark Tower" universe?', options: [{ ru: 'Нил Гейман', en: 'Neil Gaiman' }, { ru: 'Стивен Кинг', en: 'Stephen King' }, { ru: 'Терри Пратчетт', en: 'Terry Pratchett' }, { ru: 'Брэндон Сандерсон', en: 'Brandon Sanderson' }], correctIndex: 1 },
];
