import { QuizQuestion } from '@/types/game';

export const SCIENCE_QUESTIONS: QuizQuestion[] = [
  // === EASY (1-17) ===
  {
    id: 'sci-1',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая планета ближе всего к Солнцу?',
    questionEn: 'What planet is closest to the Sun?',
    options: [
      { ru: 'Венера', en: 'Venus' },
      { ru: 'Меркурий', en: 'Mercury' },
      { ru: 'Марс', en: 'Mars' },
      { ru: 'Земля', en: 'Earth' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-2',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой газ необходим для дыхания человека?',
    questionEn: 'What gas is essential for human breathing?',
    options: [
      { ru: 'Углекислый газ', en: 'Carbon dioxide' },
      { ru: 'Азот', en: 'Nitrogen' },
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Водород', en: 'Hydrogen' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-3',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько костей в теле взрослого человека?',
    questionEn: 'How many bones are in an adult human body?',
    options: [
      { ru: '206', en: '206' },
      { ru: '300', en: '300' },
      { ru: '150', en: '150' },
      { ru: '180', en: '180' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'sci-4',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой химический символ у воды?',
    questionEn: 'What is the chemical formula for water?',
    options: [
      { ru: 'CO₂', en: 'CO₂' },
      { ru: 'O₂', en: 'O₂' },
      { ru: 'H₂O', en: 'H₂O' },
      { ru: 'NaCl', en: 'NaCl' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-5',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая звезда ближе всего к Земле?',
    questionEn: 'What star is closest to Earth?',
    options: [
      { ru: 'Проксима Центавра', en: 'Proxima Centauri' },
      { ru: 'Сириус', en: 'Sirius' },
      { ru: 'Солнце', en: 'The Sun' },
      { ru: 'Полярная звезда', en: 'Polaris' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-6',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'При какой температуре по Цельсию вода закипает?',
    questionEn: 'At what temperature in Celsius does water boil?',
    options: [
      { ru: '90°C', en: '90°C' },
      { ru: '100°C', en: '100°C' },
      { ru: '110°C', en: '110°C' },
      { ru: '80°C', en: '80°C' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-7',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой самый большой орган человеческого тела?',
    questionEn: 'What is the largest organ of the human body?',
    options: [
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Мозг', en: 'Brain' },
      { ru: 'Кожа', en: 'Skin' },
      { ru: 'Лёгкие', en: 'Lungs' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-8',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько планет в Солнечной системе?',
    questionEn: 'How many planets are in the Solar System?',
    options: [
      { ru: '7', en: '7' },
      { ru: '8', en: '8' },
      { ru: '9', en: '9' },
      { ru: '10', en: '10' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-9',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой элемент обозначается символом Fe?',
    questionEn: 'What element has the symbol Fe?',
    options: [
      { ru: 'Фтор', en: 'Fluorine' },
      { ru: 'Железо', en: 'Iron' },
      { ru: 'Свинец', en: 'Lead' },
      { ru: 'Гелий', en: 'Helium' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-10',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется процесс, при котором растения производят кислород?',
    questionEn: 'What is the process by which plants produce oxygen?',
    options: [
      { ru: 'Дыхание', en: 'Respiration' },
      { ru: 'Фотосинтез', en: 'Photosynthesis' },
      { ru: 'Ферментация', en: 'Fermentation' },
      { ru: 'Осмос', en: 'Osmosis' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-11',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая самая большая планета Солнечной системы?',
    questionEn: 'What is the largest planet in the Solar System?',
    options: [
      { ru: 'Сатурн', en: 'Saturn' },
      { ru: 'Нептун', en: 'Neptune' },
      { ru: 'Юпитер', en: 'Jupiter' },
      { ru: 'Уран', en: 'Uranus' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-12',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой газ составляет большую часть атмосферы Земли?',
    questionEn: 'What gas makes up most of Earth\'s atmosphere?',
    options: [
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Углекислый газ', en: 'Carbon dioxide' },
      { ru: 'Азот', en: 'Nitrogen' },
      { ru: 'Аргон', en: 'Argon' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-13',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Что измеряется в герцах?',
    questionEn: 'What is measured in hertz?',
    options: [
      { ru: 'Напряжение', en: 'Voltage' },
      { ru: 'Частота', en: 'Frequency' },
      { ru: 'Сила тока', en: 'Electric current' },
      { ru: 'Давление', en: 'Pressure' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-14',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько хромосом у человека?',
    questionEn: 'How many chromosomes do humans have?',
    options: [
      { ru: '44', en: '44' },
      { ru: '46', en: '46' },
      { ru: '48', en: '48' },
      { ru: '42', en: '42' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-15',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется естественный спутник Земли?',
    questionEn: 'What is the name of Earth\'s natural satellite?',
    options: [
      { ru: 'Фобос', en: 'Phobos' },
      { ru: 'Титан', en: 'Titan' },
      { ru: 'Луна', en: 'The Moon' },
      { ru: 'Европа', en: 'Europa' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-16',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой витамин вырабатывается в коже под воздействием солнечного света?',
    questionEn: 'What vitamin is produced in the skin when exposed to sunlight?',
    options: [
      { ru: 'Витамин A', en: 'Vitamin A' },
      { ru: 'Витамин C', en: 'Vitamin C' },
      { ru: 'Витамин B12', en: 'Vitamin B12' },
      { ru: 'Витамин D', en: 'Vitamin D' },
    ],
    correctIndex: 3,
    timeLimit: 15,
  },
  {
    id: 'sci-17',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какое агрегатное состояние воды — лёд?',
    questionEn: 'What state of matter is ice?',
    options: [
      { ru: 'Жидкое', en: 'Liquid' },
      { ru: 'Газообразное', en: 'Gas' },
      { ru: 'Плазма', en: 'Plasma' },
      { ru: 'Твёрдое', en: 'Solid' },
    ],
    correctIndex: 3,
    timeLimit: 15,
  },

  // === MEDIUM (18-34) ===
  {
    id: 'sci-18',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какова химическая формула серной кислоты?',
    questionEn: 'What is the chemical formula for sulfuric acid?',
    options: [
      { ru: 'HCl', en: 'HCl' },
      { ru: 'H₂SO₄', en: 'H₂SO₄' },
      { ru: 'HNO₃', en: 'HNO₃' },
      { ru: 'H₃PO₄', en: 'H₃PO₄' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-19',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая частица имеет отрицательный электрический заряд?',
    questionEn: 'Which particle has a negative electric charge?',
    options: [
      { ru: 'Протон', en: 'Proton' },
      { ru: 'Нейтрон', en: 'Neutron' },
      { ru: 'Электрон', en: 'Electron' },
      { ru: 'Позитрон', en: 'Positron' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-20',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой закон Ньютона гласит: «Каждое действие имеет равное и противоположное противодействие»?',
    questionEn: 'Which of Newton\'s laws states: "Every action has an equal and opposite reaction"?',
    options: [
      { ru: 'Первый', en: 'First' },
      { ru: 'Второй', en: 'Second' },
      { ru: 'Третий', en: 'Third' },
      { ru: 'Закон всемирного тяготения', en: 'Law of Universal Gravitation' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-21',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой элемент имеет атомный номер 79?',
    questionEn: 'What element has atomic number 79?',
    options: [
      { ru: 'Серебро', en: 'Silver' },
      { ru: 'Платина', en: 'Platinum' },
      { ru: 'Золото', en: 'Gold' },
      { ru: 'Медь', en: 'Copper' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-22',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется единица измерения силы в системе СИ?',
    questionEn: 'What is the SI unit of force?',
    options: [
      { ru: 'Паскаль', en: 'Pascal' },
      { ru: 'Джоуль', en: 'Joule' },
      { ru: 'Ватт', en: 'Watt' },
      { ru: 'Ньютон', en: 'Newton' },
    ],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'sci-23',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип химической связи образуется между атомами натрия и хлора в поваренной соли?',
    questionEn: 'What type of chemical bond forms between sodium and chlorine atoms in table salt?',
    options: [
      { ru: 'Ковалентная', en: 'Covalent' },
      { ru: 'Ионная', en: 'Ionic' },
      { ru: 'Металлическая', en: 'Metallic' },
      { ru: 'Водородная', en: 'Hydrogen' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-24',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая структура клетки содержит ДНК?',
    questionEn: 'Which cell structure contains DNA?',
    options: [
      { ru: 'Рибосома', en: 'Ribosome' },
      { ru: 'Ядро', en: 'Nucleus' },
      { ru: 'Клеточная мембрана', en: 'Cell membrane' },
      { ru: 'Аппарат Гольджи', en: 'Golgi apparatus' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-25',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какова скорость света в вакууме (приблизительно)?',
    questionEn: 'What is the speed of light in a vacuum (approximately)?',
    options: [
      { ru: '300 000 км/с', en: '300,000 km/s' },
      { ru: '150 000 км/с', en: '150,000 km/s' },
      { ru: '500 000 км/с', en: '500,000 km/s' },
      { ru: '100 000 км/с', en: '100,000 km/s' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'sci-26',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой процесс описывает превращение жидкости в газ?',
    questionEn: 'What process describes the conversion of a liquid into a gas?',
    options: [
      { ru: 'Конденсация', en: 'Condensation' },
      { ru: 'Сублимация', en: 'Sublimation' },
      { ru: 'Испарение', en: 'Evaporation' },
      { ru: 'Кристаллизация', en: 'Crystallization' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-27',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой учёный сформулировал теорию относительности?',
    questionEn: 'Which scientist formulated the theory of relativity?',
    options: [
      { ru: 'Исаак Ньютон', en: 'Isaac Newton' },
      { ru: 'Нильс Бор', en: 'Niels Bohr' },
      { ru: 'Альберт Эйнштейн', en: 'Albert Einstein' },
      { ru: 'Макс Планк', en: 'Max Planck' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-28',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Что такое pH нейтрального раствора?',
    questionEn: 'What is the pH of a neutral solution?',
    options: [
      { ru: '0', en: '0' },
      { ru: '7', en: '7' },
      { ru: '14', en: '14' },
      { ru: '1', en: '1' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-29',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой орган вырабатывает инсулин?',
    questionEn: 'Which organ produces insulin?',
    options: [
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Поджелудочная железа', en: 'Pancreas' },
      { ru: 'Почки', en: 'Kidneys' },
      { ru: 'Щитовидная железа', en: 'Thyroid gland' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-30',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется самый твёрдый природный минерал?',
    questionEn: 'What is the hardest naturally occurring mineral?',
    options: [
      { ru: 'Кварц', en: 'Quartz' },
      { ru: 'Корунд', en: 'Corundum' },
      { ru: 'Алмаз', en: 'Diamond' },
      { ru: 'Топаз', en: 'Topaz' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-31',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип излучения имеет наибольшую длину волны?',
    questionEn: 'Which type of radiation has the longest wavelength?',
    options: [
      { ru: 'Гамма-лучи', en: 'Gamma rays' },
      { ru: 'Рентгеновские лучи', en: 'X-rays' },
      { ru: 'Радиоволны', en: 'Radio waves' },
      { ru: 'Ультрафиолет', en: 'Ultraviolet' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-32',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая кислота содержится в желудочном соке человека?',
    questionEn: 'What acid is found in the human stomach?',
    options: [
      { ru: 'Серная кислота', en: 'Sulfuric acid' },
      { ru: 'Уксусная кислота', en: 'Acetic acid' },
      { ru: 'Соляная кислота', en: 'Hydrochloric acid' },
      { ru: 'Азотная кислота', en: 'Nitric acid' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-33',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какое число является значением числа Пи (π) с точностью до двух знаков после запятой?',
    questionEn: 'What is the value of Pi (π) to two decimal places?',
    options: [
      { ru: '3,12', en: '3.12' },
      { ru: '3,14', en: '3.14' },
      { ru: '3,16', en: '3.16' },
      { ru: '3,18', en: '3.18' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-34',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой слой атмосферы Земли защищает от ультрафиолетового излучения?',
    questionEn: 'Which layer of Earth\'s atmosphere protects against ultraviolet radiation?',
    options: [
      { ru: 'Тропосфера', en: 'Troposphere' },
      { ru: 'Стратосфера (озоновый слой)', en: 'Stratosphere (ozone layer)' },
      { ru: 'Мезосфера', en: 'Mesosphere' },
      { ru: 'Термосфера', en: 'Thermosphere' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },

  // === HARD (35-50) ===
  {
    id: 'sci-35',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что такое радиус Шварцшильда?',
    questionEn: 'What is the Schwarzschild radius?',
    options: [
      { ru: 'Радиус орбиты электрона в атоме водорода', en: 'The orbital radius of an electron in a hydrogen atom' },
      { ru: 'Радиус, при котором объект становится чёрной дырой', en: 'The radius at which an object becomes a black hole' },
      { ru: 'Минимальный радиус нейтронной звезды', en: 'The minimum radius of a neutron star' },
      { ru: 'Максимальный радиус белого карлика', en: 'The maximum radius of a white dwarf' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-36',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой принцип квантовой механики утверждает, что невозможно одновременно точно измерить положение и импульс частицы?',
    questionEn: 'Which principle of quantum mechanics states that it is impossible to simultaneously measure the exact position and momentum of a particle?',
    options: [
      { ru: 'Принцип Паули', en: 'Pauli exclusion principle' },
      { ru: 'Принцип неопределённости Гейзенберга', en: 'Heisenberg uncertainty principle' },
      { ru: 'Принцип суперпозиции', en: 'Superposition principle' },
      { ru: 'Принцип дополнительности Бора', en: 'Bohr complementarity principle' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-37',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая постоянная определяет связь между энергией фотона и его частотой?',
    questionEn: 'What constant defines the relationship between a photon\'s energy and its frequency?',
    options: [
      { ru: 'Постоянная Больцмана', en: 'Boltzmann constant' },
      { ru: 'Гравитационная постоянная', en: 'Gravitational constant' },
      { ru: 'Постоянная Планка', en: 'Planck constant' },
      { ru: 'Постоянная Авогадро', en: 'Avogadro constant' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-38',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой процесс обеспечивает энергией звёзды, подобные Солнцу?',
    questionEn: 'What process provides energy to stars like the Sun?',
    options: [
      { ru: 'Ядерное деление', en: 'Nuclear fission' },
      { ru: 'Химическое горение', en: 'Chemical combustion' },
      { ru: 'Термоядерный синтез', en: 'Nuclear fusion' },
      { ru: 'Радиоактивный распад', en: 'Radioactive decay' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-39',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что описывает уравнение Шрёдингера?',
    questionEn: 'What does the Schrödinger equation describe?',
    options: [
      { ru: 'Движение планет', en: 'Planetary motion' },
      { ru: 'Эволюцию волновой функции квантовой системы', en: 'The evolution of the wave function of a quantum system' },
      { ru: 'Электромагнитное излучение', en: 'Electromagnetic radiation' },
      { ru: 'Термодинамическое равновесие', en: 'Thermodynamic equilibrium' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-40',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой элемент является самым тяжёлым стабильным элементом в таблице Менделеева?',
    questionEn: 'What is the heaviest stable element in the periodic table?',
    options: [
      { ru: 'Уран', en: 'Uranium' },
      { ru: 'Свинец', en: 'Lead' },
      { ru: 'Висмут', en: 'Bismuth' },
      { ru: 'Золото', en: 'Gold' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-41',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой тип РНК переносит аминокислоты к рибосоме во время синтеза белка?',
    questionEn: 'What type of RNA carries amino acids to the ribosome during protein synthesis?',
    options: [
      { ru: 'мРНК (матричная)', en: 'mRNA (messenger)' },
      { ru: 'тРНК (транспортная)', en: 'tRNA (transfer)' },
      { ru: 'рРНК (рибосомная)', en: 'rRNA (ribosomal)' },
      { ru: 'миРНК (микро)', en: 'miRNA (micro)' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-42',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Как называется явление искривления пространства-времени вблизи массивных объектов?',
    questionEn: 'What is the phenomenon of spacetime curvature near massive objects called?',
    options: [
      { ru: 'Специальная относительность', en: 'Special relativity' },
      { ru: 'Гравитационное линзирование', en: 'Gravitational lensing' },
      { ru: 'Общая теория относительности', en: 'General relativity' },
      { ru: 'Квантовая гравитация', en: 'Quantum gravity' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-43',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой фермент отвечает за раскручивание двойной спирали ДНК при репликации?',
    questionEn: 'Which enzyme is responsible for unwinding the DNA double helix during replication?',
    options: [
      { ru: 'ДНК-полимераза', en: 'DNA polymerase' },
      { ru: 'ДНК-лигаза', en: 'DNA ligase' },
      { ru: 'Геликаза', en: 'Helicase' },
      { ru: 'Праймаза', en: 'Primase' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-44',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая теорема утверждает, что каждому непрерывному симметрию соответствует закон сохранения?',
    questionEn: 'Which theorem states that every continuous symmetry corresponds to a conservation law?',
    options: [
      { ru: 'Теорема Нётер', en: 'Noether\'s theorem' },
      { ru: 'Теорема Гёделя', en: 'Gödel\'s theorem' },
      { ru: 'Теорема Белла', en: 'Bell\'s theorem' },
      { ru: 'Теорема Ферма', en: 'Fermat\'s theorem' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'sci-45',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что такое бозон Хиггса?',
    questionEn: 'What is the Higgs boson?',
    options: [
      { ru: 'Частица, переносящая электромагнитное взаимодействие', en: 'A particle carrying the electromagnetic interaction' },
      { ru: 'Частица, придающая массу другим элементарным частицам', en: 'A particle that gives mass to other elementary particles' },
      { ru: 'Частица тёмной материи', en: 'A dark matter particle' },
      { ru: 'Частица, переносящая сильное взаимодействие', en: 'A particle carrying the strong interaction' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-46',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой предел определяет максимальную массу белого карлика?',
    questionEn: 'What limit determines the maximum mass of a white dwarf?',
    options: [
      { ru: 'Предел Роша', en: 'Roche limit' },
      { ru: 'Предел Чандрасекара', en: 'Chandrasekhar limit' },
      { ru: 'Предел Эддингтона', en: 'Eddington limit' },
      { ru: 'Предел Оппенгеймера — Волкова', en: 'Oppenheimer–Volkoff limit' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-47',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой цикл описывает превращение углерода в энергию в массивных звёздах?',
    questionEn: 'What cycle describes the conversion of carbon into energy in massive stars?',
    options: [
      { ru: 'Протон-протонный цикл', en: 'Proton-proton chain' },
      { ru: 'Цикл Кребса', en: 'Krebs cycle' },
      { ru: 'CNO-цикл', en: 'CNO cycle' },
      { ru: 'Цикл Карно', en: 'Carnot cycle' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-48',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какое явление объясняет, почему электроны не могут занимать одинаковое квантовое состояние?',
    questionEn: 'What phenomenon explains why electrons cannot occupy the same quantum state?',
    options: [
      { ru: 'Эффект туннелирования', en: 'Tunneling effect' },
      { ru: 'Принцип запрета Паули', en: 'Pauli exclusion principle' },
      { ru: 'Принцип неопределённости', en: 'Uncertainty principle' },
      { ru: 'Эффект Комптона', en: 'Compton effect' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-49',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой метод датировки используется для определения возраста горных пород возрастом в миллиарды лет?',
    questionEn: 'What dating method is used to determine the age of rocks that are billions of years old?',
    options: [
      { ru: 'Радиоуглеродный анализ', en: 'Radiocarbon dating' },
      { ru: 'Уран-свинцовый метод', en: 'Uranium-lead dating' },
      { ru: 'Дендрохронология', en: 'Dendrochronology' },
      { ru: 'Термолюминесценция', en: 'Thermoluminescence' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-50',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая частица является переносчиком сильного ядерного взаимодействия?',
    questionEn: 'What particle is the carrier of the strong nuclear force?',
    options: [
      { ru: 'Фотон', en: 'Photon' },
      { ru: 'W-бозон', en: 'W boson' },
      { ru: 'Гравитон', en: 'Graviton' },
      { ru: 'Глюон', en: 'Gluon' },
    ],
    correctIndex: 3,
    timeLimit: 25,
  },
];
