import { QuizQuestion } from '@/types/game';

export const SCIENCE_QUESTIONS: QuizQuestion[] = [
  // === EASY (1-17) ===
  {
    id: 'sci-1',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая планета ближе всего к Солнцу?',
    questionEn: 'What planet is closest to the Sun?',
    options: [
      { ru: 'Венера', en: 'Venus' },
      { ru: 'Меркурий', en: 'Mercury' },
      { ru: 'Марс', en: 'Mars' },
      { ru: 'Земля', en: 'Earth' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-2',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой газ необходим для дыхания человека?',
    questionEn: 'What gas is essential for human breathing?',
    options: [
      { ru: 'Углекислый газ', en: 'Carbon dioxide' },
      { ru: 'Азот', en: 'Nitrogen' },
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Водород', en: 'Hydrogen' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-3',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько костей в теле взрослого человека?',
    questionEn: 'How many bones are in an adult human body?',
    options: [
      { ru: '206', en: '206' },
      { ru: '300', en: '300' },
      { ru: '150', en: '150' },
      { ru: '180', en: '180' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'sci-4',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой химический символ у воды?',
    questionEn: 'What is the chemical formula for water?',
    options: [
      { ru: 'CO₂', en: 'CO₂' },
      { ru: 'O₂', en: 'O₂' },
      { ru: 'H₂O', en: 'H₂O' },
      { ru: 'NaCl', en: 'NaCl' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-5',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая звезда ближе всего к Земле?',
    questionEn: 'What star is closest to Earth?',
    options: [
      { ru: 'Проксима Центавра', en: 'Proxima Centauri' },
      { ru: 'Сириус', en: 'Sirius' },
      { ru: 'Солнце', en: 'The Sun' },
      { ru: 'Полярная звезда', en: 'Polaris' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-6',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'При какой температуре по Цельсию вода закипает?',
    questionEn: 'At what temperature in Celsius does water boil?',
    options: [
      { ru: '90°C', en: '90°C' },
      { ru: '100°C', en: '100°C' },
      { ru: '110°C', en: '110°C' },
      { ru: '80°C', en: '80°C' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-7',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой самый большой орган человеческого тела?',
    questionEn: 'What is the largest organ of the human body?',
    options: [
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Мозг', en: 'Brain' },
      { ru: 'Кожа', en: 'Skin' },
      { ru: 'Лёгкие', en: 'Lungs' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-8',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько планет в Солнечной системе?',
    questionEn: 'How many planets are in the Solar System?',
    options: [
      { ru: '7', en: '7' },
      { ru: '8', en: '8' },
      { ru: '9', en: '9' },
      { ru: '10', en: '10' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-9',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой элемент обозначается символом Fe?',
    questionEn: 'What element has the symbol Fe?',
    options: [
      { ru: 'Фтор', en: 'Fluorine' },
      { ru: 'Железо', en: 'Iron' },
      { ru: 'Свинец', en: 'Lead' },
      { ru: 'Гелий', en: 'Helium' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-10',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется процесс, при котором растения производят кислород?',
    questionEn: 'What is the process by which plants produce oxygen?',
    options: [
      { ru: 'Дыхание', en: 'Respiration' },
      { ru: 'Фотосинтез', en: 'Photosynthesis' },
      { ru: 'Ферментация', en: 'Fermentation' },
      { ru: 'Осмос', en: 'Osmosis' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-11',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая самая большая планета Солнечной системы?',
    questionEn: 'What is the largest planet in the Solar System?',
    options: [
      { ru: 'Сатурн', en: 'Saturn' },
      { ru: 'Нептун', en: 'Neptune' },
      { ru: 'Юпитер', en: 'Jupiter' },
      { ru: 'Уран', en: 'Uranus' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-12',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой газ составляет большую часть атмосферы Земли?',
    questionEn: 'What gas makes up most of Earth\'s atmosphere?',
    options: [
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Углекислый газ', en: 'Carbon dioxide' },
      { ru: 'Азот', en: 'Nitrogen' },
      { ru: 'Аргон', en: 'Argon' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-13',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Что измеряется в герцах?',
    questionEn: 'What is measured in hertz?',
    options: [
      { ru: 'Напряжение', en: 'Voltage' },
      { ru: 'Частота', en: 'Frequency' },
      { ru: 'Сила тока', en: 'Electric current' },
      { ru: 'Давление', en: 'Pressure' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-14',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько хромосом у человека?',
    questionEn: 'How many chromosomes do humans have?',
    options: [
      { ru: '44', en: '44' },
      { ru: '46', en: '46' },
      { ru: '48', en: '48' },
      { ru: '42', en: '42' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-15',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется естественный спутник Земли?',
    questionEn: 'What is the name of Earth\'s natural satellite?',
    options: [
      { ru: 'Фобос', en: 'Phobos' },
      { ru: 'Титан', en: 'Titan' },
      { ru: 'Луна', en: 'The Moon' },
      { ru: 'Европа', en: 'Europa' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-16',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой витамин вырабатывается в коже под воздействием солнечного света?',
    questionEn: 'What vitamin is produced in the skin when exposed to sunlight?',
    options: [
      { ru: 'Витамин A', en: 'Vitamin A' },
      { ru: 'Витамин C', en: 'Vitamin C' },
      { ru: 'Витамин B12', en: 'Vitamin B12' },
      { ru: 'Витамин D', en: 'Vitamin D' },
    ],
    correctIndex: 3,
    timeLimit: 15,
  },
  {
    id: 'sci-17',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какое агрегатное состояние воды — лёд?',
    questionEn: 'What state of matter is ice?',
    options: [
      { ru: 'Жидкое', en: 'Liquid' },
      { ru: 'Газообразное', en: 'Gas' },
      { ru: 'Плазма', en: 'Plasma' },
      { ru: 'Твёрдое', en: 'Solid' },
    ],
    correctIndex: 3,
    timeLimit: 15,
  },

  // === MEDIUM (18-34) ===
  {
    id: 'sci-18',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какова химическая формула серной кислоты?',
    questionEn: 'What is the chemical formula for sulfuric acid?',
    options: [
      { ru: 'HCl', en: 'HCl' },
      { ru: 'H₂SO₄', en: 'H₂SO₄' },
      { ru: 'HNO₃', en: 'HNO₃' },
      { ru: 'H₃PO₄', en: 'H₃PO₄' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-19',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая частица имеет отрицательный электрический заряд?',
    questionEn: 'Which particle has a negative electric charge?',
    options: [
      { ru: 'Протон', en: 'Proton' },
      { ru: 'Нейтрон', en: 'Neutron' },
      { ru: 'Электрон', en: 'Electron' },
      { ru: 'Позитрон', en: 'Positron' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-20',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой закон Ньютона гласит: «Каждое действие имеет равное и противоположное противодействие»?',
    questionEn: 'Which of Newton\'s laws states: "Every action has an equal and opposite reaction"?',
    options: [
      { ru: 'Первый', en: 'First' },
      { ru: 'Второй', en: 'Second' },
      { ru: 'Третий', en: 'Third' },
      { ru: 'Закон всемирного тяготения', en: 'Law of Universal Gravitation' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-21',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой элемент имеет атомный номер 79?',
    questionEn: 'What element has atomic number 79?',
    options: [
      { ru: 'Серебро', en: 'Silver' },
      { ru: 'Платина', en: 'Platinum' },
      { ru: 'Золото', en: 'Gold' },
      { ru: 'Медь', en: 'Copper' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-22',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется единица измерения силы в системе СИ?',
    questionEn: 'What is the SI unit of force?',
    options: [
      { ru: 'Паскаль', en: 'Pascal' },
      { ru: 'Джоуль', en: 'Joule' },
      { ru: 'Ватт', en: 'Watt' },
      { ru: 'Ньютон', en: 'Newton' },
    ],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'sci-23',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип химической связи образуется между атомами натрия и хлора в поваренной соли?',
    questionEn: 'What type of chemical bond forms between sodium and chlorine atoms in table salt?',
    options: [
      { ru: 'Ковалентная', en: 'Covalent' },
      { ru: 'Ионная', en: 'Ionic' },
      { ru: 'Металлическая', en: 'Metallic' },
      { ru: 'Водородная', en: 'Hydrogen' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-24',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая структура клетки содержит ДНК?',
    questionEn: 'Which cell structure contains DNA?',
    options: [
      { ru: 'Рибосома', en: 'Ribosome' },
      { ru: 'Ядро', en: 'Nucleus' },
      { ru: 'Клеточная мембрана', en: 'Cell membrane' },
      { ru: 'Аппарат Гольджи', en: 'Golgi apparatus' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-25',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какова скорость света в вакууме (приблизительно)?',
    questionEn: 'What is the speed of light in a vacuum (approximately)?',
    options: [
      { ru: '300 000 км/с', en: '300,000 km/s' },
      { ru: '150 000 км/с', en: '150,000 km/s' },
      { ru: '500 000 км/с', en: '500,000 km/s' },
      { ru: '100 000 км/с', en: '100,000 km/s' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'sci-26',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой процесс описывает превращение жидкости в газ?',
    questionEn: 'What process describes the conversion of a liquid into a gas?',
    options: [
      { ru: 'Конденсация', en: 'Condensation' },
      { ru: 'Сублимация', en: 'Sublimation' },
      { ru: 'Испарение', en: 'Evaporation' },
      { ru: 'Кристаллизация', en: 'Crystallization' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-27',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой учёный сформулировал теорию относительности?',
    questionEn: 'Which scientist formulated the theory of relativity?',
    options: [
      { ru: 'Исаак Ньютон', en: 'Isaac Newton' },
      { ru: 'Нильс Бор', en: 'Niels Bohr' },
      { ru: 'Альберт Эйнштейн', en: 'Albert Einstein' },
      { ru: 'Макс Планк', en: 'Max Planck' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-28',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Что такое pH нейтрального раствора?',
    questionEn: 'What is the pH of a neutral solution?',
    options: [
      { ru: '0', en: '0' },
      { ru: '7', en: '7' },
      { ru: '14', en: '14' },
      { ru: '1', en: '1' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-29',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой орган вырабатывает инсулин?',
    questionEn: 'Which organ produces insulin?',
    options: [
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Поджелудочная железа', en: 'Pancreas' },
      { ru: 'Почки', en: 'Kidneys' },
      { ru: 'Щитовидная железа', en: 'Thyroid gland' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-30',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется самый твёрдый природный минерал?',
    questionEn: 'What is the hardest naturally occurring mineral?',
    options: [
      { ru: 'Кварц', en: 'Quartz' },
      { ru: 'Корунд', en: 'Corundum' },
      { ru: 'Алмаз', en: 'Diamond' },
      { ru: 'Топаз', en: 'Topaz' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-31',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип излучения имеет наибольшую длину волны?',
    questionEn: 'Which type of radiation has the longest wavelength?',
    options: [
      { ru: 'Гамма-лучи', en: 'Gamma rays' },
      { ru: 'Рентгеновские лучи', en: 'X-rays' },
      { ru: 'Радиоволны', en: 'Radio waves' },
      { ru: 'Ультрафиолет', en: 'Ultraviolet' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-32',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая кислота содержится в желудочном соке человека?',
    questionEn: 'What acid is found in the human stomach?',
    options: [
      { ru: 'Серная кислота', en: 'Sulfuric acid' },
      { ru: 'Уксусная кислота', en: 'Acetic acid' },
      { ru: 'Соляная кислота', en: 'Hydrochloric acid' },
      { ru: 'Азотная кислота', en: 'Nitric acid' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-33',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какое число является значением числа Пи (π) с точностью до двух знаков после запятой?',
    questionEn: 'What is the value of Pi (π) to two decimal places?',
    options: [
      { ru: '3,12', en: '3.12' },
      { ru: '3,14', en: '3.14' },
      { ru: '3,16', en: '3.16' },
      { ru: '3,18', en: '3.18' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-34',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой слой атмосферы Земли защищает от ультрафиолетового излучения?',
    questionEn: 'Which layer of Earth\'s atmosphere protects against ultraviolet radiation?',
    options: [
      { ru: 'Тропосфера', en: 'Troposphere' },
      { ru: 'Стратосфера (озоновый слой)', en: 'Stratosphere (ozone layer)' },
      { ru: 'Мезосфера', en: 'Mesosphere' },
      { ru: 'Термосфера', en: 'Thermosphere' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },

  // === HARD (35-50) ===
  {
    id: 'sci-35',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что такое радиус Шварцшильда?',
    questionEn: 'What is the Schwarzschild radius?',
    options: [
      { ru: 'Радиус орбиты электрона в атоме водорода', en: 'The orbital radius of an electron in a hydrogen atom' },
      { ru: 'Радиус, при котором объект становится чёрной дырой', en: 'The radius at which an object becomes a black hole' },
      { ru: 'Минимальный радиус нейтронной звезды', en: 'The minimum radius of a neutron star' },
      { ru: 'Максимальный радиус белого карлика', en: 'The maximum radius of a white dwarf' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-36',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой принцип квантовой механики утверждает, что невозможно одновременно точно измерить положение и импульс частицы?',
    questionEn: 'Which principle of quantum mechanics states that it is impossible to simultaneously measure the exact position and momentum of a particle?',
    options: [
      { ru: 'Принцип Паули', en: 'Pauli exclusion principle' },
      { ru: 'Принцип неопределённости Гейзенберга', en: 'Heisenberg uncertainty principle' },
      { ru: 'Принцип суперпозиции', en: 'Superposition principle' },
      { ru: 'Принцип дополнительности Бора', en: 'Bohr complementarity principle' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-37',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая постоянная определяет связь между энергией фотона и его частотой?',
    questionEn: 'What constant defines the relationship between a photon\'s energy and its frequency?',
    options: [
      { ru: 'Постоянная Больцмана', en: 'Boltzmann constant' },
      { ru: 'Гравитационная постоянная', en: 'Gravitational constant' },
      { ru: 'Постоянная Планка', en: 'Planck constant' },
      { ru: 'Постоянная Авогадро', en: 'Avogadro constant' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-38',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой процесс обеспечивает энергией звёзды, подобные Солнцу?',
    questionEn: 'What process provides energy to stars like the Sun?',
    options: [
      { ru: 'Ядерное деление', en: 'Nuclear fission' },
      { ru: 'Химическое горение', en: 'Chemical combustion' },
      { ru: 'Термоядерный синтез', en: 'Nuclear fusion' },
      { ru: 'Радиоактивный распад', en: 'Radioactive decay' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-39',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что описывает уравнение Шрёдингера?',
    questionEn: 'What does the Schrödinger equation describe?',
    options: [
      { ru: 'Движение планет', en: 'Planetary motion' },
      { ru: 'Эволюцию волновой функции квантовой системы', en: 'The evolution of the wave function of a quantum system' },
      { ru: 'Электромагнитное излучение', en: 'Electromagnetic radiation' },
      { ru: 'Термодинамическое равновесие', en: 'Thermodynamic equilibrium' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-40',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой элемент является самым тяжёлым стабильным элементом в таблице Менделеева?',
    questionEn: 'What is the heaviest stable element in the periodic table?',
    options: [
      { ru: 'Уран', en: 'Uranium' },
      { ru: 'Свинец', en: 'Lead' },
      { ru: 'Висмут', en: 'Bismuth' },
      { ru: 'Золото', en: 'Gold' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-41',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой тип РНК переносит аминокислоты к рибосоме во время синтеза белка?',
    questionEn: 'What type of RNA carries amino acids to the ribosome during protein synthesis?',
    options: [
      { ru: 'мРНК (матричная)', en: 'mRNA (messenger)' },
      { ru: 'тРНК (транспортная)', en: 'tRNA (transfer)' },
      { ru: 'рРНК (рибосомная)', en: 'rRNA (ribosomal)' },
      { ru: 'миРНК (микро)', en: 'miRNA (micro)' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-42',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Как называется явление искривления пространства-времени вблизи массивных объектов?',
    questionEn: 'What is the phenomenon of spacetime curvature near massive objects called?',
    options: [
      { ru: 'Специальная относительность', en: 'Special relativity' },
      { ru: 'Гравитационное линзирование', en: 'Gravitational lensing' },
      { ru: 'Общая теория относительности', en: 'General relativity' },
      { ru: 'Квантовая гравитация', en: 'Quantum gravity' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-43',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой фермент отвечает за раскручивание двойной спирали ДНК при репликации?',
    questionEn: 'Which enzyme is responsible for unwinding the DNA double helix during replication?',
    options: [
      { ru: 'ДНК-полимераза', en: 'DNA polymerase' },
      { ru: 'ДНК-лигаза', en: 'DNA ligase' },
      { ru: 'Геликаза', en: 'Helicase' },
      { ru: 'Праймаза', en: 'Primase' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-44',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая теорема утверждает, что каждому непрерывному симметрию соответствует закон сохранения?',
    questionEn: 'Which theorem states that every continuous symmetry corresponds to a conservation law?',
    options: [
      { ru: 'Теорема Нётер', en: 'Noether\'s theorem' },
      { ru: 'Теорема Гёделя', en: 'Gödel\'s theorem' },
      { ru: 'Теорема Белла', en: 'Bell\'s theorem' },
      { ru: 'Теорема Ферма', en: 'Fermat\'s theorem' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'sci-45',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что такое бозон Хиггса?',
    questionEn: 'What is the Higgs boson?',
    options: [
      { ru: 'Частица, переносящая электромагнитное взаимодействие', en: 'A particle carrying the electromagnetic interaction' },
      { ru: 'Частица, придающая массу другим элементарным частицам', en: 'A particle that gives mass to other elementary particles' },
      { ru: 'Частица тёмной материи', en: 'A dark matter particle' },
      { ru: 'Частица, переносящая сильное взаимодействие', en: 'A particle carrying the strong interaction' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-46',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой предел определяет максимальную массу белого карлика?',
    questionEn: 'What limit determines the maximum mass of a white dwarf?',
    options: [
      { ru: 'Предел Роша', en: 'Roche limit' },
      { ru: 'Предел Чандрасекара', en: 'Chandrasekhar limit' },
      { ru: 'Предел Эддингтона', en: 'Eddington limit' },
      { ru: 'Предел Оппенгеймера — Волкова', en: 'Oppenheimer–Volkoff limit' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-47',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой цикл описывает превращение углерода в энергию в массивных звёздах?',
    questionEn: 'What cycle describes the conversion of carbon into energy in massive stars?',
    options: [
      { ru: 'Протон-протонный цикл', en: 'Proton-proton chain' },
      { ru: 'Цикл Кребса', en: 'Krebs cycle' },
      { ru: 'CNO-цикл', en: 'CNO cycle' },
      { ru: 'Цикл Карно', en: 'Carnot cycle' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-48',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какое явление объясняет, почему электроны не могут занимать одинаковое квантовое состояние?',
    questionEn: 'What phenomenon explains why electrons cannot occupy the same quantum state?',
    options: [
      { ru: 'Эффект туннелирования', en: 'Tunneling effect' },
      { ru: 'Принцип запрета Паули', en: 'Pauli exclusion principle' },
      { ru: 'Принцип неопределённости', en: 'Uncertainty principle' },
      { ru: 'Эффект Комптона', en: 'Compton effect' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-49',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой метод датировки используется для определения возраста горных пород возрастом в миллиарды лет?',
    questionEn: 'What dating method is used to determine the age of rocks that are billions of years old?',
    options: [
      { ru: 'Радиоуглеродный анализ', en: 'Radiocarbon dating' },
      { ru: 'Уран-свинцовый метод', en: 'Uranium-lead dating' },
      { ru: 'Дендрохронология', en: 'Dendrochronology' },
      { ru: 'Термолюминесценция', en: 'Thermoluminescence' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-50',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая частица является переносчиком сильного ядерного взаимодействия?',
    questionEn: 'What particle is the carrier of the strong nuclear force?',
    options: [
      { ru: 'Фотон', en: 'Photon' },
      { ru: 'W-бозон', en: 'W boson' },
      { ru: 'Гравитон', en: 'Graviton' },
      { ru: 'Глюон', en: 'Gluon' },
    ],
    correctIndex: 3,
    timeLimit: 25,
  },

  // ============================================================
  // === BATCH 2 — EASY (51-67) ===
  // ============================================================
  {
    id: 'sci-51',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой металл является жидким при комнатной температуре?',
    questionEn: 'What metal is liquid at room temperature?',
    options: [
      { ru: 'Свинец', en: 'Lead' },
      { ru: 'Ртуть', en: 'Mercury' },
      { ru: 'Алюминий', en: 'Aluminum' },
      { ru: 'Олово', en: 'Tin' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-52',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько планет в Солнечной системе?',
    questionEn: 'How many planets are in the Solar System?',
    options: [
      { ru: '7', en: '7' },
      { ru: '8', en: '8' },
      { ru: '9', en: '9' },
      { ru: '10', en: '10' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-53',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется процесс, при котором растения производят кислород?',
    questionEn: 'What is the process by which plants produce oxygen?',
    options: [
      { ru: 'Дыхание', en: 'Respiration' },
      { ru: 'Фотосинтез', en: 'Photosynthesis' },
      { ru: 'Испарение', en: 'Evaporation' },
      { ru: 'Брожение', en: 'Fermentation' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-54',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая часть клетки содержит ДНК?',
    questionEn: 'What part of the cell contains DNA?',
    options: [
      { ru: 'Мембрана', en: 'Membrane' },
      { ru: 'Цитоплазма', en: 'Cytoplasm' },
      { ru: 'Ядро', en: 'Nucleus' },
      { ru: 'Рибосома', en: 'Ribosome' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-55',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какое животное является самым большим на Земле?',
    questionEn: 'What is the largest animal on Earth?',
    options: [
      { ru: 'Африканский слон', en: 'African elephant' },
      { ru: 'Голубой кит', en: 'Blue whale' },
      { ru: 'Жираф', en: 'Giraffe' },
      { ru: 'Китовая акула', en: 'Whale shark' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-56',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Из чего состоит молекула поваренной соли?',
    questionEn: 'What is table salt made of?',
    options: [
      { ru: 'Калий и хлор', en: 'Potassium and chlorine' },
      { ru: 'Натрий и хлор', en: 'Sodium and chlorine' },
      { ru: 'Кальций и хлор', en: 'Calcium and chlorine' },
      { ru: 'Натрий и фтор', en: 'Sodium and fluorine' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-57',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой витамин вырабатывается в коже под действием солнца?',
    questionEn: 'What vitamin is produced in the skin by sunlight?',
    options: [
      { ru: 'Витамин A', en: 'Vitamin A' },
      { ru: 'Витамин C', en: 'Vitamin C' },
      { ru: 'Витамин D', en: 'Vitamin D' },
      { ru: 'Витамин B12', en: 'Vitamin B12' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-58',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой газ составляет большую часть атмосферы Земли?',
    questionEn: 'What gas makes up most of Earth\'s atmosphere?',
    options: [
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Углекислый газ', en: 'Carbon dioxide' },
      { ru: 'Азот', en: 'Nitrogen' },
      { ru: 'Аргон', en: 'Argon' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-59',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Сколько хромосом в клетке человека?',
    questionEn: 'How many chromosomes are in a human cell?',
    options: [
      { ru: '23', en: '23' },
      { ru: '46', en: '46' },
      { ru: '44', en: '44' },
      { ru: '48', en: '48' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-60',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется единица измерения силы тока?',
    questionEn: 'What is the unit of electric current?',
    options: [
      { ru: 'Вольт', en: 'Volt' },
      { ru: 'Ватт', en: 'Watt' },
      { ru: 'Ампер', en: 'Ampere' },
      { ru: 'Ом', en: 'Ohm' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-61',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой орган отвечает за очистку крови в организме?',
    questionEn: 'What organ is responsible for filtering blood?',
    options: [
      { ru: 'Лёгкие', en: 'Lungs' },
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Почки', en: 'Kidneys' },
      { ru: 'Сердце', en: 'Heart' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-62',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какое состояние воды — пар?',
    questionEn: 'What state of matter is steam?',
    options: [
      { ru: 'Твёрдое', en: 'Solid' },
      { ru: 'Жидкое', en: 'Liquid' },
      { ru: 'Газообразное', en: 'Gas' },
      { ru: 'Плазма', en: 'Plasma' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-63',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая кровяная группа считается универсальным донором?',
    questionEn: 'Which blood type is the universal donor?',
    options: [
      { ru: 'I (O)', en: 'O' },
      { ru: 'II (A)', en: 'A' },
      { ru: 'III (B)', en: 'B' },
      { ru: 'IV (AB)', en: 'AB' },
    ],
    correctIndex: 0,
    timeLimit: 15,
  },
  {
    id: 'sci-64',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Что измеряет термометр?',
    questionEn: 'What does a thermometer measure?',
    options: [
      { ru: 'Давление', en: 'Pressure' },
      { ru: 'Температуру', en: 'Temperature' },
      { ru: 'Влажность', en: 'Humidity' },
      { ru: 'Скорость ветра', en: 'Wind speed' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-65',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какой элемент обозначается символом Fe?',
    questionEn: 'What element is represented by the symbol Fe?',
    options: [
      { ru: 'Фтор', en: 'Fluorine' },
      { ru: 'Железо', en: 'Iron' },
      { ru: 'Франций', en: 'Francium' },
      { ru: 'Фосфор', en: 'Phosphorus' },
    ],
    correctIndex: 1,
    timeLimit: 15,
  },
  {
    id: 'sci-66',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Какая система органов отвечает за переваривание пищи?',
    questionEn: 'Which organ system is responsible for digesting food?',
    options: [
      { ru: 'Нервная', en: 'Nervous' },
      { ru: 'Дыхательная', en: 'Respiratory' },
      { ru: 'Пищеварительная', en: 'Digestive' },
      { ru: 'Кровеносная', en: 'Circulatory' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },
  {
    id: 'sci-67',
    topic: 'science',
    difficulty: 'easy',
    questionRu: 'Как называется спутник Земли?',
    questionEn: 'What is the name of Earth\'s natural satellite?',
    options: [
      { ru: 'Фобос', en: 'Phobos' },
      { ru: 'Титан', en: 'Titan' },
      { ru: 'Луна', en: 'Moon' },
      { ru: 'Европа', en: 'Europa' },
    ],
    correctIndex: 2,
    timeLimit: 15,
  },

  // ============================================================
  // === BATCH 2 — MEDIUM (68-84) ===
  // ============================================================
  {
    id: 'sci-68',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой закон физики гласит, что каждое действие вызывает равное противодействие?',
    questionEn: 'Which law of physics states that every action has an equal and opposite reaction?',
    options: [
      { ru: 'Первый закон Ньютона', en: 'Newton\'s first law' },
      { ru: 'Второй закон Ньютона', en: 'Newton\'s second law' },
      { ru: 'Третий закон Ньютона', en: 'Newton\'s third law' },
      { ru: 'Закон Гука', en: 'Hooke\'s law' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-69',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой элемент имеет атомный номер 79?',
    questionEn: 'What element has atomic number 79?',
    options: [
      { ru: 'Серебро', en: 'Silver' },
      { ru: 'Золото', en: 'Gold' },
      { ru: 'Платина', en: 'Platinum' },
      { ru: 'Медь', en: 'Copper' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-70',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется наименьшая структурная единица живого организма?',
    questionEn: 'What is the smallest structural unit of a living organism?',
    options: [
      { ru: 'Атом', en: 'Atom' },
      { ru: 'Молекула', en: 'Molecule' },
      { ru: 'Клетка', en: 'Cell' },
      { ru: 'Ткань', en: 'Tissue' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-71',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип связи удерживает атомы в молекуле воды?',
    questionEn: 'What type of bond holds atoms together in a water molecule?',
    options: [
      { ru: 'Ионная', en: 'Ionic' },
      { ru: 'Ковалентная', en: 'Covalent' },
      { ru: 'Металлическая', en: 'Metallic' },
      { ru: 'Водородная', en: 'Hydrogen' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-72',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой учёный открыл пенициллин?',
    questionEn: 'Which scientist discovered penicillin?',
    options: [
      { ru: 'Луи Пастер', en: 'Louis Pasteur' },
      { ru: 'Александр Флеминг', en: 'Alexander Fleming' },
      { ru: 'Роберт Кох', en: 'Robert Koch' },
      { ru: 'Эдвард Дженнер', en: 'Edward Jenner' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-73',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Что такое митохондрия?',
    questionEn: 'What is a mitochondrion?',
    options: [
      { ru: 'Хранилище ДНК', en: 'DNA storage' },
      { ru: 'Энергетическая станция клетки', en: 'Powerhouse of the cell' },
      { ru: 'Клеточная мембрана', en: 'Cell membrane' },
      { ru: 'Центр деления', en: 'Division center' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-74',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой гормон регулирует уровень сахара в крови?',
    questionEn: 'What hormone regulates blood sugar levels?',
    options: [
      { ru: 'Адреналин', en: 'Adrenaline' },
      { ru: 'Тестостерон', en: 'Testosterone' },
      { ru: 'Инсулин', en: 'Insulin' },
      { ru: 'Тироксин', en: 'Thyroxine' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-75',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой процесс превращает жидкость в газ?',
    questionEn: 'What process turns a liquid into a gas?',
    options: [
      { ru: 'Конденсация', en: 'Condensation' },
      { ru: 'Сублимация', en: 'Sublimation' },
      { ru: 'Испарение', en: 'Evaporation' },
      { ru: 'Плавление', en: 'Melting' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-76',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется прибор для измерения атмосферного давления?',
    questionEn: 'What instrument measures atmospheric pressure?',
    options: [
      { ru: 'Гигрометр', en: 'Hygrometer' },
      { ru: 'Барометр', en: 'Barometer' },
      { ru: 'Амперметр', en: 'Ammeter' },
      { ru: 'Спектрометр', en: 'Spectrometer' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-77',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какова скорость света в вакууме (приблизительно)?',
    questionEn: 'What is the approximate speed of light in a vacuum?',
    options: [
      { ru: '300 000 км/с', en: '300,000 km/s' },
      { ru: '150 000 км/с', en: '150,000 km/s' },
      { ru: '500 000 км/с', en: '500,000 km/s' },
      { ru: '1 000 000 км/с', en: '1,000,000 km/s' },
    ],
    correctIndex: 0,
    timeLimit: 20,
  },
  {
    id: 'sci-78',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой орган вырабатывает желчь?',
    questionEn: 'Which organ produces bile?',
    options: [
      { ru: 'Желудок', en: 'Stomach' },
      { ru: 'Поджелудочная железа', en: 'Pancreas' },
      { ru: 'Печень', en: 'Liver' },
      { ru: 'Селезёнка', en: 'Spleen' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-79',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой тип излучения используется в микроволновой печи?',
    questionEn: 'What type of radiation is used in a microwave oven?',
    options: [
      { ru: 'Инфракрасное', en: 'Infrared' },
      { ru: 'Ультрафиолетовое', en: 'Ultraviolet' },
      { ru: 'Микроволновое', en: 'Microwave' },
      { ru: 'Рентгеновское', en: 'X-ray' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },
  {
    id: 'sci-80',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какая кислота содержится в желудочном соке?',
    questionEn: 'What acid is found in stomach juice?',
    options: [
      { ru: 'Серная', en: 'Sulfuric' },
      { ru: 'Соляная', en: 'Hydrochloric' },
      { ru: 'Азотная', en: 'Nitric' },
      { ru: 'Уксусная', en: 'Acetic' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-81',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Как называется явление преломления света в каплях воды?',
    questionEn: 'What is the phenomenon of light refraction in water droplets called?',
    options: [
      { ru: 'Дифракция', en: 'Diffraction' },
      { ru: 'Радуга', en: 'Rainbow' },
      { ru: 'Мираж', en: 'Mirage' },
      { ru: 'Интерференция', en: 'Interference' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-82',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой витамин помогает усваивать кальций?',
    questionEn: 'Which vitamin helps absorb calcium?',
    options: [
      { ru: 'Витамин A', en: 'Vitamin A' },
      { ru: 'Витамин B6', en: 'Vitamin B6' },
      { ru: 'Витамин C', en: 'Vitamin C' },
      { ru: 'Витамин D', en: 'Vitamin D' },
    ],
    correctIndex: 3,
    timeLimit: 20,
  },
  {
    id: 'sci-83',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Какой планетой Солнечной системы является самая большая?',
    questionEn: 'What is the largest planet in the Solar System?',
    options: [
      { ru: 'Сатурн', en: 'Saturn' },
      { ru: 'Юпитер', en: 'Jupiter' },
      { ru: 'Нептун', en: 'Neptune' },
      { ru: 'Уран', en: 'Uranus' },
    ],
    correctIndex: 1,
    timeLimit: 20,
  },
  {
    id: 'sci-84',
    topic: 'science',
    difficulty: 'medium',
    questionRu: 'Что такое pH 7?',
    questionEn: 'What does a pH of 7 indicate?',
    options: [
      { ru: 'Кислая среда', en: 'Acidic' },
      { ru: 'Щелочная среда', en: 'Alkaline' },
      { ru: 'Нейтральная среда', en: 'Neutral' },
      { ru: 'Сильная кислота', en: 'Strong acid' },
    ],
    correctIndex: 2,
    timeLimit: 20,
  },

  // ============================================================
  // === BATCH 2 — HARD (85-100) ===
  // ============================================================
  {
    id: 'sci-85',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой эффект описывает изменение частоты волны при движении источника?',
    questionEn: 'What effect describes the change in wave frequency due to source movement?',
    options: [
      { ru: 'Эффект Комптона', en: 'Compton effect' },
      { ru: 'Эффект Доплера', en: 'Doppler effect' },
      { ru: 'Эффект Холла', en: 'Hall effect' },
      { ru: 'Эффект Керра', en: 'Kerr effect' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-86',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая постоянная обозначается буквой G и описывает гравитационное взаимодействие?',
    questionEn: 'What constant is denoted by G and describes gravitational interaction?',
    options: [
      { ru: 'Постоянная Больцмана', en: 'Boltzmann constant' },
      { ru: 'Постоянная Планка', en: 'Planck constant' },
      { ru: 'Гравитационная постоянная', en: 'Gravitational constant' },
      { ru: 'Постоянная Авогадро', en: 'Avogadro constant' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-87',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой процесс происходит в ядре звезды для выработки энергии?',
    questionEn: 'What process occurs in a star\'s core to produce energy?',
    options: [
      { ru: 'Ядерный распад', en: 'Nuclear fission' },
      { ru: 'Термоядерный синтез', en: 'Nuclear fusion' },
      { ru: 'Аннигиляция', en: 'Annihilation' },
      { ru: 'Радиоактивный распад', en: 'Radioactive decay' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-88',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что описывает принцип неопределённости Гейзенберга?',
    questionEn: 'What does Heisenberg\'s uncertainty principle describe?',
    options: [
      { ru: 'Невозможность создать вечный двигатель', en: 'Impossibility of perpetual motion' },
      { ru: 'Невозможно одновременно точно измерить координату и импульс частицы', en: 'Cannot precisely measure both position and momentum simultaneously' },
      { ru: 'Энергия всегда сохраняется', en: 'Energy is always conserved' },
      { ru: 'Скорость света постоянна', en: 'Speed of light is constant' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-89',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой учёный предложил планетарную модель атома?',
    questionEn: 'Which scientist proposed the planetary model of the atom?',
    options: [
      { ru: 'Нильс Бор', en: 'Niels Bohr' },
      { ru: 'Эрнест Резерфорд', en: 'Ernest Rutherford' },
      { ru: 'Джозеф Томсон', en: 'J.J. Thomson' },
      { ru: 'Джеймс Чедвик', en: 'James Chadwick' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-90',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой тип РНК переносит аминокислоты к рибосоме?',
    questionEn: 'What type of RNA carries amino acids to the ribosome?',
    options: [
      { ru: 'мРНК', en: 'mRNA' },
      { ru: 'тРНК', en: 'tRNA' },
      { ru: 'рРНК', en: 'rRNA' },
      { ru: 'миРНК', en: 'miRNA' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-91',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какое число Авогадро (приблизительно)?',
    questionEn: 'What is Avogadro\'s number (approximately)?',
    options: [
      { ru: '6.02 × 10²³', en: '6.02 × 10²³' },
      { ru: '3.14 × 10²³', en: '3.14 × 10²³' },
      { ru: '6.02 × 10²⁰', en: '6.02 × 10²⁰' },
      { ru: '9.81 × 10²³', en: '9.81 × 10²³' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'sci-92',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Как называется самая длинная кость в теле человека?',
    questionEn: 'What is the longest bone in the human body?',
    options: [
      { ru: 'Плечевая кость', en: 'Humerus' },
      { ru: 'Большеберцовая кость', en: 'Tibia' },
      { ru: 'Бедренная кость', en: 'Femur' },
      { ru: 'Лучевая кость', en: 'Radius' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-93',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой закон термодинамики утверждает, что энтропия изолированной системы не убывает?',
    questionEn: 'Which law of thermodynamics states that entropy of an isolated system never decreases?',
    options: [
      { ru: 'Нулевой', en: 'Zeroth' },
      { ru: 'Первый', en: 'First' },
      { ru: 'Второй', en: 'Second' },
      { ru: 'Третий', en: 'Third' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-94',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой элемент является основой органической химии?',
    questionEn: 'What element is the basis of organic chemistry?',
    options: [
      { ru: 'Кислород', en: 'Oxygen' },
      { ru: 'Водород', en: 'Hydrogen' },
      { ru: 'Углерод', en: 'Carbon' },
      { ru: 'Азот', en: 'Nitrogen' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-95',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какая сила удерживает протоны и нейтроны в ядре атома?',
    questionEn: 'What force holds protons and neutrons together in an atomic nucleus?',
    options: [
      { ru: 'Электромагнитная', en: 'Electromagnetic' },
      { ru: 'Гравитационная', en: 'Gravitational' },
      { ru: 'Сильная ядерная', en: 'Strong nuclear' },
      { ru: 'Слабая ядерная', en: 'Weak nuclear' },
    ],
    correctIndex: 2,
    timeLimit: 25,
  },
  {
    id: 'sci-96',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Что такое красное смещение в астрономии?',
    questionEn: 'What is redshift in astronomy?',
    options: [
      { ru: 'Изменение цвета звёзд при вращении', en: 'Color change of stars during rotation' },
      { ru: 'Увеличение длины волны света от удаляющегося объекта', en: 'Increase in wavelength of light from a receding object' },
      { ru: 'Поглощение света атмосферой', en: 'Absorption of light by atmosphere' },
      { ru: 'Отражение света от планет', en: 'Reflection of light from planets' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-97',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой учёный сформулировал теорию эволюции путём естественного отбора?',
    questionEn: 'Which scientist formulated the theory of evolution by natural selection?',
    options: [
      { ru: 'Грегор Мендель', en: 'Gregor Mendel' },
      { ru: 'Чарльз Дарвин', en: 'Charles Darwin' },
      { ru: 'Жан-Батист Ламарк', en: 'Jean-Baptiste Lamarck' },
      { ru: 'Альфред Уоллес', en: 'Alfred Wallace' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-98',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какова приблизительная масса электрона?',
    questionEn: 'What is the approximate mass of an electron?',
    options: [
      { ru: '9.1 × 10⁻³¹ кг', en: '9.1 × 10⁻³¹ kg' },
      { ru: '1.6 × 10⁻¹⁹ кг', en: '1.6 × 10⁻¹⁹ kg' },
      { ru: '9.1 × 10⁻²⁸ кг', en: '9.1 × 10⁻²⁸ kg' },
      { ru: '1.67 × 10⁻²⁷ кг', en: '1.67 × 10⁻²⁷ kg' },
    ],
    correctIndex: 0,
    timeLimit: 25,
  },
  {
    id: 'sci-99',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой тип химической реакции происходит при горении?',
    questionEn: 'What type of chemical reaction occurs during combustion?',
    options: [
      { ru: 'Восстановление', en: 'Reduction' },
      { ru: 'Окисление', en: 'Oxidation' },
      { ru: 'Гидролиз', en: 'Hydrolysis' },
      { ru: 'Нейтрализация', en: 'Neutralization' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  {
    id: 'sci-100',
    topic: 'science',
    difficulty: 'hard',
    questionRu: 'Какой феномен объясняет, почему небо голубое?',
    questionEn: 'What phenomenon explains why the sky is blue?',
    options: [
      { ru: 'Отражение от океана', en: 'Ocean reflection' },
      { ru: 'Рассеяние Рэлея', en: 'Rayleigh scattering' },
      { ru: 'Преломление в озоновом слое', en: 'Ozone layer refraction' },
      { ru: 'Поглощение ультрафиолета', en: 'UV absorption' },
    ],
    correctIndex: 1,
    timeLimit: 25,
  },
  // ============================================================
  // === BATCH 3 — EASY (101-117) ===
  // ============================================================
  { id: 'sci-101', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой орган качает кровь по телу?', questionEn: 'Which organ pumps blood through the body?', options: [{ ru: 'Лёгкие', en: 'Lungs' }, { ru: 'Сердце', en: 'Heart' }, { ru: 'Печень', en: 'Liver' }, { ru: 'Мозг', en: 'Brain' }], correctIndex: 1 },
  { id: 'sci-102', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какое вещество покрывает зубы снаружи?', questionEn: 'What substance covers the outside of teeth?', options: [{ ru: 'Кератин', en: 'Keratin' }, { ru: 'Эмаль', en: 'Enamel' }, { ru: 'Кальций', en: 'Calcium' }, { ru: 'Хрящ', en: 'Cartilage' }], correctIndex: 1 },
  { id: 'sci-103', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая планета известна своими кольцами?', questionEn: 'Which planet is famous for its rings?', options: [{ ru: 'Юпитер', en: 'Jupiter' }, { ru: 'Сатурн', en: 'Saturn' }, { ru: 'Уран', en: 'Uranus' }, { ru: 'Нептун', en: 'Neptune' }], correctIndex: 1 },
  { id: 'sci-104', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Как называется наука о погоде?', questionEn: 'What is the science of weather called?', options: [{ ru: 'Геология', en: 'Geology' }, { ru: 'Метеорология', en: 'Meteorology' }, { ru: 'Астрономия', en: 'Astronomy' }, { ru: 'Экология', en: 'Ecology' }], correctIndex: 1 },
  { id: 'sci-105', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Сколько зубов у взрослого человека?', questionEn: 'How many teeth does an adult human have?', options: [{ ru: '28', en: '28' }, { ru: '32', en: '32' }, { ru: '36', en: '36' }, { ru: '24', en: '24' }], correctIndex: 1 },
  { id: 'sci-106', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой цвет получится при смешении красного и синего?', questionEn: 'What color do you get by mixing red and blue?', options: [{ ru: 'Зелёный', en: 'Green' }, { ru: 'Фиолетовый', en: 'Purple' }, { ru: 'Оранжевый', en: 'Orange' }, { ru: 'Коричневый', en: 'Brown' }], correctIndex: 1 },
  { id: 'sci-107', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какое животное является символом медлительности?', questionEn: 'Which animal is a symbol of slowness?', options: [{ ru: 'Черепаха', en: 'Turtle' }, { ru: 'Ленивец', en: 'Sloth' }, { ru: 'Улитка', en: 'Snail' }, { ru: 'Коала', en: 'Koala' }], correctIndex: 2 },
  { id: 'sci-108', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Из чего состоят облака?', questionEn: 'What are clouds made of?', options: [{ ru: 'Дым', en: 'Smoke' }, { ru: 'Водяной пар и капельки', en: 'Water vapor and droplets' }, { ru: 'Пыль', en: 'Dust' }, { ru: 'Кислород', en: 'Oxygen' }], correctIndex: 1 },
  { id: 'sci-109', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой орган отвечает за зрение?', questionEn: 'Which organ is responsible for vision?', options: [{ ru: 'Ухо', en: 'Ear' }, { ru: 'Глаз', en: 'Eye' }, { ru: 'Нос', en: 'Nose' }, { ru: 'Язык', en: 'Tongue' }], correctIndex: 1 },
  { id: 'sci-110', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какое самое твёрдое природное вещество?', questionEn: 'What is the hardest natural substance?', options: [{ ru: 'Золото', en: 'Gold' }, { ru: 'Алмаз', en: 'Diamond' }, { ru: 'Железо', en: 'Iron' }, { ru: 'Кварц', en: 'Quartz' }], correctIndex: 1 },
  { id: 'sci-111', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая сила притягивает предметы к Земле?', questionEn: 'What force pulls objects toward Earth?', options: [{ ru: 'Магнитная', en: 'Magnetic' }, { ru: 'Гравитация', en: 'Gravity' }, { ru: 'Трение', en: 'Friction' }, { ru: 'Инерция', en: 'Inertia' }], correctIndex: 1 },
  { id: 'sci-112', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой газ выдыхает человек?', questionEn: 'What gas does a human exhale?', options: [{ ru: 'Кислород', en: 'Oxygen' }, { ru: 'Углекислый газ', en: 'Carbon dioxide' }, { ru: 'Азот', en: 'Nitrogen' }, { ru: 'Водород', en: 'Hydrogen' }], correctIndex: 1 },
  { id: 'sci-113', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Сколько литров крови в теле взрослого человека (примерно)?', questionEn: 'How many liters of blood are in an adult body (approximately)?', options: [{ ru: '2 литра', en: '2 liters' }, { ru: '5 литров', en: '5 liters' }, { ru: '8 литров', en: '8 liters' }, { ru: '10 литров', en: '10 liters' }], correctIndex: 1 },
  { id: 'sci-114', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой материк самый холодный?', questionEn: 'Which continent is the coldest?', options: [{ ru: 'Арктика', en: 'Arctic' }, { ru: 'Антарктида', en: 'Antarctica' }, { ru: 'Сибирь', en: 'Siberia' }, { ru: 'Гренландия', en: 'Greenland' }], correctIndex: 1 },
  { id: 'sci-115', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какое животное даёт молоко, которое пьют люди чаще всего?', questionEn: 'Which animal provides the milk most commonly consumed by humans?', options: [{ ru: 'Коза', en: 'Goat' }, { ru: 'Корова', en: 'Cow' }, { ru: 'Овца', en: 'Sheep' }, { ru: 'Буйвол', en: 'Buffalo' }], correctIndex: 1 },
  { id: 'sci-116', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какой химический элемент обозначается буквой O?', questionEn: 'Which chemical element is represented by the letter O?', options: [{ ru: 'Золото', en: 'Gold' }, { ru: 'Кислород', en: 'Oxygen' }, { ru: 'Осмий', en: 'Osmium' }, { ru: 'Олово', en: 'Tin' }], correctIndex: 1 },
  { id: 'sci-117', topic: 'science', difficulty: 'easy', timeLimit: 15, questionRu: 'Какая часть растения поглощает воду из почвы?', questionEn: 'Which part of a plant absorbs water from the soil?', options: [{ ru: 'Листья', en: 'Leaves' }, { ru: 'Корни', en: 'Roots' }, { ru: 'Стебель', en: 'Stem' }, { ru: 'Цветок', en: 'Flower' }], correctIndex: 1 },
  // ============================================================
  // === BATCH 3 — MEDIUM (118-134) ===
  // ============================================================
  { id: 'sci-118', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой закон описывает зависимость давления газа от объёма?', questionEn: 'Which law describes the relationship between gas pressure and volume?', options: [{ ru: 'Закон Ома', en: 'Ohm\'s law' }, { ru: 'Закон Бойля-Мариотта', en: 'Boyle\'s law' }, { ru: 'Закон Архимеда', en: 'Archimedes\' law' }, { ru: 'Закон Кулона', en: 'Coulomb\'s law' }], correctIndex: 1 },
  { id: 'sci-119', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая железа в мозге регулирует гормональный баланс?', questionEn: 'Which gland in the brain regulates hormonal balance?', options: [{ ru: 'Щитовидная', en: 'Thyroid' }, { ru: 'Гипофиз', en: 'Pituitary' }, { ru: 'Надпочечники', en: 'Adrenal glands' }, { ru: 'Тимус', en: 'Thymus' }], correctIndex: 1 },
  { id: 'sci-120', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой элемент таблицы Менделеева имеет символ Na?', questionEn: 'Which element has the symbol Na?', options: [{ ru: 'Азот', en: 'Nitrogen' }, { ru: 'Натрий', en: 'Sodium' }, { ru: 'Никель', en: 'Nickel' }, { ru: 'Неон', en: 'Neon' }], correctIndex: 1 },
  { id: 'sci-121', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой процесс позволяет клеткам делиться?', questionEn: 'What process allows cells to divide?', options: [{ ru: 'Осмос', en: 'Osmosis' }, { ru: 'Митоз', en: 'Mitosis' }, { ru: 'Фотосинтез', en: 'Photosynthesis' }, { ru: 'Диффузия', en: 'Diffusion' }], correctIndex: 1 },
  { id: 'sci-122', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой металл используется в термометрах старого типа?', questionEn: 'Which metal was used in old-style thermometers?', options: [{ ru: 'Свинец', en: 'Lead' }, { ru: 'Ртуть', en: 'Mercury' }, { ru: 'Олово', en: 'Tin' }, { ru: 'Цинк', en: 'Zinc' }], correctIndex: 1 },
  { id: 'sci-123', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой тип кровеносных сосудов самый мелкий?', questionEn: 'What is the smallest type of blood vessel?', options: [{ ru: 'Артерия', en: 'Artery' }, { ru: 'Капилляр', en: 'Capillary' }, { ru: 'Вена', en: 'Vein' }, { ru: 'Аорта', en: 'Aorta' }], correctIndex: 1 },
  { id: 'sci-124', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая планета вращается «лёжа на боку»?', questionEn: 'Which planet rotates on its side?', options: [{ ru: 'Нептун', en: 'Neptune' }, { ru: 'Уран', en: 'Uranus' }, { ru: 'Венера', en: 'Venus' }, { ru: 'Сатурн', en: 'Saturn' }], correctIndex: 1 },
  { id: 'sci-125', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая единица измерения используется для частоты?', questionEn: 'What unit of measurement is used for frequency?', options: [{ ru: 'Ватт', en: 'Watt' }, { ru: 'Герц', en: 'Hertz' }, { ru: 'Паскаль', en: 'Pascal' }, { ru: 'Джоуль', en: 'Joule' }], correctIndex: 1 },
  { id: 'sci-126', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой белок переносит кислород в крови?', questionEn: 'Which protein carries oxygen in the blood?', options: [{ ru: 'Инсулин', en: 'Insulin' }, { ru: 'Гемоглобин', en: 'Hemoglobin' }, { ru: 'Коллаген', en: 'Collagen' }, { ru: 'Кератин', en: 'Keratin' }], correctIndex: 1 },
  { id: 'sci-127', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какая кислота содержится в лимоне?', questionEn: 'What acid is found in lemons?', options: [{ ru: 'Уксусная', en: 'Acetic' }, { ru: 'Лимонная', en: 'Citric' }, { ru: 'Молочная', en: 'Lactic' }, { ru: 'Яблочная', en: 'Malic' }], correctIndex: 1 },
  { id: 'sci-128', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой учёный открыл закон всемирного тяготения?', questionEn: 'Which scientist discovered the law of universal gravitation?', options: [{ ru: 'Галилей', en: 'Galileo' }, { ru: 'Ньютон', en: 'Newton' }, { ru: 'Эйнштейн', en: 'Einstein' }, { ru: 'Кеплер', en: 'Kepler' }], correctIndex: 1 },
  { id: 'sci-129', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой орган вырабатывает инсулин?', questionEn: 'Which organ produces insulin?', options: [{ ru: 'Печень', en: 'Liver' }, { ru: 'Поджелудочная железа', en: 'Pancreas' }, { ru: 'Почки', en: 'Kidneys' }, { ru: 'Селезёнка', en: 'Spleen' }], correctIndex: 1 },
  { id: 'sci-130', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой слой атмосферы содержит озоновый слой?', questionEn: 'Which layer of the atmosphere contains the ozone layer?', options: [{ ru: 'Тропосфера', en: 'Troposphere' }, { ru: 'Стратосфера', en: 'Stratosphere' }, { ru: 'Мезосфера', en: 'Mesosphere' }, { ru: 'Термосфера', en: 'Thermosphere' }], correctIndex: 1 },
  { id: 'sci-131', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой тип линзы используется для коррекции близорукости?', questionEn: 'What type of lens is used to correct nearsightedness?', options: [{ ru: 'Выпуклая', en: 'Convex' }, { ru: 'Вогнутая', en: 'Concave' }, { ru: 'Плоская', en: 'Flat' }, { ru: 'Цилиндрическая', en: 'Cylindrical' }], correctIndex: 1 },
  { id: 'sci-132', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой газ используется в воздушных шарах для полёта?', questionEn: 'What gas is used in balloons to make them float?', options: [{ ru: 'Водород', en: 'Hydrogen' }, { ru: 'Гелий', en: 'Helium' }, { ru: 'Неон', en: 'Neon' }, { ru: 'Аргон', en: 'Argon' }], correctIndex: 1 },
  { id: 'sci-133', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какое явление вызывает приливы и отливы?', questionEn: 'What phenomenon causes tides?', options: [{ ru: 'Ветер', en: 'Wind' }, { ru: 'Притяжение Луны', en: 'Moon\'s gravity' }, { ru: 'Вращение Земли', en: 'Earth\'s rotation' }, { ru: 'Солнечное излучение', en: 'Solar radiation' }], correctIndex: 1 },
  { id: 'sci-134', topic: 'science', difficulty: 'medium', timeLimit: 20, questionRu: 'Какой витамин необходим для свёртывания крови?', questionEn: 'Which vitamin is essential for blood clotting?', options: [{ ru: 'Витамин A', en: 'Vitamin A' }, { ru: 'Витамин K', en: 'Vitamin K' }, { ru: 'Витамин E', en: 'Vitamin E' }, { ru: 'Витамин B12', en: 'Vitamin B12' }], correctIndex: 1 },
  // ============================================================
  // === BATCH 3 — HARD (135-150) ===
  // ============================================================
  { id: 'sci-135', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой принцип гласит, что тело, погружённое в жидкость, теряет в весе?', questionEn: 'Which principle states that a body immersed in fluid loses weight?', options: [{ ru: 'Принцип Паскаля', en: 'Pascal\'s principle' }, { ru: 'Закон Архимеда', en: 'Archimedes\' principle' }, { ru: 'Закон Бернулли', en: 'Bernoulli\'s law' }, { ru: 'Закон Гука', en: 'Hooke\'s law' }], correctIndex: 1 },
  { id: 'sci-136', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая частица имеет положительный заряд в атоме?', questionEn: 'Which particle has a positive charge in an atom?', options: [{ ru: 'Электрон', en: 'Electron' }, { ru: 'Протон', en: 'Proton' }, { ru: 'Нейтрон', en: 'Neutron' }, { ru: 'Фотон', en: 'Photon' }], correctIndex: 1 },
  { id: 'sci-137', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой тип связи образуется между ионами натрия и хлора?', questionEn: 'What type of bond forms between sodium and chlorine ions?', options: [{ ru: 'Ковалентная', en: 'Covalent' }, { ru: 'Ионная', en: 'Ionic' }, { ru: 'Металлическая', en: 'Metallic' }, { ru: 'Водородная', en: 'Hydrogen' }], correctIndex: 1 },
  { id: 'sci-138', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какое явление описывает туннелирование частиц через потенциальный барьер?', questionEn: 'What phenomenon describes particles tunneling through a potential barrier?', options: [{ ru: 'Дифракция', en: 'Diffraction' }, { ru: 'Квантовое туннелирование', en: 'Quantum tunneling' }, { ru: 'Интерференция', en: 'Interference' }, { ru: 'Поляризация', en: 'Polarization' }], correctIndex: 1 },
  { id: 'sci-139', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой учёный открыл структуру ДНК?', questionEn: 'Which scientists discovered the structure of DNA?', options: [{ ru: 'Мендель и Дарвин', en: 'Mendel and Darwin' }, { ru: 'Уотсон и Крик', en: 'Watson and Crick' }, { ru: 'Пастер и Кох', en: 'Pasteur and Koch' }, { ru: 'Флеминг и Бор', en: 'Fleming and Bohr' }], correctIndex: 1 },
  { id: 'sci-140', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой спутник Юпитера имеет подлёдный океан?', questionEn: 'Which moon of Jupiter has a subsurface ocean?', options: [{ ru: 'Ио', en: 'Io' }, { ru: 'Европа', en: 'Europa' }, { ru: 'Ганимед', en: 'Ganymede' }, { ru: 'Каллисто', en: 'Callisto' }], correctIndex: 1 },
  { id: 'sci-141', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой изотоп углерода используется для радиоуглеродного датирования?', questionEn: 'Which carbon isotope is used for radiocarbon dating?', options: [{ ru: 'C-12', en: 'C-12' }, { ru: 'C-14', en: 'C-14' }, { ru: 'C-13', en: 'C-13' }, { ru: 'C-16', en: 'C-16' }], correctIndex: 1 },
  { id: 'sci-142', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой эффект используется в лазерах?', questionEn: 'What effect is used in lasers?', options: [{ ru: 'Спонтанное излучение', en: 'Spontaneous emission' }, { ru: 'Вынужденное излучение', en: 'Stimulated emission' }, { ru: 'Тепловое излучение', en: 'Thermal emission' }, { ru: 'Черенковское излучение', en: 'Cherenkov radiation' }], correctIndex: 1 },
  { id: 'sci-143', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой тип иммунитета формируется после вакцинации?', questionEn: 'What type of immunity is formed after vaccination?', options: [{ ru: 'Врождённый', en: 'Innate' }, { ru: 'Приобретённый активный', en: 'Acquired active' }, { ru: 'Пассивный', en: 'Passive' }, { ru: 'Неспецифический', en: 'Nonspecific' }], correctIndex: 1 },
  { id: 'sci-144', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой закон связывает электрическое поле и магнитный поток?', questionEn: 'Which law relates electric field and magnetic flux?', options: [{ ru: 'Закон Кулона', en: 'Coulomb\'s law' }, { ru: 'Закон Фарадея', en: 'Faraday\'s law' }, { ru: 'Закон Ома', en: 'Ohm\'s law' }, { ru: 'Закон Ампера', en: 'Ampère\'s law' }], correctIndex: 1 },
  { id: 'sci-145', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой тип звезды образуется после взрыва сверхновой?', questionEn: 'What type of star forms after a supernova explosion?', options: [{ ru: 'Красный гигант', en: 'Red giant' }, { ru: 'Нейтронная звезда', en: 'Neutron star' }, { ru: 'Белый карлик', en: 'White dwarf' }, { ru: 'Протозвезда', en: 'Protostar' }], correctIndex: 1 },
  { id: 'sci-146', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой процесс лежит в основе технологии CRISPR?', questionEn: 'What process is the basis of CRISPR technology?', options: [{ ru: 'Клонирование', en: 'Cloning' }, { ru: 'Редактирование генов', en: 'Gene editing' }, { ru: 'Секвенирование', en: 'Sequencing' }, { ru: 'Трансплантация', en: 'Transplantation' }], correctIndex: 1 },
  { id: 'sci-147', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какая константа определяет скорость электромагнитного взаимодействия?', questionEn: 'Which constant determines the strength of electromagnetic interaction?', options: [{ ru: 'Постоянная Планка', en: 'Planck constant' }, { ru: 'Постоянная тонкой структуры', en: 'Fine-structure constant' }, { ru: 'Постоянная Больцмана', en: 'Boltzmann constant' }, { ru: 'Число Авогадро', en: 'Avogadro\'s number' }], correctIndex: 1 },
  { id: 'sci-148', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой полимер составляет основу пластиковых бутылок?', questionEn: 'What polymer is the main component of plastic bottles?', options: [{ ru: 'Полиэтилен', en: 'Polyethylene' }, { ru: 'Полиэтилентерефталат (ПЭТ)', en: 'PET' }, { ru: 'Поливинилхлорид', en: 'PVC' }, { ru: 'Полистирол', en: 'Polystyrene' }], correctIndex: 1 },
  { id: 'sci-149', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какой орган человека может регенерировать свою ткань?', questionEn: 'Which human organ can regenerate its own tissue?', options: [{ ru: 'Сердце', en: 'Heart' }, { ru: 'Печень', en: 'Liver' }, { ru: 'Почки', en: 'Kidneys' }, { ru: 'Лёгкие', en: 'Lungs' }], correctIndex: 1 },
  { id: 'sci-150', topic: 'science', difficulty: 'hard', timeLimit: 25, questionRu: 'Какое состояние вещества существует при экстремально высоких температурах?', questionEn: 'What state of matter exists at extremely high temperatures?', options: [{ ru: 'Газ', en: 'Gas' }, { ru: 'Плазма', en: 'Plasma' }, { ru: 'Конденсат Бозе-Эйнштейна', en: 'Bose-Einstein condensate' }, { ru: 'Сверхтекучая жидкость', en: 'Superfluid' }], correctIndex: 1 },
];
