'use client';

import { motion } from 'framer-motion';
import { ANSWERS, cinematic, PhoneFrame, spring, TvFrame } from './ConceptPrimitives';

export function StudioConcept({ reduced }: { reduced: boolean }) {
  const bulbs = reduced ? undefined : { opacity: [0.35, 1, 0.35], scale: [0.85, 1.15, 0.85] };
  return <div className="mt-10 grid items-start gap-8 lg:grid-cols-[326px_1fr]">
    <PhoneFrame className="bg-[#71152b] font-serif text-[#2b1520]">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_12%,#ba5261_0,transparent_38%),linear-gradient(180deg,transparent,#420817)]" />
      <div className="relative mt-5 text-center text-[#f8e6bd]"><div className="text-[9px] font-bold uppercase tracking-[0.28em] opacity-65">Прямой эфир</div><div className="mt-1 text-2xl font-black tracking-[-0.04em]">СТО К ОДНОМУ</div></div>
      <div className="relative mt-5 flex justify-center gap-2">{Array.from({ length: 13 }, (_, index) => <motion.i key={index} animate={bulbs} transition={{ duration: 1.8, repeat: Infinity, delay: index * 0.08 }} className="h-1.5 w-1.5 rounded-full bg-[#ffd77b] shadow-[0_0_8px_#ffd77b]" />)}</div>
      <motion.div initial={{ rotateX: -18, opacity: 0 }} animate={{ rotateX: 0, opacity: 1 }} transition={{ ...spring, delay: 0.15 }} className="relative mt-4 rounded-[20px] border-[3px] border-[#d4a94f] bg-[#f4e4c0] p-4 shadow-[0_18px_45px_-18px_#2a030e]"><span className="text-[9px] font-bold uppercase tracking-[0.16em] text-[#8a2638]">Вопрос раунда</span><h4 className="mt-2 text-[18px] font-black leading-tight">Что люди чаще всего забывают дома?</h4><div className="mt-4 space-y-2 font-sans">{ANSWERS.map(([answer, points], index) => <motion.div key={answer} initial={{ rotateX: 90 }} animate={{ rotateX: 0 }} transition={{ duration: 0.55, delay: 0.35 + index * 0.13, ease: cinematic }} className="flex h-10 items-center rounded-[9px] border border-[#b98c3c] bg-[#30131c] px-3 text-[#ffe7ac] shadow-inner"><span className="text-xs font-black">{index + 1}</span><b className="ml-3 text-xs tracking-[0.05em]">{answer}</b><b className="ml-auto text-base">{points}</b></motion.div>)}</div></motion.div>
      <div className="relative mt-4 grid grid-cols-2 gap-2 font-sans text-[#ffe9bd]"><div className="rounded-[13px] border border-[#e0b65d]/60 bg-[#38101d]/80 px-3 py-2"><small className="block text-[8px] opacity-55">АЛЫЕ</small><b className="text-xl">240</b></div><div className="rounded-[13px] border border-[#e0b65d]/60 bg-[#38101d]/80 px-3 py-2 text-right"><small className="block text-[8px] opacity-55">ЗОЛОТЫЕ</small><b className="text-xl">180</b></div></div>
      <motion.button whileTap={reduced ? undefined : { scale: 0.92 }} animate={reduced ? undefined : { boxShadow: ['0 8px 24px #25030c', '0 8px 40px #ffbb55aa', '0 8px 24px #25030c'] }} transition={{ duration: 2.2, repeat: Infinity }} className="relative mt-auto h-14 rounded-full border-[3px] border-[#f4d18a] bg-[radial-gradient(circle_at_50%_25%,#ff6d55,#9f1428_68%)] font-sans text-sm font-black text-white shadow-xl">ОТКРЫТЬ ОТВЕТ</motion.button>
    </PhoneFrame>
    <TvFrame className="bg-[#32101b] font-serif text-[#f9e8c0]">
      <motion.div animate={reduced ? undefined : { x: ['-20%', '120%'] }} transition={{ duration: 7, repeat: Infinity, ease: 'linear' }} className="absolute -top-1/2 h-[160%] w-1/3 rotate-[18deg] bg-gradient-to-r from-transparent via-[#fff3c4]/12 to-transparent blur-xl" />
      <div className="absolute inset-y-0 left-0 w-[18%] bg-[repeating-linear-gradient(90deg,#4f0c20_0_16px,#71152b_16px_32px)] shadow-[inset_-24px_0_35px_#250711]" /><div className="absolute inset-y-0 right-0 w-[18%] bg-[repeating-linear-gradient(90deg,#71152b_0_16px,#4f0c20_16px_32px)] shadow-[inset_24px_0_35px_#250711]" />
      <div className="relative flex h-full flex-col items-center px-[18%] py-[4%]"><div className="text-center"><span className="text-[clamp(8px,1vw,15px)] font-bold uppercase tracking-[0.34em] text-[#e2b95d]">Семейная телеигра</span><h4 className="mt-1 text-[clamp(28px,5vw,72px)] font-black leading-none tracking-[-0.05em]">СТО К ОДНОМУ</h4></div><div className="relative mt-[3%] flex w-full flex-1 items-center justify-center rounded-[34px] border-[5px] border-[#c99c45] bg-[#efe0bb] p-[2.5%] text-[#26141a] shadow-[0_0_0_9px_#5c1527,0_30px_70px_#16030a]"><div className="absolute inset-x-[3%] top-[-12px] flex justify-between">{Array.from({ length: 18 }, (_, index) => <motion.i key={index} animate={bulbs} transition={{ duration: 1.7, repeat: Infinity, delay: index * 0.06 }} className="h-2.5 w-2.5 rounded-full bg-[#ffd471] shadow-[0_0_10px_#ffd471]" />)}</div><div className="w-[82%]"><div className="text-center text-[clamp(13px,2vw,28px)] font-black">Что люди чаще всего забывают дома?</div><div className="mt-[3%] grid grid-cols-2 gap-[3%] font-sans">{ANSWERS.map(([answer, points], index) => <motion.div key={answer} initial={{ y: 18, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ ...spring, delay: 0.2 + index * 0.13 }} className="flex items-center rounded-lg bg-[#32101b] px-[5%] py-[4%] text-[clamp(8px,1.2vw,17px)] text-[#ffe5aa]"><b>{index + 1}</b><span className="ml-[8%] font-black">{answer}</span><b className="ml-auto">{points}</b></motion.div>)}</div></div></div><div className="mt-[3%] flex w-full items-end justify-between font-sans"><div className="rounded-xl border border-[#dcb15a]/50 bg-[#5f1428] px-[5%] py-[2%]"><small className="block text-[8px] opacity-55">КОМАНДА АЛЫЕ</small><b className="text-[clamp(18px,3vw,42px)]">240</b></div><motion.div animate={reduced ? undefined : { y: [0, -5, 0] }} transition={{ duration: 1.7, repeat: Infinity }} className="rounded-full bg-[#d4a84d] px-[4%] py-[1.5%] font-black text-[#36131d]">БАНК · 120</motion.div><div className="rounded-xl border border-[#dcb15a]/50 bg-[#5f1428] px-[5%] py-[2%] text-right"><small className="block text-[8px] opacity-55">КОМАНДА ЗОЛОТЫЕ</small><b className="text-[clamp(18px,3vw,42px)]">180</b></div></div></div>
    </TvFrame>
  </div>;
}
